const {_electron:electron}=require('playwright-core');const assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),http=require('node:http'),AdmZip=require('adm-zip');
async function waitForFile(file){for(let i=0;i<100;i++){try{return await fs.readFile(file);}catch(e){if(e.code!=='ENOENT')throw e;await new Promise(resolve=>setTimeout(resolve,100));}}throw Error('导出未在 10 秒内生成文件：'+file);}
(async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'director-desktop-'));let app,server,requests=0,mode='valid',payload;const errors=[];const env={...process.env,DIRECTOR_DATA_DIR:path.join(root,'data'),DIRECTOR_HEADLESS:'1'};delete env.ELECTRON_RUN_AS_NODE;
try{server=http.createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;if(req.url==='/v1/models'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({data:[{id:'mock-director'}]}));return;}requests++;if(mode==='retry'&&requests===1){res.writeHead(429);res.end('{}');return;}if(mode==='cancel'){req.on('close',()=>{});setTimeout(()=>{if(!res.destroyed)res.end('{}');},6000);return;}const input=JSON.parse(raw);const user=input.messages.at(-1).content;const value=user.includes('connected')?'{"connected":true}':mode==='malformed'&&requests===1?'invalid JSON':JSON.stringify(payload||{ok:true});res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:value},finish_reason:'stop'}],usage:{prompt_tokens:50,completion_tokens:100}}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
app=await electron.launch({executablePath:require('electron'),args:[path.resolve('.')],env});const page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].showInactive());page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('#content [data-action="new-project"]');await page.locator('#content [data-action="new-project"]').first().click();await page.locator('#new-name').fill('本机验证项目');await page.locator('#modal-submit').click();await page.waitForSelector('[data-action="sample"]',{state:'attached'});await page.locator('.page-head .more-menu summary').click();await page.locator('[data-action="sample"]').click();await page.waitForFunction(()=>S.project?.name==='原创示例 · 雨夜归还'&&C.audit(S.project,selectedSequence(),selectedSequence().segments[0]).length===0);assert.deepEqual(await page.evaluate(()=>C.audit(S.project,selectedSequence(),selectedSequence().segments[0])),[]);console.log('PASS 创建项目、原创示例、状态审查');
await page.locator('[data-action="segment-tools"]').first().click();await page.waitForSelector('.stage-map');await page.locator('[data-action="close-modal"]').first().click();await page.locator('[data-action="review"]').first().click();await page.locator('#modal-submit').click();await page.waitForFunction(()=>S.project.sequences[0].segments[0].reviewed);await page.evaluate(()=>act('page',{page:'delivery'}));await page.locator('[data-action="freeze-delivery"]').click();await page.locator('#modal-submit').click();await page.waitForFunction(()=>S.project.deliveries.length===1);const fingerprint=await page.evaluate(()=>S.project.deliveries[0].fingerprint);console.log('PASS 站位图、人工审核、冻结交付');
const pdf=path.join(root,'book.pdf'),zip=path.join(root,'package.zip');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},pdf);await page.locator('[data-action="export-delivery"][data-format="pdf"]').click();assert.equal((await waitForFile(pdf)).subarray(0,4).toString(),'%PDF');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},zip);await page.locator('[data-action="export-delivery"][data-format="zip"]').click();const archive=new AdmZip(await waitForFile(zip));assert.ok(archive.getEntry('director-manifest.json'));assert.ok(archive.getEntries().some(x=>x.entryName.startsWith('tasks/')));console.log('PASS PDF 分镜册、ZIP交付与逐镜任务');
for(const nav of ['home','assets','shots','prompts','memory','facts','knowledge','rules','review','recovery','history','delivery']){await page.evaluate(nav=>act('page',{page:nav}),nav);await page.waitForTimeout(30);assert.ok(await page.locator('#content').evaluate(e=>e.textContent.trim().length>0),nav);}assert.deepEqual(errors,[]);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].showInactive());await page.screenshot({path:path.resolve('desktop-preview.png'),fullPage:false});console.log('PASS 全部12个页面，无未捕获界面异常');
const port=server.address().port;await page.evaluate(async port=>{await call('settings:save',{provider:'local',localUrl:`http://127.0.0.1:${port}/v1`,baseUrl:'https://example.invalid/v1',model:'mock-director',contextTokens:65536,outputTokens:12000,vision:false,stream:false});S.settings=await call('settings:get');},port);const diagnosis=await page.evaluate(()=>call('model:diagnose',{}));assert.equal(diagnosis.structured,true);console.log('PASS 模型连接诊断（模拟服务，无密钥）');
payload=await page.evaluate(()=>{const g=S.project.sequences[0].segments[0];return {requirements:'模拟生成验证',endState:g.endState,stageEnd:g.stageEnd.map(a=>({...a,presence:a.presence||'present'})),shots:g.shots.map(sh=>({...sh,stateIn:sh.stateIn.map(a=>({...a,presence:a.presence||'present'})),stateOut:sh.stateOut.map(a=>({...a,presence:a.presence||'present'})),voice:'无人声',audio:[],actorReactions:sh.stateIn.map(a=>({assetId:a.assetId,text:'自然注视与呼吸'})),presenceEvents:[]}))};});await page.evaluate(()=>{S.page='shots';S.seqId=S.project.sequences[0].id;render();});await page.evaluate(()=>window.lastJobId=S.project.jobs[0]?.id);await page.locator('[data-action="generate-segment"]').first().click();await page.locator('#modal-submit').click();await page.waitForFunction(()=>S.project.jobs[0]?.id!==window.lastJobId);await page.waitForFunction(()=>!S.job&&S.project.jobs[0]?.status==='completed',{},{timeout:15000});assert.equal(await page.evaluate(()=>S.project.sequences[0].segments[0].reviewed),false);assert.equal(await page.evaluate(()=>S.project.deliveries[0].fingerprint),fingerprint);console.log('PASS 模拟分镜生成、取消旧审核、冻结版本不变');
mode='malformed';requests=0;await page.evaluate(()=>window.lastJobId=S.project.jobs[0]?.id);await page.locator('[data-action="generate-segment"]').first().click();await page.locator('#modal-submit').click();await page.waitForFunction(()=>S.project.jobs[0]?.id!==window.lastJobId);await page.waitForFunction(()=>!S.job&&S.project.jobs[0]?.status==='completed',{},{timeout:15000});assert.equal(requests,2);console.log('PASS JSON 格式失败后有限修复');
mode='retry';requests=0;await page.evaluate(()=>window.lastJobId=S.project.jobs[0]?.id);await page.locator('[data-action="generate-segment"]').first().click();await page.locator('#modal-submit').click();await page.waitForFunction(()=>S.project.jobs[0]?.id!==window.lastJobId);await page.waitForFunction(()=>!S.job&&S.project.jobs[0]?.status==='completed',{},{timeout:15000});assert.equal(requests,2);console.log('PASS HTTP 429 退避重试');
mode='cancel';await page.evaluate(()=>window.lastJobId=S.project.jobs[0]?.id);await page.locator('[data-action="generate-segment"]').first().click();await page.locator('#modal-submit').click();await page.waitForFunction(()=>S.project.jobs[0]?.id!==window.lastJobId);await page.waitForFunction(()=>S.job?.requestId);await page.locator('[data-action="cancel-job"]').click();await page.waitForFunction(()=>!S.job,{},{timeout:10000});assert.equal(await page.evaluate(()=>S.project.jobs[0].status),'cancelled');console.log('PASS 取消请求保留检查点');
await page.evaluate(()=>persist());await page.reload();await page.waitForFunction(()=>S.project?.name==='原创示例 · 雨夜归还');assert.equal(await page.evaluate(()=>S.project.deliveries[0].fingerprint),fingerprint);assert.deepEqual(errors,[]);console.log('PASS 数据库保存后重新加载');
await page.evaluate(()=>act('page',{page:'assets'}));await page.locator('[data-action="new-asset"]').click();await page.locator('#asset-name').fill('新道具');await page.locator('#modal-submit').click();await page.waitForFunction(()=>S.project.assets.some(a=>a.name==='新道具'));assert.deepEqual(errors,[]);console.log('PASS 手动新增资产兼容新结构');
console.log('DESKTOP CHECKS PASSED; artifacts='+root);
}finally{if(app)await app.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}if(errors.length)console.error('PAGE ERRORS',errors);}
})().catch(e=>{console.error(e);process.exitCode=1;});



