const {_electron:electron}=require('playwright-core'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),http=require('node:http');
(async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-070-')),requests=[];
 const server=http.createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);requests.push(body);const content=body.messages[1].content,text=content.find(x=>x.type==='text').text,rows=JSON.parse(text.split('镜头资料：')[1]);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({shots:rows.map(x=>({id:x.id,analysis:'可见：色块构图。推测：情绪转换。声音未知。'})),summary:'不同颜色的节奏对照',methods:'在情绪转折处切换构图；不适用于要求连续实时动作的镜头。'})}}]}));});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const env={...process.env,DIRECTOR_DATA_DIR:root,DIRECTOR_HEADLESS:'1'};delete env.ELECTRON_RUN_AS_NODE;
 const app=await electron.launch({executablePath:process.argv[2]?path.resolve(process.argv[2]):require('electron'),args:process.argv[2]?['--disable-backgrounding-occluded-windows']:['--disable-backgrounding-occluded-windows',path.resolve('.')],env}),checks=[],errors=[];
 try{
 const p=await app.firstWindow();p.on('pageerror',e=>errors.push(e.message));await p.waitForFunction(()=>typeof PRODUCT!=='undefined'&&PRODUCT.ready);await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].showInactive());
 await p.evaluate(()=>act('page',{page:'film'}));await p.waitForFunction(()=>FILM.loaded);assert.ok(await p.locator('[data-action="film-import"]').isVisible());checks.push('无项目可独立进入拉片');
 await p.evaluate(()=>createSample());
 for(const page of ['home','assets','shots','workbench','review','delivery']){await p.locator(`.top-stages [data-page="${page}"]`).click();await p.waitForFunction(x=>S.page===x,page);assert.equal(await p.locator('.top-stages [aria-current="page"]').getAttribute('data-page'),page);}
 await p.locator('[data-action="nav-back"]').click();await p.waitForFunction(()=>S.page==='review');assert.equal(await p.evaluate(()=>S.page),'review');await p.locator('[data-action="nav-forward"]').click();await p.waitForFunction(()=>S.page==='delivery');assert.equal(await p.evaluate(()=>S.page),'delivery');assert.ok((await p.locator('.top-stages').boundingBox()).height<=34);assert.equal(await p.locator('.top-stages').evaluate(e=>e.scrollWidth<=e.clientWidth+2),true);await p.evaluate(()=>act('page',{page:'canvas'}));await p.waitForFunction(()=>S.page==='canvas');assert.equal(await p.locator('#nav [data-page="canvas"]').getAttribute('aria-current'),'page');checks.push('顶部线性流程与侧栏独立画布入口、后退和前进恢复');
 await p.evaluate(()=>act('page',{page:'workbench'}));await p.evaluate(()=>act('ws-view',{view:'board'}));await p.evaluate(()=>act('nav-back'));assert.equal(await p.evaluate(()=>WS.view),'studio');checks.push('工作区视图也能返回');
 const pages=await p.locator('#nav [data-page]').evaluateAll(xs=>xs.map(x=>x.dataset.page));for(const page of pages){await p.evaluate(page=>act('page',{page}),page);assert.equal(await p.evaluate(()=>S.page),page);assert.ok((await p.locator('#content').textContent()).length>20);}
 const collapsedBefore=await p.evaluate(()=>Boolean(PRODUCT.personal.sidebarCollapsed));
 await p.evaluate(()=>act('nav-collapse'));
 const collapsedAfter=await p.evaluate(()=>({preference:PRODUCT.personal.sidebarCollapsed,visible:document.body.classList.contains('nav-collapsed')}));
 assert.deepEqual(collapsedAfter,{preference:!collapsedBefore,visible:!collapsedBefore});
 if(!collapsedBefore)assert.ok((await p.locator('.shell>aside').boundingBox()).width<=64);
 await p.evaluate(()=>act('nav-collapse'));
 const restored=await p.evaluate(()=>({preference:PRODUCT.personal.sidebarCollapsed,visible:document.body.classList.contains('nav-collapsed')}));
 assert.deepEqual(restored,{preference:collapsedBefore,visible:collapsedBefore});
 checks.push('全局页面入口与侧栏收起展开');
 await p.evaluate(()=>act('personal-center'));await p.locator('#person-name').fill('我的导演空间');await p.locator('[data-action="u80-settings-tab"][data-id="connections"]').click();await p.locator('#modal-body [data-action="settings"]').click();await p.locator('[data-action="model-new"]').click();await p.locator('#conn-name').fill('未保存的连接');await p.locator('#dialog-back').click();assert.equal(await p.locator('#modal-title').textContent(),'模型中心');await p.locator('#dialog-back').click();assert.equal(await p.locator('#person-name').inputValue(),'我的导演空间');checks.push('嵌套窗口返回保留原表单内容');
 await p.locator('[data-action="u80-settings-tab"][data-id="appearance"]').click();await p.locator('#person-theme').selectOption('system');await p.locator('#person-accent').fill('#834ac9');
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},path.resolve('src/assets/brand/guanlan-new.png'));
 await p.locator('[data-action="u80-settings-tab"][data-id="identity"]').click();await p.locator('[data-action="personal-avatar"]').click();await p.waitForSelector('.personal-avatar[src]');assert.equal(await p.locator('#person-name').inputValue(),'我的导演空间');await p.locator('[data-action="u80-settings-tab"][data-id="appearance"]').click();await p.locator('[data-action="personal-background"]').click();await p.waitForSelector('.wallpaper-preview');await p.locator('#modal-submit').click();await p.waitForFunction(()=>!$('modal').open);await p.locator('header [data-action="personal-center"] .header-avatar[src]').waitFor();
 await p.emulateMedia({colorScheme:'dark'});await p.waitForFunction(()=>document.documentElement.dataset.theme==='dark');await p.emulateMedia({colorScheme:'light'});assert.equal(await p.evaluate(()=>document.documentElement.dataset.theme),'dark');await p.emulateMedia({colorScheme:'dark'});checks.push('头像、背景与配色保存；指定暗色皮肤优先于系统颜色');
 const packets=await p.evaluate(async()=>{const c=document.createElement('canvas');c.width=320;c.height=180;const ctx=c.getContext('2d'),chunks=[];let error;const encoder=new VideoEncoder({output:chunk=>{const data=new Uint8Array(chunk.byteLength);chunk.copyTo(data);chunks.push(Array.from(data));},error:e=>error=e.message});encoder.configure({codec:'vp8',width:320,height:180,bitrate:200000,framerate:1});for(let i=0;i<3;i++){ctx.fillStyle=['#f00000','#00e000','#0000ff'][i];ctx.fillRect(0,0,320,180);const f=new VideoFrame(c,{timestamp:i*1000000,duration:1000000});encoder.encode(f,{keyFrame:true});f.close();}await encoder.flush();encoder.close();if(error)throw Error(error);return chunks;});
 const num=(n)=>{const b=Buffer.alloc(4);b.writeUInt32BE(n);let i=0;while(i<3&&!b[i])i++;return b.subarray(i);},el=(id,data)=>{data=Array.isArray(data)?Buffer.concat(data):Buffer.isBuffer(data)?data:typeof data==='number'?num(data):Buffer.from(data);let n=1;while(data.length>=2**(7*n)-1)n++;const size=Buffer.alloc(n);let v=data.length;for(let i=n-1;i>=0;i--){size[i]=v%256;v=Math.floor(v/256);}size[0]|=1<<(8-n);return Buffer.concat([Buffer.from(id,'hex'),size,data]);};const duration=Buffer.alloc(8);duration.writeDoubleBE(3000);const blocks=packets.map((data,i)=>{const h=Buffer.alloc(4);h[0]=0x81;h.writeInt16BE(i*1000,1);h[3]=0x80;return el('a3',Buffer.concat([h,Buffer.from(data)]));});const bytes=Buffer.concat([el('1a45dfa3',[el('4286',1),el('42f7',1),el('42f2',4),el('42f3',8),el('4282','webm'),el('4287',2),el('4285',2)]),el('18538067',[el('1549a966',[el('2ad7b1',1000000),el('4489',duration),el('4d80','fixture'),el('5741','fixture')]),el('1654ae6b',[el('ae',[el('d7',1),el('73c5',1),el('83',1),el('86','V_VP8'),el('e0',[el('b0',320),el('ba',180)])])]),el('1f43b675',[el('e7',0),...blocks])])]);
 const clip=path.join(root,'test-clip.webm');await fs.writeFile(clip,Buffer.from(bytes));await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},clip);
 await p.evaluate(()=>act('page',{page:'film'}));await p.locator('[data-action="film-import"]').click();await p.waitForFunction(()=>filmCurrent()?.duration>2);const ranged=await p.evaluate(async()=>{const r=await fetch(filmCurrent().sourceVideo,{headers:{Range:'bytes=0-31'}});return [r.status,(await r.arrayBuffer()).byteLength];});assert.deepEqual(ranged,[206,32]);
 await p.locator('.u80-cut-settings summary').click();await p.locator('[data-action="film-detect"]').click();await p.waitForFunction(()=>!S.job&&filmCurrent().shots.length>=2,{},{timeout:45000});await p.evaluate(()=>$('film-player').play());await p.waitForFunction(()=>$('film-player').currentTime>0.5);await p.evaluate(()=>$('film-player').pause());assert.ok(await p.locator('.film-shot img').count()>=2);assert.match(await p.evaluate(()=>filmCurrent().shots[0].frames[0]),/^data:image/);checks.push('本机视频导入、范围播放、真实解码拆帧与候选切点');
 const model=await p.evaluate(async base=>{const c=await call('connections:save',{name:'模拟视觉模型',kind:'chat',provider:'local',baseUrl:base,model:'mock-vision',vision:true,stream:false});await call('connections:activate',c.id);S.settings=await call('settings:get');return c;},'http://127.0.0.1:'+server.address().port+'/v1');
 await p.locator('.u80-cut-settings summary').click();await p.locator('[data-action="film-analyze"]').click();assert.equal(requests.length,0);await p.locator('#modal-submit').click();await p.waitForFunction(()=>!S.job&&filmCurrent().methods.length>0,{},{timeout:45000});assert.equal(requests.length,1);assert.ok(requests[0].messages[1].content.filter(x=>x.type==='image_url').every(x=>x.image_url.url.startsWith('data:image/')));assert.ok(!JSON.stringify(requests).includes('director-video:'));checks.push('确认后发送采样图，模拟模型逐镜分析成功，不发送原视频');
 await p.locator('#film-reviewed').check();await p.locator('[data-action="film-publish"]').click();await p.waitForFunction(()=>S.knowledge.some(x=>x.id.startsWith('filmref_')));assert.equal(await p.evaluate(()=>S.knowledge.find(x=>x.id.startsWith('filmref_')).enabledByDefault),false);await p.locator('[data-action="film-enable"]').click();await p.waitForFunction(()=>S.project.knowledgeOverrides['filmref_'+filmCurrent().id]);assert.match(await p.evaluate(()=>rules(S.project,'analysis','情绪转折 构图')),/拉片参考/);checks.push('审阅后入导演参考库，明确启用才关联当前项目并进入分析上下文');
 const exported=path.join(root,'study.json');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},exported);await p.locator('[data-action="film-export"]').click();await p.locator('#u80-export-format').selectOption('json');await p.locator('#modal-submit').click();await p.waitForFunction(()=>$('toast').textContent.includes('报告已保存'));const study=JSON.parse(await fs.readFile(exported));assert.equal(study.study.sourceVideo,undefined);assert.match(study.study.shots[0].frames[0],/^data:image/);checks.push('拉片导出包含可带走的关键帧和分析');
 await p.evaluate(()=>act('personal-center'));await p.locator('[data-action="u80-settings-tab"][data-id="preferences"]').click();await p.locator('#person-home').selectOption('film');await p.locator('#modal-submit').click();await p.waitForFunction(()=>!$('modal').open);await p.reload();await p.waitForFunction(()=>PRODUCT.ready&&FILM.loaded&&filmCurrent()?.methods);assert.equal(await p.evaluate(()=>PRODUCT.personal.name),'我的导演空间');assert.match(await p.evaluate(()=>filmCurrent().shots[0].frames[0]),/^director-media:/);checks.push('重启保留拉片、关键帧、头像背景与启动偏好');
 await fs.mkdir('audit-evidence/upgrade-070',{recursive:true});await p.waitForTimeout(600);await p.screenshot({path:'audit-evidence/upgrade-070/film.png'});
 await p.evaluate(()=>act('personal-center'));await p.waitForTimeout(300);await p.screenshot({path:'audit-evidence/upgrade-070/personal.png'});await p.evaluate(()=>closeModal());
 assert.deepEqual(errors,[]);await fs.writeFile('audit-evidence/upgrade-070/experience-check.json',JSON.stringify({passed:true,checks,errors},null,2));console.log('PASS '+checks.join('；'));
 }catch(e){const p=await app.firstWindow();console.error('ERRORS',errors,await p.evaluate(()=>({toast:$('toast').textContent,modal:$('modal-title').textContent,page:S.page,film:filmCurrent(),video:(()=>{const v=$('film-player');return v&&{duration:v.duration,ready:v.readyState,error:v.error?.message,src:v.currentSrc}})(),job:S.job})).catch(()=>({})));throw e;}finally{await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await app.close().catch(()=>{});server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
