const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');const generate=require('../src/model-client');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),usageStore=require('../src/usage-store');
async function serverTest(handler,fn){const server=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));try{await fn('http://127.0.0.1:'+server.address().port);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
const setting={model:'mock',contextTokens:65536,outputTokens:8192},input={system:'system',user:'script',requestId:'test'},event={sender:{isDestroyed:()=>false,send:()=>{}}};
test('UTF8流式内容分块正确合并并记录实际usage',async()=>{const progress=[];await serverTest((req,res)=>{res.writeHead(200,{'Content-Type':'text/event-stream'});const bytes=Buffer.from('data: '+JSON.stringify({choices:[{delta:{content:'甲递出钥匙'}}]})+'\n\n');res.write(bytes.subarray(0,bytes.length-5));res.write(bytes.subarray(bytes.length-5));res.end('data: '+JSON.stringify({choices:[{delta:{},finish_reason:'stop'}],usage:{prompt_tokens:42,completion_tokens:7}})+'\n\ndata: [DONE]\n\n');},async base=>{const text=await generate(setting,input,{sender:{isDestroyed:()=>false,send:(_,d)=>progress.push(d)}},new Map(),()=>({base,key:'',local:true}));assert.equal(text,'甲递出钥匙');assert.equal(progress.at(-1).usage.input,42);assert.equal(progress.at(-1).usage.estimated,false);});});
test('观澜成功调用独立记账，记录中不包含提示词或密钥',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-usage-')),store=usageStore(()=>dir);await serverTest((req,res)=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:'镜头完成'},finish_reason:'stop'}],usage:{prompt_tokens:48,completion_tokens:6}}));},async base=>{await generate({...setting,inputPrice:2,outputPrice:4,currency:'CNY'},{...input,user:'private-script'},event,new Map(),()=>({base,key:'private-key',local:true}),usage=>store.append({...usage,id:'call_1',projectId:'p_demo',projectName:'测试项目'}));});const rows=await store.list(),raw=await fs.readFile(path.join(dir,'model-usage.jsonl'),'utf8');assert.equal(rows.length,1);assert.equal(rows[0].input,48);assert.equal(rows[0].output,6);assert.equal(rows[0].estimated,false);assert.ok(rows[0].cost>0);assert.ok(!raw.includes('private-script')&&!raw.includes('private-key'));});
test('未配置单价保持费用未知，不误显示为零元',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-no-price-')),store=usageStore(()=>dir);await store.append({id:'call_2',model:'mock',input:100,output:20,cost:null});assert.equal((await store.list())[0].cost,null);});
test('超出预算不发请求',async()=>{await assert.rejects(generate({...setting,contextTokens:100},input,event,new Map(),()=>({base:'http://127.0.0.1:1',key:'',local:true})),/超过设置/);});
test('未声明视觉能力时不上传图片',async()=>{await assert.rejects(generate(setting,{...input,images:['data:image/png;base64,abc']},event,new Map(),()=>({base:'http://127.0.0.1:1',key:'',local:true})),/视觉/);});
test('输出截断不会被当作成功结果',async()=>{await serverTest((req,res)=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:'不完整'},finish_reason:'length'}]}));},base=>assert.rejects(generate(setting,input,event,new Map(),()=>({base,key:'',local:true})),/截断/));});
test('错误消息不会泄露密钥',async()=>{const key='test_not_real_secret';await serverTest((req,res)=>{res.writeHead(401);res.end('bad '+key);},async base=>{try{await generate(setting,input,event,new Map(),()=>({base,key,local:false}));assert.fail('should throw');}catch(e){assert.ok(!e.message.includes(key));assert.match(e.message,/401/);}});});
test('取消请求能清理运行任务',async()=>{await serverTest((req,res)=>{},async base=>{const requests=new Map();const pending=generate(setting,input,event,requests,()=>({base,key:'',local:true}));requests.get('test').abort();await assert.rejects(pending,/取消/);assert.equal(requests.size,0);});});
