const test=require('node:test'),assert=require('node:assert/strict'),S=require('../src/spatial');
test('非正方形底图坐标、旋转轴与真实比例尺',()=>{const l=S.create();l.scale={a:{x:0,y:0},b:{x:100,y:0},meters:10};assert.deepEqual(S.coord(l,{x:60,y:50}),{x:1,y:0,unit:'米'});assert.ok(Math.abs(S.coord(l,{x:50,y:40}).y-.7)<1e-10);l.axis={x:50,y:20};assert.ok(Math.abs(S.coord(l,{x:50,y:40}).x-.7)<1e-10);});
test('反打与镜像只改变画面关系，不改变场景位置',()=>{const l=S.create(),p={x:30,y:50};assert.match(S.projection(l,{x:50,y:90,tx:50,ty:50},p).label,/左/);assert.match(S.projection(l,{x:50,y:10,tx:50,ty:50},p).label,/右/);assert.match(S.projection(l,{x:50,y:90,tx:50,ty:50,mirror:true},p).label,/右/);assert.deepEqual(p,{x:30,y:50});});
test('明确参照、人体左右手与非空间词识别',()=>{assert.ok(S.lint('他往左走，抬起右手').length>=2);assert.equal(S.lint('以当前镜头画面为准，陈安向左移动').length,0);assert.equal(S.lint('陈安自身右手持钥匙').length,0);assert.ok(S.lint('桌子右侧有一个人').length);assert.equal(S.lint('左右两难，前后两次，停顿3秒左右').length,0);assert.ok(S.lint('move left').length);assert.equal(S.lint('move screen left').length,0);assert.ok(S.lint('陈安左入画').length);});
test('物体自身方向必须由锚点明确，不能用通用前缀掩盖手部歧义',()=>{const l=S.create();l.confirmed=true;l.anchors=[{id:'car',name:'汽车',x:50,y:50,radius:3,heading:0}];assert.equal(S.lint('以汽车自身正向为准，站在左侧',l).length,0);assert.ok(S.lint('以桌子自身正向为准，站在右侧',l).length);assert.ok(S.lint('以当前镜头画面为准，抬起右手',l).length);});
test('阻止无效标定与机位、检测跨障碍路径',()=>{const l=S.create();l.anchors=[{id:'a',name:'桌子',x:50,y:50,radius:5,blocked:true}];assert.deepEqual(S.obstacles(l,[{x:10,y:50},{x:90,y:50}]),['桌子']);l.axis={...l.origin};assert.ok(S.valid(l).length);assert.ok(S.cameraErrors(l,{x:50,y:50,tx:50,ty:50}).length);});
test('独立镜头提示词包含参照及标定，底图不以base64污染上下文',()=>{const l=S.create();l.confirmed=true;const p={assets:[{id:'room',kind:'scene',spatialLayout:l},{id:'a',name:'人物'}]},s={spatialSceneId:'room',spatialCamera:{x:50,y:90,tx:50,ty:50}},sh={stateIn:[{assetId:'a',x:30,y:50,left:'空',right:'空'}],stateOut:[]};const text=S.spatialText(p,s,sh);assert.match(text,/本镜方位约定/);assert.match(text,/画面左侧/);assert.match(text,/不得输出真实米数/);assert.ok(!('image' in S.info(p,s)));});

test('空间扩展进入上下文、独立交付及审核指纹',()=>{const C={hash:x=>String(x),context:()=>({text:'base',budget:20000,sources:[]}),audit:()=>[],promptText:()=>'',dependencyStamp:()=>'',compile:()=>({tasks:[{shot:1,prompt:'镜头任务'}]})};S.install(C);const l=S.create();l.confirmed=true;const p={assets:[{id:'room',kind:'scene',spatialLayout:l}],sequences:[]},s={spatialSceneId:'room'},g={shots:[{action:'以当前镜头画面为准，向左移动',stateIn:[],stateOut:[]}]};const before=C.dependencyStamp(p,s,g);assert.match(C.context(p,s,g).text,/本镜方位约定/);assert.match(C.compile(p,s,g).tasks[0].prompt,/场景锚定/);l.originName='门口';assert.notEqual(C.dependencyStamp(p,s,g),before);g.shots[0].action='向左移动';assert.throws(()=>C.compile(p,s,g),/参照/);assert.ok(C.audit(p,s,g).length);});
