const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const C=require('../src/performance'),location=require('../src/data-location'),rescue=require('../src/rescue');
async function dirs(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-upgrade-'));const base=path.join(root,'base'),target=path.join(root,'target');await fs.mkdir(base);await fs.mkdir(target);return {root,base,target};}
test('断开的磁盘恢复后同一实例可用，状态不永久缓存',async()=>{const {root,base,target}=await dirs(),m=location(base);await m.migrate(target);await fs.rename(target,path.join(root,'offline'));assert.ok((await m.info()).error);await fs.rename(path.join(root,'offline'),target);await m.ready();assert.equal((await m.info()).error,'');});
test('迁移中断后从已有校验文件恢复，源文件保留',async()=>{const {base,target}=await dirs();await fs.writeFile(path.join(base,'settings.json'),'one');await fs.writeFile(path.join(base,'knowledge.json'),'two');const m=location(base);await assert.rejects(m.migrate(target,()=>{throw Error('模拟中断');}),/模拟中断/);assert.equal(m.root(),base);assert.ok(await fs.stat(path.join(target,'.director-migration.json')));const result=await m.migrate(target);assert.equal(result.files,2);assert.equal(await fs.readFile(path.join(base,'settings.json'),'utf8'),'one');assert.ok((await m.info()).identity.libraryId);});
test('迁移源在中断后改变时拒绝错误恢复',async()=>{const {base,target}=await dirs();await fs.writeFile(path.join(base,'settings.json'),'one');const m=location(base);await assert.rejects(m.migrate(target,()=>{throw Error('stop');}));await fs.writeFile(path.join(base,'settings.json'),'changed');await assert.rejects(m.migrate(target),/已变化/);assert.equal(m.root(),base);});
test('救援不依赖资料库，保留文字、报告缺图并移除密钥字段',async()=>{const data=await rescue({name:'救援',script:'未保存原文',apiKey:'secret',assets:[{references:[{data:'director-media://image/'+'a'.repeat(64)+'.png'}]}]},path.join(os.tmpdir(),'missing-media'));assert.equal(data.project.script,'未保存原文');assert.equal(data.missingMedia.length,1);assert.equal(data.project.apiKey,undefined);assert.equal(data.project.assets[0].references[0].data,'');});
const actor=(id,presence='present')=>({assetId:id,presence,x:10,y:20,facing:'东',gaze:'门',left:'空',right:'空',pose:'站',attention:'呼吸',phase:'静候'});
test('空间不足在复制之前拦截，原目录和目标保持',async()=>{const {base,target}=await dirs();await fs.writeFile(path.join(base,'settings.json'),'source');const original=fs.statfs;try{fs.statfs=async()=>({bavail:0,bsize:4096});await assert.rejects(location(base).migrate(target),/空间不足/);assert.deepEqual(await fs.readdir(target),[]);assert.equal(await fs.readFile(path.join(base,'settings.json'),'utf8'),'source');}finally{fs.statfs=original;}});
function shotFixture(){const p=C.normalize({id:'p_case',script:'甲说你好。',assets:[{id:'a_one',kind:'character',name:'甲',status:'confirmed'},{id:'a_two',kind:'character',name:'乙',status:'confirmed'}]});const s={assetIds:['a_one','a_two']};const sh={duration:3,voice:'无人声',audio:[],stateIn:[actor('a_one'),actor('a_two')],stateOut:[actor('a_one'),actor('a_two')],actorReactions:[{assetId:'a_one',text:'呼吸'},{assetId:'a_two',text:'背影略微转头'}],presenceEvents:[]};return {p,s,g:{performanceSchema:2,shots:[sh]},sh};}
test('离场允许不填画内坐标，但保留道具与动作阶段',()=>{const a={assetId:'a_one',presence:'absent',left:'空',right:'空',phase:'门外等待'};assert.deepEqual(C.stateErrors([a],['a_one'],'开场'),[]);a.presence='present';assert.ok(C.stateErrors([a],['a_one'],'开场').length);});
test('进出画事件与背影反应逐人检查',()=>{const {p,s,g,sh}=shotFixture();assert.deepEqual(C.performanceIssues(p,s,g),[]);sh.actorReactions.pop();assert.ok(C.performanceIssues(p,s,g).some(e=>e.includes('a_two')));sh.stateOut[0].presence='absent';assert.ok(C.performanceIssues(p,s,g).some(e=>e.includes('进出画')));sh.presenceEvents=[{assetId:'a_one',from:'present',to:'absent',reason:'从门离开'}];assert.ok(!C.performanceIssues(p,s,g).some(e=>e.includes('进出画')));});
test('声音跨语言保留，时长、旁白、离场说话与重叠校验',()=>{const {p,s,g,sh}=shotFixture();sh.audio=[{type:'dialogue',speaker:'a_one',language:'日本語',text:'ありがとう',start:0,end:2,lipSync:true}];sh.voice=C.audioText(sh.audio);assert.deepEqual(C.performanceIssues(p,s,g),[]);assert.ok(C.audioText(sh.audio).includes('ありがとう'));sh.audio[0].end=4;assert.ok(C.performanceIssues(p,s,g).some(e=>e.includes('时间')));sh.audio[0].type='narration';assert.ok(C.performanceIssues(p,s,g).some(e=>e.includes('禁止旁白')));sh.audio[0].type='dialogue';sh.stateIn[0].presence=sh.stateOut[0].presence='absent';assert.ok(C.performanceIssues(p,s,g).some(e=>e.includes('离场人物')));});
test('长篇事实金标准：别名、跨章节关键事实、未来事实不进入固定事实',()=>{const script='第一章 阿岚（代号青鸟）把钥匙交给小周。\n'+'路上的雨始终没有停。\n'.repeat(18000)+'第二章 小周在旧站等候。\n第三章 阿岚才得知信封是空的。';const start=script.indexOf('第二章'),end=script.indexOf('第三章');const p=C.normalize({id:'p_long',script,analysis:'阿岚也叫青鸟。',maxContextChars:28000,assets:[{id:'a_zhou',kind:'character',name:'小周',aliases:[],status:'confirmed',design:'固定',continuity:'固定'}]});p.facts=[{id:'f_key',text:'钥匙由小周持有',status:'confirmed',critical:true,start:0,end:25,revealAt:0,revision:1},{id:'f_future',text:'信封是空的',status:'confirmed',critical:true,start:end,end:script.length,revealAt:end+1,revision:1}];const g={sourceText:script.slice(start,end),sourceStart:start,sourceEnd:end,factIds:[],stageStart:[],shots:[]},s={assetIds:['a_zhou'],segments:[g]};const ctx=C.context(p,s,g,[]);assert.ok(ctx.factIds.includes('f_key'));assert.ok(!ctx.factIds.includes('f_future'));assert.ok(ctx.sources.some(x=>x.ref==='f_key'));assert.ok(ctx.characters<=28000);});
