const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const create=require('../src/video-generation');
const input={projectId:'p_demo',sequenceId:'s_demo',segmentId:'g_demo',shotId:'sh_demo',shotIndex:0,prompt:'雨夜，一个人缓缓回头，镜头保持中景。',duration:5,ratio:'16:9',resolution:'720p',generateAudio:false};
function fixture(folder,fetchImpl){return create({root:()=>folder,read:async(file,fallback)=>fs.readFile(file,'utf8').then(JSON.parse,e=>e.code==='ENOENT'?fallback:Promise.reject(e)),write:async(file,value)=>{await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,JSON.stringify(value));},safeStorage:{isEncryptionAvailable:()=>true,encryptString:x=>Buffer.from(x),decryptString:x=>x.toString()},fetchImpl});}
test('Seedance task submits once, resumes polling and stores video without API key in job data',async()=>{const folder=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-video-'));let posts=0,gets=0;const mp4=Buffer.from([0,0,0,12,102,116,121,112,105,115,111,109]);const fetchImpl=async(url,options)=>{const u=String(url);if(options.method==='POST'){posts++;assert.equal(JSON.parse(options.body).model,'doubao-seedance-2-5-260628');return new Response(JSON.stringify({id:'task_123',status:'queued'}),{headers:{'content-type':'application/json'}});}if(u.endsWith('/task_123')){gets++;return new Response(JSON.stringify({status:gets===1?'running':'succeeded',content:{video_url:'https://media.example.com/output.mp4'}}),{headers:{'content-type':'application/json'}});}if(u==='https://media.example.com/output.mp4')return new Response(mp4,{headers:{'content-type':'video/mp4'}});throw Error('unexpected URL '+u);};const hub=fixture(folder,fetchImpl);await hub.saveConfig({model:'doubao-seedance-2-5-260628',apiKey:'private-secret'});const job=await hub.submit(input);assert.equal(job.status,'queued');assert.equal(posts,1);assert.equal((await hub.poll(job.id)).status,'running');const done=await hub.poll(job.id);assert.equal(done.status,'succeeded');assert.equal(done.file.bytes,mp4.length);assert.deepEqual(await fs.readFile(done.file.path),mp4);assert.equal(posts,1);assert.doesNotMatch(await fs.readFile(path.join(folder,'video-jobs.json'),'utf8'),/private-secret/);});
test('invalid time and non-public download URLs are rejected before unsafe reuse',async()=>{assert.throws(()=>create.validateInput({...input,duration:3}),/4–30/);const folder=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-video-'));let count=0;const hub=fixture(folder,async(_url,options)=>{if(options.method==='POST'){count++;return new Response(JSON.stringify({id:'task_2'}));}return new Response(JSON.stringify({status:'succeeded',content:{video_url:'https://127.0.0.1/video.mp4'}}));});await hub.saveConfig({model:'doubao-seedance-2-5-260628',apiKey:'key'});const job=await hub.submit(input),end=await hub.poll(job.id);assert.equal(end.status,'download_pending');assert.equal(count,1);assert.match(end.error,/公网 HTTPS/);});
test('interrupted submission becomes an explicit review state after restart',async()=>{const folder=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-video-'));await fs.writeFile(path.join(folder,'video-jobs.json'),JSON.stringify([{id:'video_test',projectId:'p_demo',status:'submitting'}]));const hub=fixture(folder,async()=>{throw Error('no network expected');});const jobs=await hub.list('p_demo');assert.equal(jobs[0].status,'submission_unknown');assert.match(jobs[0].error,/控制台核对/);assert.equal((await hub.poll('video_test')).status,'submission_unknown');});
test('explicit first-frame image is submitted but never persisted in task history',async()=>{const folder=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-video-')),image='data:image/png;base64,'+Buffer.from('tiny-image').toString('base64');let body;const hub=fixture(folder,async(_url,options)=>{body=JSON.parse(options.body);return new Response(JSON.stringify({id:'task_image'}));});await hub.saveConfig({model:'doubao-seedance-2-5-260628',apiKey:'key'});const job=await hub.submit({...input,referenceImage:image,referenceName:'角色定版图'});assert.equal(job.mode,'first_frame');assert.equal(body.content[1].role,'first_frame');assert.equal(body.content[1].image_url.url,image);assert.doesNotMatch(await fs.readFile(path.join(folder,'video-jobs.json'),'utf8'),/data:image/);await assert.rejects(hub.submit({...input,referenceImage:'file:///secret.png'}),/首帧参考图/);});
test('自由画布任务与逐镜任务身份分离',async()=>{const raw={projectId:'p_demo',canvasNodeId:'node_free',prompt:'水面倒影渐渐显出人影',duration:5,ratio:'16:9',resolution:'720p'};const value=create.validateInput(raw);assert.equal(value.canvasNodeId,'node_free');assert.equal(value.shotId,'');assert.throws(()=>create.validateInput({...raw,shotId:'sh_demo'}),/画布生成节点身份无效/);});
test('Seedance 2.0 family uses each model limits and submits the chosen ID',async()=>{const models=[['doubao-seedance-2-0-260128',true],['doubao-seedance-2-0-fast-260128',false],['doubao-seedance-2-0-mini-260615',false]];for(const [model,fullHD] of models){assert.equal(create.modelSpec(model).max,15);assert.throws(()=>create.validateInput({...input,duration:16},model),/4–15/);if(!fullHD)assert.throws(()=>create.validateInput({...input,resolution:'1080p'},model),/不支持 1080p/);else assert.equal(create.validateInput({...input,resolution:'1080p'},model).resolution,'1080p');const folder=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-video-'));let submitted;const hub=fixture(folder,async(_url,options)=>{submitted=JSON.parse(options.body);return new Response(JSON.stringify({id:'task_20'}));});await hub.saveConfig({model,apiKey:'key'});const job=await hub.submit({...input,duration:15});assert.equal(submitted.model,model);assert.equal(job.model,model);assert.equal((await hub.publicConfig()).model,model);}
 assert.equal(create.validateInput({...input,resolution:'4k'},'doubao-seedance-2-0-260128').resolution,'4k');
 assert.throws(()=>create.validateInput({...input,resolution:'4k'},'doubao-seedance-2-5-260628'),/不支持 4k/);
 assert.throws(()=>create.modelSpec('grok-imagine-video-1.5'),/Seedance/);
});
