const {_electron:electron}=require('playwright-core'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
(async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-workspace-')),env={...process.env,DIRECTOR_DATA_DIR:root,DIRECTOR_HEADLESS:'1'};delete env.ELECTRON_RUN_AS_NODE;const app=await electron.launch({executablePath:process.argv[2]?path.resolve(process.argv[2]):require('electron'),args:process.argv[2]?[]:[path.resolve('.')],env});const errors=[];try{const page=await app.firstWindow();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].showInactive());page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>typeof PRODUCT!=='undefined'&&PRODUCT.ready);await page.evaluate(()=>createSample());await page.evaluate(async()=>{await act('page',{page:'workbench'});await act('ws-view',{view:'board'});});assert.equal(await page.locator('.dw-shot').count(),2);await page.locator('[data-action="dw-view"][data-view="flow"]').click();assert.equal(await page.locator('.dw-flow .dw-shot').count(),2);await page.locator('[data-action="dw-direct"]').first().click();await page.locator('[data-dw-ref]').first().check();await page.locator('[data-action="dw-save-refs"]').click();assert.equal(await page.evaluate(()=>DW.rows(S.project)[0].sh.directorRefs.length),1);await page.locator('[data-action="close-modal"]').first().click();console.log('PASS 同源双视图与引用保存');
 await page.evaluate(()=>act('page',{page:'methods'}));assert.ok((await page.locator('#content').textContent()).includes('导演方法库'));await page.evaluate(async()=>{await act('page',{page:'workbench'});await act('ws-view',{view:'board'});});await page.locator('[data-action="dw-seam"]').nth(1).click();assert.ok((await page.locator('#modal-body').textContent()).includes('前镜终态'));await page.locator('[data-action="close-modal"]').first().click();console.log('PASS 方法库与接缝对照');
 await page.evaluate(()=>{window.ran=false;dwConfirmTask('模拟调用',()=>runJob('模拟调用',async()=>{window.ran=true;}));});await page.waitForFunction(()=>$('modal').open);assert.equal(await page.evaluate(()=>window.ran),false);await page.locator('[data-action="close-modal"]').first().click();assert.equal(await page.evaluate(()=>window.ran),false);await page.evaluate(()=>{dwConfirmTask('模拟调用',()=>runJob('模拟调用',async()=>{window.ran=true;}));});await page.locator('#modal-submit').click();await page.waitForFunction(()=>window.ran&&!S.job);console.log('PASS 调用确认与取消');
 await page.evaluate(()=>{const r=DW.rows(S.project)[0];r.sh.directorDraft={base:DW.stamp(S.project,r),patch:{frame:'新画面测试'},model:'mock'};dwReview(r);});await page.locator('#modal-submit').click();await page.waitForFunction(()=>!$('modal').open);assert.equal(await page.evaluate(()=>DW.rows(S.project)[0].sh.frame),'新画面测试');assert.equal(await page.evaluate(()=>DW.rows(S.project)[0].g.stale),true);console.log('PASS 局部修改审阅采用');
 await page.evaluate(()=>showStateEditor(DW.rows(S.project)[0].g,'0'));const oldX=await page.locator('#state-0-x').inputValue();await page.locator('#dw-stage circle').first().press('ArrowRight');assert.equal(Number(await page.locator('#state-0-x').inputValue()),Number(oldX)+1);await page.locator('[data-action="close-modal"]').first().click();assert.equal(await page.evaluate(()=>DW.rows(S.project)[0].sh.stateOut[0].x),Number(oldX));await page.evaluate(()=>showStateEditor(DW.rows(S.project)[0].g,'0'));await page.locator('#dw-stage circle').first().press('ArrowRight');await page.locator('#modal-submit').click();await page.waitForFunction(()=>!$('modal').open);assert.equal(await page.evaluate(()=>DW.rows(S.project)[0].sh.stateOut[0].x),Number(oldX)+1);console.log('PASS 二维站位调整、取消与保存');
 await page.evaluate(async()=>{await persist();});await page.reload();await page.waitForFunction(()=>S.project?.sequences?.length);assert.equal(await page.evaluate(()=>DW.rows(S.project)[0].sh.frame),'新画面测试');await page.evaluate(()=>act('page',{page:'workbench'}));assert.deepEqual(errors,[]);await fs.mkdir('audit-evidence/upgrade-050',{recursive:true});await page.screenshot({path:'audit-evidence/upgrade-050/workspace.png',fullPage:false});await fs.writeFile('audit-evidence/upgrade-050/desktop-result.json',JSON.stringify({passed:true,errors,checks:['双视图','引用持久化','方法库','接缝','任务确认与取消','草稿采用','二维站位保存与取消','重启恢复']}));console.log('PASS 保存重启及页面无异常');}finally{await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await app.close().catch(()=>{});}})().catch(e=>{console.error(e);process.exitCode=1;});


