const inputHtml=(id,label,value='',type='text')=>`<label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`;
const ACTION_REGISTRY=new Map();
function registerAction(name,handler){if(!/^[a-z][a-z0-9-]*$/.test(name)||typeof handler!=='function'||ACTION_REGISTRY.has(name))throw Error('动作注册无效或重复：'+name);ACTION_REGISTRY.set(name,handler);}
function dirtySequence(s){for(const g of s.segments){g.stale=Boolean(g.shots.length||g.prompt);g.reviewed=false;}}
function checkOutput(s,g){const errors=C.validate(s,g);if(!g.reviewed||!g.shots.length||errors.length)throw Error('请先完成分镜并人工审核：'+errors.join('；'));}
async function act(action,d={}){if(S.job&&!['cancel-job','page','help','context','close-modal','canvas-desk-queue','canvas-desk-messages','hub-queue','hub-messages','hub-help','hub-close','hub-filter','hub-read','hub-open-task','hub-open-notice','hub-refresh'].includes(action))throw Error('任务运行期间请先停止任务再修改项目');if(ACTION_REGISTRY.has(action))return ACTION_REGISTRY.get(action)(d);const p=S.project,a=selectedAsset(),s=selectedSequence(),g=segmentBy(d.id);
switch(action){
case 'close-modal':closeModal();return;
case 'page':S.page=d.page;render();return;
case 'new-project':NEW_PROJECT.imported=null;showModal('创建导演项目',`${inputHtml('new-name','项目名称')}<label>从哪里开始<select id="new-mode"><option value="script">已有剧本或故事想法 · 先整理原文</option><option value="subtitle">已有 SRT 字幕 · 保留时间码导入</option><option value="canvas">空白画布 · 自由探索</option></select></label><div class="new-project-source"><div><strong>已有文字文件？</strong><p>可选 TXT、Markdown、Word、文字型 PDF 或 SRT。先预览再创建，不会改动其他项目。</p></div>${btn('选择文件','new-project-import')}</div><p id="new-project-file" class="muted" role="status">未选择文件。创建后也可以在剧本页导入或直接输入。</p>`,async()=>{const name=$('new-name').value.trim(),mode=$('new-mode').value;if(!name)throw Error('请输入项目名称');if(mode==='subtitle'&&!NEW_PROJECT.imported)throw Error('请先选择 SRT 字幕文件');if(mode==='subtitle'&&!/\.srt$/i.test(NEW_PROJECT.imported.name))throw Error('字幕模式请选择 SRT 文件，其他文字请使用剧本模式');await persist();const x=C.normalize(await call('projects:create',name));x.entryMode=mode;if(NEW_PROJECT.imported){x.script=NEW_PROJECT.imported.text;x.scriptSource=NEW_PROJECT.imported.name;markScriptChanged(x);}S.projects.unshift(x);S.project=x;S.page=mode==='canvas'?'canvas':'home';NEW_PROJECT.imported=null;await persist();render();},true,'创建并进入');return;
case 'select-project':await selectProject(d.id);return;
case 'backup':await persist();await call('projects:backup',C.clone(p));return;
case 'restore-project':{await persist();const x=await call('projects:restore');if(x){S.projects.unshift(x);S.project=x;render();}return;}
case 'archive':return act('hub-delete-project',{id:p.id});
case 'data-folder':await call('files:openData');return;
case 'import-script':{const r=await call('files:script');if(r){const apply=()=>{p.script=r.text;p.scriptSource=r.name;markScriptChanged(p);saveSoon();render();};if(p.script)confirmAction('替换剧本','将替换当前原文，现有分析与分镜需要更新。建议先做项目备份。',apply);else apply();}return;}
case 'analyze':await analyzeProject();return;
case 'extract-assets':await extractAssets();return;
case 'filter-assets':S.filter=d.id;render();return;
case 'select-asset':S.assetId=d.id;render();return;
case 'new-asset':showModal('新增资产',inputHtml('asset-name','名称')+`<label>类别<select id="asset-kind">${opts(labels,'character')}</select></label>`,()=>{if(!$('asset-name').value.trim())throw Error('请输入名称');const x={id:C.id('a'),kind:$('asset-kind').value,name:$('asset-name').value.trim(),basis:'',design:'',continuity:'',references:[],versions:[],revision:1,status:'draft',aliases:[],variants:'',sourceRevision:p.scriptRevision,sourceReview:false};p.assets.push(x);S.assetId=x.id;saveSoon();render();});return;
case 'confirm-asset':if(a.status==='confirmed'){snapshotAsset(a);a.status='draft';a.revision++;C.invalidateAssets(p,a.id);}else{if(!a.name.trim()||!a.design.trim()||!a.continuity.trim())throw Error('请补全名称、设计和连续性');a.status='confirmed';snapshotAsset(a);}break;
case 'delete-asset':confirmAction('删除资产','引用此资产的分镜将需要重新审核。',()=>{C.invalidateAssets(p,a.id);p.sequences.forEach(s=>s.assetIds=s.assetIds.filter(id=>id!==a.id));p.assets=p.assets.filter(x=>x!==a);S.assetId=null;saveSoon();render();});return;
case 'add-ref':if(a.status==='confirmed')throw Error('请先解锁资产');{const images=await call('files:image');a.references.push(...images);C.invalidateAssets(p,a.id);}break;
case 'remove-ref':if(a.status==='confirmed')throw Error('请先解锁资产');a.references.splice(Number(d.index),1);C.invalidateAssets(p,a.id);break;
case 'describe-ref':if(a.status==='confirmed')throw Error('请先解锁资产');if(!a.references.length)throw Error('请先添加参考图');await runJob('参考图分析',async()=>{snapshotAsset(a);a.design=await ask(DIRECTOR,`请描述参考图可见的${labels[a.kind]}视觉特征，生成稳定设计提示词。不要猜测不可见部分。现有依据：${a.basis}`,a.references.map(r=>r.data));C.invalidateAssets(p,a.id);});return;
case 'asset-history':showModal('资产版本',a.versions.map((v,i)=>`<section class="card">${esc(v.at)}<pre class="source">${esc(v.design)}</pre>${btn('恢复为草稿','restore-asset',`data-index="${i}"`)}</section>`).join('')||'暂无历史版本',null,true);return;
case 'restore-asset':{const v=C.clone(a.versions[Number(d.index)]);snapshotAsset(a);Object.assign(a,{name:v.name,basis:v.basis,design:v.design,continuity:v.continuity,references:v.references||[],aliases:v.aliases||[],variants:v.variants||'',sourceReview:true,status:'draft',revision:a.revision+1});C.invalidateAssets(p,a.id);closeModal();}break;
case 'plan-sequences':await planSequences();return;
case 'new-sequence':showModal('新建连续段落组',inputHtml('seq-name','名称，例如：第一集 · 办公室对峙'),()=>{const title=$('seq-name').value.trim();if(!title)throw Error('请输入名称');const x={id:C.id('s'),title,episode:'',scene:'',event:'',template:'director',assetIds:[],segments:[]};p.sequences.push(x);S.seqId=x.id;saveSoon();render();});return;
case 'select-sequence':S.seqId=d.id;render();return;
case 'delete-sequence':confirmAction('删除段落组','此组所有分镜也将移除，请先备份需要保留的内容。',()=>{p.sequences=p.sequences.filter(x=>x!==s);S.seqId=null;saveSoon();render();});return;
case 'add-segment':s.segments.push({id:C.id('g'),duration:30,sourceText:'',startState:s.segments.at(-1)?.endState||'',endState:'',stageStart:C.clone(s.segments.at(-1)?.stageEnd||[]),stageEnd:[],factIds:[],shots:[],history:[],prompt:'',reviewed:false,stale:false,stateSchema:1});break;
case 'delete-segment':confirmAction('删除片段','后续片段需要重新审核。',()=>{const i=s.segments.indexOf(g);s.segments.splice(i,1);if(s.segments[i]&&i===0)s.segments[i].startState='';C.invalidateAfter(s,i-1,'前序片段删除');saveSoon();render();});return;
case 'generate-segment':await generateSegment(d.id);return;
case 'qa':await reviewByModel(d.id);return;
case 'context':{const ctx=C.context(p,s,g,S.knowledge);showModal(`本次上下文 · ${ctx.characters}/${ctx.budget} 字符`,`<pre class="source">${esc(ctx.text)}</pre><p>引用：${esc(ctx.sources.map(x=>x.label).join('；'))}</p>`,null,true);return;}
case 'review':{const candidate={...g,stale:false};const seq={...s,segments:s.segments.map(x=>x===g?candidate:x)};const problems=C.validate(seq,candidate);if(!g.shots.length)problems.push('没有镜头');if(p.analysisDirty)problems.push('故事记忆已过期');if(s.assetIds.some(id=>p.assets.find(a=>a.id===id)?.status!=='confirmed'))problems.push('资产未确认');const i=s.segments.indexOf(g);if(i>0&&(!s.segments[i-1].reviewed||s.segments[i-1].stale))problems.push('上一段未审核');if(problems.length)throw Error(problems.join('；'));confirmAction('确认本片段','请确认已逐镜检查原文、人物反应、站位、手部、道具与首尾状态。确认后允许导出，并作为下一段依据。',()=>{g.stale=false;g.reviewed=true;g.prompt=C.promptText(s,g,p);saveSoon();render();});return;}
case 'add-shot':snapshotSegment(g);g.shots.push({duration:3,...Object.fromEntries(Object.keys(C.shotFields).map(k=>[k,'']))});g.reviewed=false;break;
case 'delete-shot':snapshotSegment(g);g.shots.splice(Number(d.index),1);g.reviewed=false;break;
case 'move-shot':{const i=Number(d.index);if(i>0){snapshotSegment(g);[g.shots[i-1],g.shots[i]]=[g.shots[i],g.shots[i-1]];g.reviewed=false;}}break;
case 'segment-history':showModal('分镜历史',g.history.map((v,i)=>`<section class="card">${esc(v.at)}<pre class="source">${esc(C.promptText(s,v.value,p))}</pre>${btn('恢复为待审核','restore-segment',`data-id="${g.id}" data-index="${i}"`)}</section>`).join('')||'暂无历史版本',null,true);return;
case 'restore-segment':{const v=C.clone(g.history[Number(d.index)].value);snapshotSegment(g);Object.assign(g,v,{history:g.history,reviewed:false,stale:true});C.invalidateAfter(s,s.segments.indexOf(g),'前一片段恢复版本');closeModal();}break;
case 'copy-prompt':case 'export-prompt':{const seq=p.sequences.find(x=>x.id===d.seq),seg=seq.segments.find(x=>x.id===d.id);checkOutput(seq,seg);const text=C.promptText(seq,seg,p);if(action==='copy-prompt'){await call('clipboard:copy',text);toast('已复制');}else await call('files:export',{name:seq.title,format:'txt',text});return;}
case 'export-all':{const list=p.sequences.flatMap(seq=>seq.segments.filter(g=>g.reviewed&&!g.stale).map(g=>{checkOutput(seq,g);return {sequence:seq.title,episode:seq.episode,...g,prompt:C.promptText(seq,g,p)};}));if(!list.length)throw Error('没有通过审核的分镜');let text=list.map(g=>g.prompt).join('\n\n---\n\n');if(d.format==='json')text=JSON.stringify({project:p.name,segments:list},null,2);if(d.format==='csv'){const quote=v=>'"'+String(v??'').replace(/"/g,'""')+'"';text='\ufeff'+[['段落组','集次','片段','镜头','时长',...Object.values(C.shotFields),'方位约定与空间依据'],...list.flatMap((g,i)=>g.shots.map((shot,j)=>[g.sequence,g.episode,i+1,j+1,shot.duration,...Object.keys(C.shotFields).map(k=>shot[k]),typeof Spatial!=='undefined'?Spatial.spatialText(p,p.sequences.find(s=>s.segments.some(x=>x.id===g.id)),shot):'']))].map(row=>row.map(quote).join(',')).join('\r\n');}await call('files:export',{name:p.name+'-分镜',format:d.format,text});return;}
case 'import-knowledge':case 'import-folder':{const r=await call('knowledge:import',action==='import-folder'?'folder':'files');S.knowledge=await call('knowledge:list');toast(`导入 ${r.added.length} 项，跳过 ${r.skipped.length} 项${r.skipped.length?'：'+r.skipped.slice(0,3).map(x=>typeof x==='string'?x:JSON.stringify(x)).join('；'):''}`);render();return;}
case 'knowledge-detail':{const k=S.knowledge.find(x=>x.id===d.id);showModal('资料全文与用途',inputHtml('k-name','名称',k.name)+inputHtml('k-version','版本',k.version)+`<label>用途<select id="k-kind">${opts({core:'导演原则',preset:'特定规格',reference:'学习参考'},k.kind)}</select></label><label>适用阶段（英文逗号分隔：analysis,assets,shots）<input id="k-stages" value="${esc(k.stages?.join(',')||'')}"></label><p>${esc(k.source)}</p><pre class="source">${esc(k.text)}</pre>`,k.builtin?null:async()=>{await call('knowledge:save',{...k,name:$('k-name').value,version:$('k-version').value,kind:$('k-kind').value,stages:$('k-stages').value.split(',').map(x=>x.trim()).filter(x=>['analysis','assets','shots'].includes(x))});S.knowledge=await call('knowledge:list');if(p){p.knowledgeRevision=(p.knowledgeRevision||0)+1;C.touch(p,'资料配置变化');p.analysisDirty=Boolean(p.analysis);saveSoon();}render();},true);return;}
case 'delete-knowledge':confirmAction('移除资料','内置资料不会受影响。',async()=>{await call('knowledge:remove',d.id);S.knowledge=await call('knowledge:list');if(p){p.knowledgeRevision=(p.knowledgeRevision||0)+1;C.touch(p,'资料配置变化');p.analysisDirty=Boolean(p.analysis);saveSoon();}render();});return;
case 'settings':{const v=S.settings;showModal('模型连接',`<p>支持云端和本机 OpenAI 兼容接口（如 Ollama）。云端需要你自己的 API 密钥；本机需要先启动模型服务。</p><label>运行方式<select id="set-provider">${opts({cloud:'云端（默认）',local:'本机服务'},v.provider)}</select></label>`+inputHtml('set-base','云端接口地址',v.baseUrl||'https://dashscope.aliyuncs.com/compatible-mode/v1')+inputHtml('set-local','本机接口地址',v.localUrl||'http://localhost:11434/v1')+inputHtml('set-model','模型名称',v.model||'qwen-plus')+inputHtml('set-key',v.hasKey?'API 密钥（已保存，留空保留）':'API 密钥','','password')+`<label class="check"><input id="clear-key" type="checkbox">清除已保存密钥</label><p>保存后可读取模型列表。上下文预算按字符计算，需要根据服务商实际限制设置。</p>${btn('读取已保存连接的模型列表','models')}`,async()=>{await call('settings:save',{provider:$('set-provider').value,baseUrl:$('set-base').value.trim(),localUrl:$('set-local').value.trim(),model:$('set-model').value.trim(),apiKey:$('set-key').value.trim(),clearKey:$('clear-key').checked});S.settings=await call('settings:get');render();});return;}
case 'models':{const list=await call('model:models');toast('可用模型：'+list.join('、'));return;}
case 'cancel-job':if(S.job){S.job.cancelled=true;if(S.job.requestId)await call('model:cancel',S.job.requestId);}return;
case 'help':showModal('使用指南','<ol><li>配置模型接口和密钥。</li><li>导入完整剧本，建立故事记忆。</li><li>提取资产，补全设计与参考图后确认。</li><li>新建连续段落组，勾选资产，填入本段原文与开场状态。</li><li>生成镜头，核对后人工确认。下一段自动继承结束状态。</li><li>在提示词输出复制或导出。</li></ol><p>项目自动保存到本机。建议定期备份。长篇通过原文分块、摘要和检索管理上下文；无法保证每次召回所有细节。资料仅用于当前项目检索，不会训练或修改大模型。此程序生成提示词，不包含视频渲染和本地模型权重。</p>',null,true);return;
default:return;
}if(g&&['add-shot','delete-shot','move-shot'].includes(action))C.invalidateAfter(s,s.segments.indexOf(g),'前序镜头已修改');saveSoon();render();}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;e.preventDefault();if(el.getAttribute('aria-busy')==='true')return;let busy=false;const timer=setTimeout(()=>{if(el.isConnected){el.setAttribute('aria-busy','true');busy=true;}},120);act(el.dataset.action,el.dataset).catch(showError).finally(()=>{clearTimeout(timer);if(busy)el.removeAttribute('aria-busy');});});


$('modal-form').addEventListener('submit',async e=>{e.preventDefault();if(!S.modalSubmit)return;const submit=S.modalSubmit,button=$('modal-submit');button.disabled=true;button.setAttribute('aria-busy','true');try{await submit();closeModal();}catch(error){presentModalError(error);}finally{button.disabled=false;button.removeAttribute('aria-busy');}});
document.addEventListener('submit',e=>{if(e.target.id==='memory-search'){e.preventDefault();S.memoryQuery=new FormData(e.target).get('query');render();}});
document.addEventListener('input',e=>{const el=e.target;if(!el.dataset.bind||S.job)return;const path=el.dataset.bind.split('.'),p=S.project;let object,key=path.at(-1);if(path[0]==='project')object=p;if(path[0]==='asset'){object=selectedAsset();if(object.status==='confirmed')return;C.invalidateAssets(p,object.id);}if(path[0]==='seq'){object=selectedSequence();dirtySequence(object);}if(path[0]==='seg'){object=segmentBy(path[1]);object.reviewed=false;C.invalidateAfter(selectedSequence(),selectedSequence().segments.indexOf(object),'前序片段状态变化');}if(path[0]==='shot'){const g=segmentBy(path[1]);object=g.shots[Number(path[2])];g.reviewed=false;C.invalidateAfter(selectedSequence(),selectedSequence().segments.indexOf(g),'前序镜头已修改');}if(!object)return;object[key]=el.type==='number'?Number(el.value):el.value;if(path[0]==='shot'&&key==='voice'&&object.audio){delete object.audio;}if(path[0]==='shot'&&key==='reactions'&&object.actorReactions){delete object.actorReactions;}if(path[0]==='project'&&key==='script')markScriptChanged(p);else if(path[0]==='project'&&key!=='name'&&key!=='maxContextChars'){if(key!=='analysis')p.analysisDirty=Boolean(p.analysis);p.sequences.forEach(dirtySequence);}if(path[0]==='seg'&&key==='endState')C.invalidateAfter(selectedSequence(),selectedSequence().segments.indexOf(object),'前序结束状态变化');saveSoon();});
document.addEventListener('change',e=>{if(S.job)return;const el=e.target;if(el.dataset.asset){const s=selectedSequence();s.assetIds=el.checked?[...new Set([...s.assetIds,el.dataset.asset])]:s.assetIds.filter(id=>id!==el.dataset.asset);dirtySequence(s);saveSoon();}if(el.dataset.knowledge){S.project.knowledgeOverrides[el.dataset.knowledge]=el.checked;S.project.analysisDirty=Boolean(S.project.analysis);S.project.sequences.forEach(dirtySequence);saveSoon();}if(el.tagName==='SELECT'&&el.dataset.bind)render();});
desk.onClosing(async()=>{try{if(S.job){toast('请先停止任务，再关闭程序，以保留完整检查点');return;}await persist();await call('app:close');}catch(e){if(e.diagnosisDraft){showModal('短片诊断尚未保存','<p>'+esc(e.message)+'</p><p>当前诊断文字仍留在本次运行内存中。请修复资料位置并重试保存，或先导出可阅读的应急草稿；不要直接结束进程。</p><div class="toolbar">'+btn('导出诊断应急草稿','diagnosis-rescue')+btn('检查资料位置','data-folder')+'</div>',null,true);return;}showModal('关闭前保存未完成','<p>'+esc(e.message)+'</p><p>可恢复磁盘后重试，或把当前内存内容救援导出到可用位置。导出成功后才会关闭。</p><div class="toolbar">'+btn('检查资料位置','data-folder')+btn('救援导出并关闭','rescue-and-close')+'</div>',null,true);}});

