(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.GuanlanAssistantCore=api;})(globalThis,()=>{
 const PAGES={home:'剧本',assets:'视觉资产',shots:'连续分镜',workbench:'镜头工作区',review:'审稿与验证',delivery:'冻结交付',prompts:'提示词输出',tools:'AI 实验室',film:'拉片学习',diagnosis:'短片诊断',knowledge:'导演知识库',facts:'事实台账',rules:'导演规则',history:'任务记录',usage:'Token 用量'};
 const GUIDE_WORDS={tools:['AI实验室','AI 实验室','工具箱','技能','skill','添加文件','上传文件'],start:['入门','第一次','开始使用'],model:['模型','连接','密钥','api','接口'],script:['剧本','原文','导入剧本'], 'script-planner':['写剧本','剧本草稿','故事想法'],assets:['资产','资产库','角色','场景','道具'],planning:['分镜','规划','镜头表'],directing:['镜头工作区','精修','连续性'], 'spatial-090':['空间','站位','坐标','原点'], 'film-study':['拉片','拆镜','看片'], 'study-library':['五期','资料库','每日一镜'], 'short-film-diagnosis':['短片诊断','成片诊断'], 'film-delivery-080':['拉片报告','excel','表格导出'],export:['交付','冻结','提示词'],storage:['保存','备份','资料位置'],personal:['外观','皮肤','个人中心'],usage:['token','用量'],trouble:['报错','打不开','故障']};
 function guideMatches(question,chapters){const q=String(question||'').trim().toLowerCase();return chapters.map(c=>{let score=0;for(const word of GUIDE_WORDS[c.id]||[])if(q.includes(word))score+=word.length+3;if(q.includes(c.title.toLowerCase()))score+=20;for(const part of q.split(/[\s，。？?、：:；;]+/).filter(x=>x.length>=2))if(c.title.toLowerCase().includes(part))score+=part.length;return {chapter:c,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,4).map(x=>x.chapter);}
 function projectStatus(p){if(!p)return '当前没有选中项目。可以告诉我“创建项目《名称》”，或先体验原创示例。';const assets=p.assets||[],seq=p.sequences||[],segments=seq.flatMap(s=>s.segments||[]),approved=segments.filter(g=>g.reviewed&&!g.stale),stale=segments.filter(g=>g.stale),confirmed=assets.filter(a=>a.status==='confirmed'&&!a.sourceReview);let next='';if(!String(p.script||'').trim())next='先补齐剧本原文或从想法写独立草稿。';else if(!p.analysis||p.analysisDirty)next='接下来核对或更新故事记忆。';else if(!assets.length||confirmed.length<assets.length)next='接下来核对并确认需要使用的视觉资产。';else if(!segments.length)next='接下来在连续分镜里规划第一段。';else if(approved.length<segments.length)next='接下来逐镜检查待审核片段，确认连续性。';else next='已审片段可前往冻结交付。';return `《${p.name}》：剧本${String(p.script||'').trim()?'已录入':'未录入'}；资产 ${confirmed.length}/${assets.length} 项已确认；片段 ${approved.length}/${segments.length} 个已审核${stale.length?`，${stale.length} 个待复核`:''}。\n${next}`;}
 function nextSteps(p){if(!p)return [{label:'新建项目',prompt:'创建项目《我的短片》',reason:'先建立创作空间'},{label:'打开拉片学习',prompt:'打开拉片学习',reason:'从已有短片学习镜头'}];const assets=p.assets||[],segments=(p.sequences||[]).flatMap(s=>s.segments||[]),confirmed=assets.filter(a=>a.status==='confirmed'&&!a.sourceReview),approved=segments.filter(g=>g.reviewed&&!g.stale);if(!String(p.script||'').trim())return [{label:'写剧本草稿',prompt:'写剧本草稿',reason:'先明确故事，再规划镜头'},{label:'查看剧本页',prompt:'打开剧本',reason:'也可直接录入已有剧本'}];if(!p.analysis||p.analysisDirty)return [{label:'核对故事记忆',prompt:'打开剧本',reason:'剧本改变后先核对故事信息'},{label:'查看资产',prompt:'打开视觉资产',reason:'准备角色、场景和道具'}];if(!assets.length||confirmed.length<assets.length)return [{label:'核对视觉资产',prompt:'打开视觉资产',reason:`已确认 ${confirmed.length}/${assets.length} 项`},{label:'规划分镜',prompt:'打开连续分镜',reason:'资产可在后续继续补充'}];if(!segments.length)return [{label:'规划分镜',prompt:'打开连续分镜',reason:'把剧本拆成可执行镜头'}];if(approved.length<segments.length)return [{label:'检查镜头',prompt:'打开镜头工作区',reason:`已审核 ${approved.length}/${segments.length} 个片段`},{label:'查看分镜',prompt:'打开连续分镜',reason:'先检查镜头顺序与衔接'}];return [{label:'冻结交付',prompt:'打开冻结交付',reason:'核对后输出制作资料'},{label:'查看提示词',prompt:'打开提示词输出',reason:'逐镜检查生成提示词'}];}
 function local(question,context,chapters){const q=String(question||'').trim(),result={reply:'',actions:[],handled:false};if(!q)return result;
  const parts=q.split(/(?:并且|然后|再|，|,)/).map(x=>x.trim()).filter(Boolean);if(parts.length>1&&parts.length<=4){const plans=parts.map(part=>local(part,context,chapters));if(plans.every(p=>p.handled&&p.actions.length&&!p.actions.some(a=>a.offer))){result.actions=plans.flatMap(p=>p.actions);result.handled=true;return result;}}
  const create=/^(?:帮我|请|现在)?\s*(?:创建|新建|建立|建)(?:一个|个)?(?:导演)?项目(?:叫|名为|名称是|：|:|《|\s)+[《“"]?([^》”"，。]+)[》”"]?$/.exec(q);if(create){result.actions=[{type:'create_project',name:create[1].trim()}];result.handled=true;return result;}
  const asset=/(?:添加|新增|创建|新建)(?:一个|个)?(人物|角色|场景|道具)(?:叫|名为|：|:|《|\s)+[《“"]?([^》”"，。]+)[》”"]?/.exec(q);if(asset){result.actions=[{type:'add_asset',kind:asset[1]==='人物'?'character':asset[1]==='角色'?'character':asset[1]==='场景'?'scene':'prop',name:asset[2].trim()}];result.handled=true;return result;}
  if(/(?:检查|查看|分析|告诉我).*(?:项目进度|项目状态|下一步|卡在哪)|^(?:项目进度|项目状态|下一步)/.test(q)){result.reply=projectStatus(context.project);result.handled=true;return result;}
  if(/(?:导出|保存).*(?:拉片|excel|表格)/i.test(q)&&!/怎么|如何|怎样/.test(q)){result.actions=[{type:'export_film_xlsx'}];result.handled=true;return result;}
  if(/(?:继续|恢复).*(?:AI|智能)?.*拉片/.test(q)&&!/怎么|如何|怎样/.test(q)){result.actions=[{type:'resume_film_analysis'}];result.handled=true;return result;}
  if(/(?:一键|自动).*(?:AI|智能)?.*拉片/.test(q)&&/(?:开始|进行|帮我|给我|做|分析|一键|自动)/.test(q)&&!/怎么|如何|怎样/.test(q)){result.actions=[{type:'auto_film_analysis'}];result.handled=true;return result;}
  if(/(?:打开|进入|带我去|切换到|跳转到|前往)/.test(q)&&!/怎么|如何|怎样/.test(q)){if(/模型中心|模型设置|连接模型/.test(q)){result.actions=[{type:'open_model'}];result.handled=true;return result;}if(/五期|资料库/.test(q)&&/拉片|资料/.test(q)){result.actions=[{type:'open_study_library'}];result.handled=true;return result;}if(/使用指南|帮助/.test(q)){result.actions=[{type:'guide',chapter:'start'}];result.handled=true;return result;}const page=Object.entries(PAGES).sort((a,b)=>b[1].length-a[1].length).find(([,name])=>q.includes(name));if(page){result.actions=[{type:'navigate',page:page[0]}];result.handled=true;return result;}}
  if(/(?:写|生成|起草).*(?:剧本|脚本)/.test(q)&&!/怎么|如何|怎样/.test(q)){const idea=/(?:关于|讲述)(.+?)的(?:短片)?(?:剧本|脚本)/.exec(q)?.[1]||/(?:剧本|脚本)[：:\s]+(.+)/.exec(q)?.[1];result.actions=idea?.trim()?[{type:'draft_script',idea:idea.trim().slice(0,1200)}]:[{type:'open_script_planner'}];result.handled=true;return result;}
  if(/(?:这个页面|当前页面|这里).*(?:怎么|如何|怎样)|(?:怎么|如何|怎样).*(?:这个页面|当前页面|这里)/.test(q)){const pageGuide={home:'script',assets:'assets',shots:'planning',workbench:'directing',tools:'tools',film:'film-study',diagnosis:'short-film-diagnosis',review:'export',delivery:'export',prompts:'export',knowledge:'knowledge',usage:'usage'},c=chapters.find(x=>x.id===(pageGuide[context.page]||'start'));if(c){result.reply=`${c.title}\n${c.steps.slice(0,3).map(([title,step],i)=>`${i+1}. ${title}：${step}`).join('\n')}\n完成后：${c.result}`;result.actions=[{type:'guide',chapter:c.id,offer:true}];result.handled=true;return result;}}
  if(/(?:怎么|如何|怎样|哪里|在哪|什么是|流程|指南|步骤|不会用|看不懂)/.test(q)){const matches=guideMatches(q,chapters);if(matches.length){const c=matches[0];result.reply=`${c.title}\n${c.steps.slice(0,3).map(([title,step],i)=>`${i+1}. ${title}：${step}`).join('\n')}\n完成后：${c.result}`;result.actions=[{type:'guide',chapter:c.id,offer:true}];result.handled=true;return result;}}
  return result;
 }
 const TYPES=new Set(['navigate','guide','open_model','open_study_library','open_script_planner','draft_script','create_project','add_asset','export_film_xlsx','auto_film_analysis','resume_film_analysis','project_status']);
 function validatePlan(value,question,chapters){if(!value||typeof value!=='object')throw Error('助手返回格式无效');const reply=String(value.reply||'').slice(0,5000),raw=Array.isArray(value.actions)?value.actions:[],actions=[];if(raw.length>4)throw Error('单次任务步骤过多，请拆成小任务');const q=String(question||''),askingHow=/(怎么|如何|怎样)/.test(q);for(const item of raw){if(!item||!TYPES.has(item.type))throw Error('助手提出了不支持的操作');const a={type:item.type};if(item.type==='navigate'){if(!Object.hasOwn(PAGES,item.page))throw Error('目标页面无效');a.page=item.page;}if(item.type==='guide'){if(!chapters.some(c=>c.id===item.chapter))throw Error('指南章节无效');a.chapter=item.chapter;a.offer=!!item.offer;}if(item.type==='create_project'){if(askingHow||!/(?:创建|新建|建立|建).{0,8}项目/.test(q))throw Error('用户没有要求新建项目');a.name=String(item.name||'').trim().slice(0,80);if(!a.name)throw Error('项目名称不能为空');}if(item.type==='add_asset'){if(askingHow||!/(?:添加|新增|创建|新建).{0,8}(?:角色|人物|场景|道具|资产)/.test(q))throw Error('用户没有要求新增资产');if(!['character','scene','prop'].includes(item.kind))throw Error('资产类别无效');a.kind=item.kind;a.name=String(item.name||'').trim().slice(0,80);if(!a.name)throw Error('资产名称不能为空');}if(item.type==='draft_script'){if(askingHow||!/(?:写|生成|起草).*(?:剧本|脚本)/.test(q))throw Error('用户没有要求撰写剧本');a.idea=String(item.idea||'').trim().slice(0,1200);if(!a.idea)throw Error('请提供故事想法');}if(item.type==='export_film_xlsx'&&(askingHow||!/(?:导出|保存).*(?:拉片|excel|表格)/i.test(q)))throw Error('用户没有要求导出拉片表');if(['auto_film_analysis','resume_film_analysis'].includes(item.type)&&(askingHow||!/(?:一键|自动|继续|恢复).*(?:拉片)/.test(q)))throw Error('用户没有要求启动 AI 拉片');actions.push(a);}return {reply,actions};}
 return {PAGES,guideMatches,projectStatus,nextSteps,local,validatePlan};
});
