(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./domain'));else factory(root.DirectorCore);})(globalThis,C=>{
const old={normalize:C.normalize,context:C.context,audit:C.audit,promptText:C.promptText,compile:C.compile,dependencyStamp:C.dependencyStamp};
const narrativeModes={drama:'剧情演绎 · 无旁白',narration:'旁白驱动 · 推文 / 解说',mixed:'混合叙事 · 旁白与对白',silent:'无语言叙事 · 动作与环境音'};
function mode(p){return narrativeModes[p.narrativeMode]?p.narrativeMode:'drama';}
function languageGuide(p){return (p.languagePolicy==='translate'?`语言处理：用户主动要求翻译为「${p.voiceLanguage}」，保持人物身份、原意和信息顺序。`:'语言处理：逐句跟随剧本原有语言；中文、英文及其他语言使用相同制作流程。多语剧本保留每句对白或旁白的语言及原有切换，不擅自统一语言、不默认转英文、不根据国内海外标签推断语言。')+'分镜字段说明可用中文，但台词、旁白与剧情内文字遵守上述语言策略。无语言叙事不产生人声，原文语言仍用于理解剧情。语速须按具体语言、演员和情绪校准，禁止套用固定英语词速或中文字符速度。';}
function narrativeGuide(p){const m=mode(p);return `叙事声音模式：${narrativeModes[m]}。${languageGuide(p)}\n`+({drama:'不生成解说旁白或回顾式讲述。通过人物行动、对白、视线、反应和环境音传达剧情。原文叙述是画面依据，不直接念出来；无法视觉化的信息列为待确认，不擅自补对白，不自动把旁白改成内心独白。',narration:'旁白是叙事主线，按旁白语义与自然停顿安排画面。镜头可以保留无旁白的呼吸段，不机械要求每镜有人声。旁白不对应画内人物口型；需要角色对白时单独标注说话者与口型，避免与旁白重叠。不得为了画面长度任意删改旁白。',mixed:'根据原文明确区分旁白和角色对白，标记声音来源、说话者与时间。避免旁白重复解释画面已经表达的信息；不能把人物对白擅自转为旁白。',silent:'不生成旁白、对白或内心独白，仅用可见行动、自然反应、环境音与动作音叙事。原文语言信息若无法通过画面保留，列为改编待确认，不能悄悄删掉。'}[m])+`\n内心独白：${p.allowInnerVoice&&m!=='silent'?'仅允许原文明示的角色心理语言；注明角色音色、闭嘴、无口型同步，不把环境叙述强制转换为心理语言。':'不使用；心理描写优先转化为可见表现，不能凭空发明角色台词。'}\n资料模板中的风格、旁白禁令、固定镜数、固定转场和平台时长只是原模板条件，不能覆盖本项目设置。用户确认事实与本项目声音设置优先。`;
}
function knowledgeFor(p,knowledge,stage){return knowledge.filter(k=>(!k.narrativeModes||k.narrativeModes.includes(mode(p)))&&(!stage||!k.stages?.length||k.stages.includes(stage))).map(k=>k.id?.startsWith('builtin_30s_')?{...k,text:'30S 方法的跨语言适配：借鉴同场景同事件的首尾人物站位、视线、左右手与道具归属、动作进度、机位轴线和光线延续。下一段明确复述上一段末帧，不能只写接上段。镜头按新的信息、动作或情绪推进；主体、听者与背影保持自然生命感。角色对白注明真正说话者，可覆盖听者反应，但听者不替说话者对口型。旁白、独白和对白是否使用完全服从本项目声音设置。原30S中的固定英文输出、英语语速、旁白音色与性别、无人声1秒上限、禁配乐均不迁移到任何模式；静默和完整动作按实际需要留时。只有用户主动选择30S镜数规格时才使用对应镜数要求。'}:k);}
function voiceIssues(p,g){const errors=[];for(const [i,sh] of (g.shots||[]).entries()){const text=String(sh.voice||'').trim();const active=text.replace(/(?:无|不含|没有|禁止)(?:对白|旁白|独白|人声)/g,'');if(['drama','silent'].includes(mode(p))&&/(?:旁白|解说|narrat(?:or|ion)|voice\s*over)\s*[：:（(“"]|画外音[-—：:]旁白/i.test(active))errors.push(`镜${i+1}含旁白，与当前叙事模式冲突`);if((!p.allowInnerVoice||mode(p)==='silent')&&/内心独白|心理独白/.test(active))errors.push(`镜${i+1}含未允许的内心独白`);if(mode(p)==='silent'&&!/^(?:无|无对白|无人声|无语言|无台词|静默|仅环境音)[。；;\s]*$/.test(text))errors.push(`镜${i+1}请将人声设为“无人声”，保留环境音字段`);}return [...new Set(errors)];}
function assetGuide(p,a){const general=`资产设定图与剧情表演分开。遵守已确认身份、时代、物种、服饰、材质、比例、色彩和原文特殊体征；未知细节标为建议。视觉风格采用项目“${p.style||'按确认设计'}”，不得强制国风3D、默认美化、改年龄或套用课程性别配饰限制。各视图为同一资产，统一比例、光源与纹理位置，完整不裁切。`;
if(a.kind==='character')return general+'\n人物定版：正面全身、侧面全身、背面全身、头部特写，按此顺序横排，简洁背景。定妆姿态自然中性，肤质按年龄与身份保留特征，不塑料磨皮。独立可移动道具另建资产，基础图可双手空置，但不得删除确认的身体辅助器具、固定服饰或标志特征。若为动物或非人角色，按该物种解剖设计三视图，不能套用人类四视图姿态。剧情中再单独设计动作、表情与道具交互。';
if(a.kind==='scene')return general+'\n场景底板：无临时演员与动物；固定建筑装饰按原文保留。说明尺度、入口出口、遮挡、固定家具、主光方向和可拍机位，另列人物活动区域。场景底板的空景要求不能传递为剧情镜头“没有人物”。';
return general+'\n道具定版：正面、侧面、背面，完整保留功能部件与附件，给出尺寸参照、材质及持握部位。有收纳/展开/激活状态时分别给出提示词并列明不变结构；没有对应状态不凭空创造。特效仅依已确认设定添加，不遮挡主体结构。';}
C.normalize=function(p){p=old.normalize(p);p.narrativeMode=mode(p);p.allowInnerVoice=Boolean(p.allowInnerVoice);p.voiceLanguage||='保持原文语言';p.languagePolicy||=(p.voiceLanguage==='保持原文语言'?'source':'translate');p.scriptDrafts||=[];return p;};
C.context=function(p,s,g,knowledge){const guide=narrativeGuide(p);const budget=p.maxContextChars||28000;const ctx=old.context({...p,maxContextChars:Math.max(16000,budget-guide.length-80)},s,g,knowledgeFor(p,knowledge,'shots'));const text=ctx.text+'\n\n【本项目叙事声音约束】\n'+guide;if(text.length>budget)throw Error('叙事声音约束与本段内容超出上下文预算');return {...ctx,text,characters:text.length,budget};};
C.audit=(p,s,g)=>[...old.audit(p,s,g),...voiceIssues(p,g)];
C.promptText=(s,g,p)=>old.promptText(s,g,p)+'\n\n【叙事与声音】\n'+narrativeGuide(p);
C.compile=function(p,s,g){const errors=voiceIssues(p,g);if(errors.length)throw Error(errors.join('；'));const result=old.compile(p,s,g);for(const t of result.tasks){t.narrativeMode=mode(p);t.voiceLanguage=p.languagePolicy==='translate'?p.voiceLanguage:'逐句保持剧本原有语言';t.languagePolicy=p.languagePolicy||'source';t.prompt+='\n'+narrativeGuide(p);t.audioText=g.shots[t.shot-1]?.voice||'';}return result;};
Object.assign(C,{narrativeModes,narrativeGuide,languageGuide,knowledgeFor,voiceIssues,assetGuide,narrativeMode:mode});return C;
});
