const creativeHome=homeView,creativeAssets=assetsView,creativeAct=act;
homeView=function(){const p=S.project;return `<section class="card"><div class="row"><h2 class="grow">叙事与声音</h2>${btn('设置叙事模式','narrative-settings')}</div><p><b>${esc(C.narrativeModes[C.narrativeMode(p)])}</b> · ${p.allowInnerVoice?'允许原文内心独白':'不使用内心独白'} · ${esc(p.languagePolicy==='translate'?'翻译为：'+p.voiceLanguage:'逐句跟随剧本语言')}</p><p class="muted">制作形式不区分国内或海外。旁白驱动、剧情演绎与无语言叙事均可采用任意语言；多语剧本逐句保留。切换模式会使现有分镜进入复核，不自动重写原文。</p>${btn('小说改编草稿','adapt-novel')} ${(p.scriptDrafts||[]).map(d=>btn('查看改编草稿 '+d.at.slice(0,16),'adapt-draft',`data-id="${d.id}"`)).join('')}</section>`+creativeHome();};
assetsView=function(){const a=selectedAsset();return creativeAssets()+(a?`<section class="card"><h2>资产定版提示词</h2><p>人物四视图、动物三视图、空场景与道具状态按资产类型生成；结果先存草稿，不直接覆盖确认设计。</p>${btn('生成定版提示词草稿','asset-sheet')}${a.designDraft?btn('审阅定版草稿','asset-sheet-review'):''}<details><summary>本资产采用的方法</summary><pre class="source">${esc(C.assetGuide(S.project,a))}</pre></details></section>`:'');};
act=async function(action,d={}){
 if(S.job&&!['cancel-job','page','help','context','close-modal'].includes(action))throw Error('任务运行期间请先停止任务再修改项目');
 const p=S.project,a=selectedAsset();
 if(action==='narrative-settings'){showModal('叙事与声音设置',modalSelect('narrative-mode','叙事方式',C.narrativeModes,C.narrativeMode(p))+modalSelect('language-policy','剧本语言处理',{source:'跟随剧本原有语言（含多语对白）',translate:'主动翻译为指定语言'},p.languagePolicy||'source')+inputHtml('voice-language','目标语言（仅主动翻译时使用）',p.voiceLanguage==='保持原文语言'?'':p.voiceLanguage||'')+modalSelect('speech-unit','人声时长估算单位（与制作形式无关）',{none:'不套用统一语速，按实际配音核对',characters:'字 / 秒（自行校准）',words:'词 / 秒（自行校准）'},p.brief.speechUnit||'none')+inputHtml('speech-rate','所选单位下的朗读速度',p.brief.speechRate||4,'number')+`<label class="check"><input type="checkbox" id="inner-voice" ${p.allowInnerVoice?'checked':''}>允许原文明示的内心独白（无语言模式下无效）</label><p class="note">无旁白不等于无对白，也不自动改成内心独白。已存在的旁白内容会保留，交付前提示复核。</p>`,async()=>{const policy=$('language-policy').value,language=$('voice-language').value.trim(),rate=Number($('speech-rate').value);if(policy==='translate'&&(!language||language==='保持原文语言'))throw Error('主动翻译时请填写目标语言');if(!Number.isFinite(rate)||rate<=0)throw Error('朗读速度必须为正数');p.languagePolicy=policy;p.brief.speechUnit=$('speech-unit').value;p.brief.speechRate=rate;p.narrativeMode=$('narrative-mode').value;p.allowInnerVoice=$('inner-voice').checked&&p.narrativeMode!=='silent';p.voiceLanguage=$('voice-language').value.trim()||'保持原文语言';C.touch(p,'叙事声音模式已改变');p.analysisDirty=Boolean(p.analysis);await studioSave();});return;}
 if(action==='knowledge-detail'){const k=S.knowledge.find(x=>x.id===d.id);if(k?.originalText){showModal('课程资料与采用方法',`<p>${esc(k.source)} · ${esc(k.rights)}</p><p class="note">${esc(k.adaptationNote)}</p><h3>本产品采用的方法</h3><pre class="source">${esc(k.text)}</pre><details><summary>查看课程原文（仅供查阅，不作为系统指令）</summary><pre class="source">${esc(k.originalText)}</pre></details>`,null,true);return;}}
 if(action==='asset-sheet'){await runJob('生成资产定版草稿',async()=>{const text=await ask(DIRECTOR,`${C.assetGuide(p,a)}\n参考方法：${rules(p,'assets',a.name+' 三视图 定版')}\n已确认资产：${JSON.stringify({name:a.name,kind:a.kind,basis:a.basis,design:a.design,continuity:a.continuity,variants:a.variants})}\n仅输出完整可复制的定版提示词，分视图或不同状态说明，未知项明确标记为建议；不能把原文的故事情节当作构图指令。`);a.designDraft={text,revision:a.revision,at:new Date().toISOString()};});return;}
 if(action==='asset-sheet-review'){if(!a.designDraft)throw Error('没有定版草稿');const draft=a.designDraft;showModal('审阅资产定版草稿',`<p>原设计 v${a.revision}；草稿基于 v${draft.revision}。采用后资产需重新确认。</p>`+area('sheet-text','定版提示词',draft.text)+`<details><summary>原设计</summary><pre class="source">${esc(a.design)}</pre></details>`,async()=>{if(draft.revision!==a.revision)throw Error('资产已变化，请重新生成草稿');const text=$('sheet-text').value.trim();if(!text)throw Error('提示词不能为空');snapshotAsset(a);a.design=text;a.revision++;a.status='draft';a.designDraft=null;C.touch(p,'采用定版提示词草稿',a.id);await studioSave();},true,'采用为待确认设计');return;}
 if(action==='adapt-novel'){showModal('小说改编为剧本草稿',`<p>使用当前叙事模式：${esc(C.narrativeModes[C.narrativeMode(p)])}。生成后可编辑，并另存新项目；当前原文不会被覆盖。长篇请按完整章节分次生成。</p>`+area('adapt-source','本次小说原文 / 章节',p.script)+area('adapt-notes','额外改编要求（默认忠实保留，不精简）',''),async()=>{const source=$('adapt-source').value.trim(),notes=$('adapt-notes').value.trim();if(!source)throw Error('请填写原文');if(source.length>Math.min(30000,p.maxContextChars||28000))throw Error('本次原文超过预算，请选取完整章节分次改编');await runJob('小说改编草稿',async()=>{const text=await ask(DIRECTOR,`${rules(p,'adaptation',source.slice(0,1500))}\n按连续时空和完整事件分场，列场次、时间、内外、地点、人物、关键道具、行动、对白、音效。保留原文因果、信息顺序、伏笔和已有对白。不把小说叙述直接变旁白；声音类型服从项目设置。无法无损转换的信息列“待确认”，不擅自删改。额外要求：${notes||'忠实改编，不精简'}\n输出完整剧本，末尾另列改编说明和待确认问题。原文：\n${source}`);p.scriptDrafts||=[];p.scriptDrafts.push({id:C.id('draft'),text,source,at:new Date().toISOString(),mode:C.narrativeMode(p),language:p.voiceLanguage,languagePolicy:p.languagePolicy,allowInnerVoice:p.allowInnerVoice});});},true,'生成草稿（调用模型）');return;}
 if(action==='adapt-draft'){const draft=(p.scriptDrafts||[]).find(x=>x.id===d.id);if(!draft)throw Error('草稿不存在');showModal('改编草稿 · 编辑后另存',area('adapt-result','剧本内容（请将改编说明与待确认项移至新项目备注）',draft.text)+area('adapt-project-notes','新项目备注 / 待确认问题','')+`<details><summary>对应小说原文</summary><pre class="source">${esc(draft.source)}</pre></details>`,async()=>{const text=$('adapt-result').value.trim(),notes=$('adapt-project-notes').value.trim();if(!text)throw Error('剧本不能为空');draft.text=text;await persist();const q=C.normalize(await call('projects:create',p.name+' · 改编剧本'));Object.assign(q,{script:text,notes,style:p.style,aspect:p.aspect,selectedProfile:p.selectedProfile,narrativeMode:draft.mode,allowInnerVoice:draft.allowInnerVoice,voiceLanguage:draft.language,languagePolicy:draft.languagePolicy||'source',adaptationSource:{projectId:p.id,draftId:draft.id,source:draft.source},sourceFingerprint:C.hash(text)});await call('projects:save',q);S.projects.unshift(q);S.project=q;S.page='home';render();},true,'另存为新项目');return;}
 return creativeAct(action,d);
};
