const DIAG={records:[],selected:null,loaded:false,loading:false,preview:null,busy:false,dirty:new Set(),timer:null,saveChain:Promise.resolve(),revision:new Map()};
function diagnosisCurrent(){return DIAG.records.find(r=>r.id===DIAG.selected)||DIAG.records[0]||null;}
async function diagnosisLoad(){if(DIAG.loading)return;DIAG.loading=true;try{DIAG.records=await call('diagnosis:list');DIAG.loaded=true;}finally{DIAG.loading=false;}if(S.page==='diagnosis')render();}
function diagnosisView(){if(!DIAG.loaded&&!DIAG.loading)setTimeout(()=>diagnosisLoad().catch(showError),0);const r=diagnosisCurrent();return pageHead('短片诊断','针对自己的成片复盘：先记录可见事实，再定位问题和修改动作。',btn('导入待诊断短片','diagnosis-import','','primary'))+
 `<div class="diagnosis-layout"><aside class="diagnosis-list"><h3>诊断记录</h3>${DIAG.records.map(x=>btn(esc(x.name),'diagnosis-select',`data-id="${x.id}"`,r?.id===x.id?'active':'')).join('')||'<p class="muted">可以不连接模型，先导入视频并手工记录。</p>'}</aside><section class="diagnosis-detail">${r?`<div class="section-head"><div><h2>${esc(r.name)}</h2><p class="muted">${r.reviewed?'已人工复核':'诊断草稿'} · ${esc(r.updatedAt?.slice(0,16)||'')}</p></div><div class="row wrap">${btn('保存','diagnosis-save')}${btn('导出诊断报告','diagnosis-export')}</div></div>${DIAG.preview?`<video id="diagnosis-video" class="diagnosis-video" controls preload="metadata" src="${esc(DIAG.preview)}"></video>`:btn('加载原视频','diagnosis-preview')}`+
 `<div class="diagnosis-guide"><strong>诊断顺序</strong><span>目标与受众 → 自己观察 → 逐项定位 → 可执行修改 → 人工复核。模型只看稀疏采样帧和文字，不读取音轨。</span></div><div class="grid">${inputHtml('diag-goal','短片要让观众理解或感受什么',r.goal)}${inputHtml('diag-audience','目标受众与发布场景',r.audience)}${inputHtml('diag-format','片型 / 画幅 / 目标时长',r.format)}${inputHtml('diag-concerns','最想检查的 1—3 个问题',r.concerns)}</div>${area('diag-observation','人工观察：具体时间点、画面与听到的声音',r.observation)}<div class="toolbar">${btn(DIAG.busy?'分析中…':'AI 辅助诊断（可能计费）','diagnosis-analyze',DIAG.busy||!DIAG.preview?'disabled':'','primary')}</div><p class="muted">分析会发送五张等距采样帧及上方文字。运动、声音、精确镜头参数须由你核对；无模型时下方报告仍可手工填写和导出。</p>${area('diag-summary','整体判断',r.summary)}${area('diag-issues','问题清单：位置／观察／影响／原因／修改',r.issues)}${area('diag-plan','优先级修改计划',r.plan)}<label class="check"><input id="diag-reviewed" type="checkbox" ${r.reviewed?'checked':''}>已对照原片人工复核诊断结论</label>`:'<div class="study-empty">导入你自己的短片后，可手工诊断，也可在连接模型后辅助分析。</div>'}</section></div>`;}
function diagnosisValues(){const r=diagnosisCurrent();if(!r)throw Error('请先导入短片');return {...r,goal:$('diag-goal').value,audience:$('diag-audience').value,format:$('diag-format').value,concerns:$('diag-concerns').value,observation:$('diag-observation').value,summary:$('diag-summary').value,issues:$('diag-issues').value,plan:$('diag-plan').value,reviewed:$('diag-reviewed').checked};}
const DIAG_FIELDS={goal:'diag-goal',audience:'diag-audience',format:'diag-format',concerns:'diag-concerns',observation:'diag-observation',summary:'diag-summary',issues:'diag-issues',plan:'diag-plan'};
function diagnosisStatus(message,failed=false){const el=$('diagnosis-save-status');if(el){el.textContent=message;el.classList.toggle('error',failed);}if(S.page==='diagnosis')$('save-status').textContent=message;}
function diagnosisDirty(){const r=diagnosisCurrent();if(!r)return;DIAG.dirty.add(r.id);DIAG.revision.set(r.id,(DIAG.revision.get(r.id)||0)+1);diagnosisStatus('诊断待保存');clearTimeout(DIAG.timer);DIAG.timer=setTimeout(()=>diagnosisFlush().catch(e=>{diagnosisStatus('诊断保存失败 · 请重试',true);showError(e);}),500);}
async function diagnosisFlush(){clearTimeout(DIAG.timer);DIAG.timer=null;for(const id of [...DIAG.dirty]){const r=DIAG.records.find(x=>x.id===id);if(!r)continue;const revision=DIAG.revision.get(id),snapshot={...r};DIAG.saveChain=DIAG.saveChain.catch(()=>{}).then(()=>call('diagnosis:save',snapshot));try{const saved=await DIAG.saveChain;r.updatedAt=saved.updatedAt;if(DIAG.revision.get(id)===revision)DIAG.dirty.delete(id);diagnosisStatus(DIAG.dirty.size?'诊断待保存':'诊断已保存');}catch(e){e.diagnosisDraft=true;diagnosisStatus('诊断保存失败 · 请重试',true);throw e;}}if(DIAG.dirty.size)await diagnosisFlush();}
document.addEventListener('input',e=>{if(S.page!=='diagnosis'||!diagnosisCurrent())return;const key=Object.keys(DIAG_FIELDS).find(k=>DIAG_FIELDS[k]===e.target.id);if(!key)return;diagnosisCurrent()[key]=e.target.value;diagnosisCurrent().reviewed=false;const checked=$('diag-reviewed');if(checked)checked.checked=false;diagnosisDirty();});
document.addEventListener('change',e=>{if(S.page==='diagnosis'&&e.target.id==='diag-reviewed'&&diagnosisCurrent()){diagnosisCurrent().reviewed=e.target.checked;diagnosisDirty();}});
function diagnosisMarkdown(r){return `# ${r.name} · 观澜短片诊断\n\n复核状态：${r.reviewed?'已人工复核':'草稿，待人工复核'}\n\n## 目标与受众\n\n目标：${r.goal||'未填写'}\n\n受众：${r.audience||'未填写'}\n\n片型：${r.format||'未填写'}\n\n## 人工观察\n\n${r.observation||'未填写'}\n\n## 整体判断\n\n${r.summary||'未填写'}\n\n## 问题清单\n\n${r.issues||'未填写'}\n\n## 优先级修改计划\n\n${r.plan||'未填写'}\n\n---\n模型仅查看稀疏采样帧与用户文字；未读取原视频音轨。精确运镜、声音与未采样动作以人工复核为准。原视频不随报告导出。\n`;}
const diagnosisRenderBase=render;
render=function(){diagnosisRenderBase();WS_PAGES.diagnosis='短片诊断';if(S.page==='diagnosis'){$('breadcrumb').textContent='本机工作区 / 短片诊断';$('content').innerHTML=diagnosisView();const note=document.querySelector('.diagnosis-detail .section-head .muted');if(note)note.insertAdjacentHTML('beforeend',` · <span id="diagnosis-save-status">${DIAG.dirty.size?'诊断待保存':'诊断已保存'}</span>`);}};
const diagnosisActBase=act;
const diagnosisPersistBase=persist;persist=async function(){await diagnosisFlush();return diagnosisPersistBase();};
act=async function(action,d={}){
 if(action==='diagnosis-rescue'){const drafts=DIAG.records.filter(x=>DIAG.dirty.has(x.id));if(!drafts.length)throw Error('当前没有未保存的诊断草稿');const file=await call('files:export',{name:'观澜-短片诊断-应急草稿',format:'md',text:drafts.map(diagnosisMarkdown).join('\n\n---\n\n')});if(file)showModal('诊断草稿已另存',`<p>未保存的诊断文字已导出到：</p><pre class="source">${esc(file)}</pre><p>请修复资料位置后再点“保存”，确认标题旁显示“诊断已保存”。</p>`,null,true);return;}
 if(S.page==='diagnosis'&&['page','help','guide-chapter','nav-back','nav-forward','select-project','diagnosis-select','diagnosis-import','diagnosis-export'].includes(action))await diagnosisFlush();
 if(action==='diagnosis-import'){const record=await call('diagnosis:import');if(!record)return;DIAG.records.unshift(record);DIAG.selected=record.id;DIAG.loaded=true;DIAG.preview=await call('diagnosis:preview',record.id);S.page='diagnosis';render();return;}
 if(action==='diagnosis-select'){DIAG.selected=d.id;DIAG.preview=null;render();return;}
 if(action==='diagnosis-preview'){DIAG.preview=await call('diagnosis:preview',diagnosisCurrent().id);render();return;}
 if(action==='diagnosis-save'){Object.assign(diagnosisCurrent(),diagnosisValues());diagnosisDirty();await diagnosisFlush();render();toast('诊断记录已保存');return;}
 if(action==='diagnosis-export'){const saved=await call('diagnosis:save',diagnosisValues());Object.assign(diagnosisCurrent(),saved);await call('files:export',{name:'观澜-短片诊断-'+saved.name.replace(/\.[^.]+$/,''),format:'md',text:diagnosisMarkdown(saved)});render();return;}
 if(action==='diagnosis-analyze'){
  if(DIAG.busy)return;
  await diagnosisFlush();
  const r=diagnosisValues(),video=$('diagnosis-video');if(!video||!Number.isFinite(video.duration)||video.duration<=0)throw Error('请先加载可播放的视频');
  if(!S.settings.model||!S.settings.vision)throw Error('AI 短片诊断需要已启用图片输入的文字模型；你仍可手工填写并导出诊断报告');
  const sourceRevision=DIAG.revision.get(r.id)||0;DIAG.busy=true;const button=document.querySelector('[data-action="diagnosis-analyze"]');if(button){button.disabled=true;button.textContent='正在采样与分析…';}
  try{const times=[.1,.3,.5,.7,.9].map(x=>Math.min(video.duration-.04,video.duration*x)),images=[];video.pause();for(const t of times)images.push(await filmFrame(video,t));const requestId=C.id('diag');const raw=await call('model:generate',{requestId,kind:'diagnosis',projectId:S.project?.id,projectName:S.project?.name,system:'你是影视短片诊断助手。只能根据五张稀疏采样帧和用户文字作判断。明确区分可见事实、合理推测和无法判断；不得声称听到声音、看到帧间动作或精确知道焦距。只返回JSON。',user:`片长 ${video.duration.toFixed(2)} 秒。采样时刻：${times.map(x=>x.toFixed(2)).join('、')} 秒。目标：${r.goal}；受众：${r.audience}；片型：${r.format}；待查问题：${r.concerns}；人工观察：${r.observation}。请输出 {"summary":"整体判断","issues":[{"severity":"高/中/低","at":"时间点或范围","observation":"可见事实","impact":"影响","cause":"可能原因与不确定项","fix":"可执行修改"}],"plan":"按优先级排序的修改步骤"}。镜头缺失、声音和未采样动作必须标明待人工核对。`,images});const parsed=C.parseJson(raw);if(typeof parsed.summary!=='string'||!Array.isArray(parsed.issues)||typeof parsed.plan!=='string')throw Error('模型返回结构不完整，未写入诊断');if(DIAG.revision.get(r.id)!==sourceRevision)throw Error('分析期间诊断输入已变化；为避免覆盖新内容，本次结果未采用，请重新分析');r.summary=parsed.summary;r.issues=parsed.issues.slice(0,30).map((x,i)=>`${i+1}. [${x.severity||'待定'}] ${x.at||'位置待确认'}\n观察：${x.observation||'未提供'}\n影响：${x.impact||'待确认'}\n可能原因：${x.cause||'待确认'}\n修改：${x.fix||'待确认'}`).join('\n\n');r.plan=parsed.plan;r.model=S.settings.model;r.reviewed=false;const saved=await call('diagnosis:save',r);Object.assign(DIAG.records.find(x=>x.id===saved.id),saved);toast('诊断草稿已生成，请对照原片核对');}
  finally{DIAG.busy=false;render();}return;
 }
 const result=await diagnosisActBase(action,d);


 return result;
};
