(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./core'));else factory(root.DirectorCore);})(globalThis,C=>{
const old={normalize:C.normalize,context:C.context,validate:C.validate,promptText:C.promptText,invalidateAfter:C.invalidateAfter};
const hash=text=>{let h=2166136261;for(const c of String(text))h=Math.imul(h^c.charCodeAt(0),16777619);return (h>>>0).toString(16);};
const actorFields={presence:'在场状态',x:'横向坐标',y:'纵向坐标',facing:'身体朝向',gaze:'视线目标',left:'左手道具',right:'右手道具',pose:'姿态',attention:'注意力与微反应',phase:'动作阶段'};
const genres={general:'遵守叙事因果，镜头有动机。',manju:'情绪必须转化为可见表演；听者、背影与背景人物有克制反应；不额外添加原文没有的信息。',shortfilm:'按完整动作与戏剧节拍安排镜头，可保留静默与长镜头，不机械切镜。',commercial:'品牌信息、产品外观、卖点证据和行动引导必须与项目简报一致；不得编造产品功效。',mv:'遵循音乐 BPM、节拍与段落，动作与切点对齐音乐，不强加剧情对白。',documentary:'区分已证实事实、受访者陈述和重现场景；引用来源；未知事实不补写，AI 重现必须标注。',animation:'保持造型、运动规律和世界观；夸张幅度服从角色设定。',custom:'以项目自定义要求为准。'};
const adapters={
 generic:{name:'通用视频模型',max:30,reference:false,source:'',aspects:null},
 seedance25:{name:'Seedance 2.5',max:30,reference:false,aspects:['21:9','16:9','4:3','1:1','3:4','9:16'],source:'https://docs.volcengine.com/docs/ark/seedance-2-5'},
 seedance20:{name:'Seedance 2.0',max:15,reference:false,aspects:['21:9','16:9','4:3','1:1','3:4','9:16'],source:'https://docs.volcengine.com/docs/ark/seedance-2-5'},
 seedance20fast:{name:'Seedance 2.0 Fast',max:15,reference:false,aspects:['21:9','16:9','4:3','1:1','3:4','9:16'],source:'https://docs.volcengine.com/docs/ark/seedance-2-5'},
 seedance20mini:{name:'Seedance 2.0 Mini',max:15,reference:false,aspects:['21:9','16:9','4:3','1:1','3:4','9:16'],source:'https://docs.volcengine.com/docs/ark/seedance-2-5'},
 minimaxh3:{name:'MiniMax H3',max:15,reference:false,aspects:['21:9','16:9','4:3','1:1','3:4','9:16'],source:'https://www.minimax.io/blog/minimax-h3'},
 minimaxs3:{name:'MiniMax S3 · 待核实',max:null,reference:false,aspects:null,note:'按创作者提供的名称保留交付目标；截至 2026-10-07 未在 MiniMax 官方模型目录确认 S3 视频型号或 API，不自动套用 H3 规格，也不能从观澜直接提交。',source:'https://www.minimax.io/news'},
 minimaxh3local:{name:'MiniMax H3 · 本地模型',max:15,reference:false,aspects:['21:9','16:9','4:3','1:1','3:4','9:16'],note:'开源权重预设；须自行部署模型与推理服务，观澜不随安装包分发权重。',source:'https://www.minimax.io/news/minimax-h3-open-source'},
 wan30:{name:'通义万相 Wan 3.0',max:30,reference:false,aspects:['21:9','16:9','4:3','1:1','3:4','9:16'],source:'https://docs.modelstudio.console.alibabacloud.com/en/model-studio/wan3-video-generation-guide'},
 wan30prime:{name:'通义万相 Wan 3.0 Prime',max:30,reference:false,aspects:['21:9','16:9','4:3','1:1','3:4','9:16'],source:'https://docs.modelstudio.console.alibabacloud.com/en/model-studio/wan3-video-generation-guide'},
 wan27:{name:'通义万相 Wan 2.7',max:15,reference:false,aspects:null,source:'https://docs.modelstudio.console.alibabacloud.com/en/model-studio/video-generate-edit-model'},
 happyhorse:{name:'HappyHorse 1.0',max:15,reference:false,aspects:null,source:'https://docs.modelstudio.console.alibabacloud.com/en/model-studio/video-generate-edit-model'},
 kling3:{name:'可灵 VIDEO 3.0',max:15,reference:false,aspects:['16:9','9:16'],source:'https://helpx.adobe.com/firefly/web/work-with-audio-and-video/work-with-video/generate-videos-using-kling.html'},
 kling3omni:{name:'可灵 VIDEO 3.0 Omni',max:15,reference:false,aspects:['16:9','9:16'],source:'https://helpx.adobe.com/firefly/web/work-with-audio-and-video/work-with-video/generate-videos-using-kling.html'},
 runway4:{name:'Runway Gen-4 · 图生视频',max:10,durations:[5,10],reference:true,aspects:['21:9','16:9','4:3','1:1','3:4','9:16'],source:'https://help.runwayml.com/hc/en-us/articles/37327109429011-Creating-with-Gen-4-Video'},
 runway45:{name:'Runway Gen-4.5',max:10,reference:false,aspects:['21:9','16:9','4:3','1:1','3:4','9:16'],note:'纯文生视频仅 16:9；其他画幅需图生视频并核对参考图裁剪。',source:'https://help.runwayml.com/hc/en-us/articles/46974685288467-Creating-with-Gen-4-5'},
 veo31:{name:'Google Veo 3.1',max:8,durations:[4,6,8],reference:false,aspects:['16:9','9:16'],source:'https://ai.google.dev/gemini-api/docs/veo'},
 veo31fast:{name:'Google Veo 3.1 Fast',max:8,durations:[4,6,8],reference:false,aspects:['16:9','9:16'],source:'https://ai.google.dev/gemini-api/docs/veo'},
 veo31lite:{name:'Google Veo 3.1 Lite',max:8,durations:[4,6,8],reference:false,aspects:['16:9','9:16'],source:'https://ai.google.dev/gemini-api/docs/veo'},
 geminiomni:{name:'Google Gemini Omni Flash',max:null,reference:false,aspects:null,note:'多模态视频预设；请以 Google 当前区域权限与接口文档核对。',source:'https://ai.google.dev/gemini-api/docs/models'},
 ray32:{name:'Luma Ray3.2',max:10,durations:[5,10],reference:false,aspects:null,source:'https://docs.agents.lumalabs.ai/api/python/resources/generations/methods/create/'},
 firefly:{name:'Adobe Firefly Video',max:5,durations:[5],reference:false,aspects:['16:9','9:16','1:1'],source:'https://helpx.adobe.com/firefly/mobile/work-with-audio-and-video/work-with-video/generate-videos-using-text-prompts.html'},
 grok15:{name:'Grok Imagine Video 1.5',max:15,reference:false,aspects:['16:9','9:16','1:1','4:3','3:4'],note:'xAI 视频 API 预设；目前用于提示词交付，未连接观澜的生成任务队列。',source:'https://docs.x.ai/developers/model-capabilities/video/generation'},
 grok:{name:'Grok Imagine Video',max:15,reference:false,aspects:['16:9','9:16','1:1','4:3','3:4'],note:'xAI 旧版视频模型交付预设；优先核对账号是否已提供 1.5。',source:'https://docs.x.ai/developers/models/grok-imagine-video'},
 viduq3:{name:'Vidu Q3',max:16,reference:false,aspects:null,source:'https://s.vidu.com/vidu-q3'},
 pixversev6:{name:'PixVerse V6',max:15,reference:false,aspects:null,source:'https://pixverse.ai/en/model/pixverse-v6'},
 pixversec1:{name:'PixVerse C1',max:15,reference:false,aspects:null,source:'https://pixverse.ai/en/blog/pixverse-introduces-c1-ai-video-model-for-film-production'},
 pika22:{name:'Pika 2.2',max:10,reference:false,aspects:null,source:'https://pika.art/faq'},
 hailuo23:{name:'海螺 Hailuo 2.3',max:null,reference:false,aspects:null,note:'平台预设；时长、比例和接口权限请在使用前核对。',source:'https://www.minimax.io/'},
 hailuo23fast:{name:'海螺 Hailuo 2.3 Fast',max:null,reference:false,aspects:null,note:'平台预设；具体档位和接口权限请在使用前核对。',source:'https://www.minimax.io/'},
 ltx2:{name:'LTX-2 · 本地模型',max:null,reference:false,aspects:null,note:'开源模型预设；需要自行部署，观澜目前不内置模型权重或推理服务。',source:'https://github.com/Lightricks/LTX-2'},
 wan22:{name:'Wan 2.2 · 本地模型',max:null,reference:false,aspects:null,note:'开源模型预设；需要自行部署，观澜目前不内置模型权重或推理服务。',source:'https://github.com/Wan-Video/Wan2.2'},
 hunyuanvideo:{name:'腾讯混元 HunyuanVideo · 本地模型',max:null,reference:false,aspects:null,note:'开源模型预设；需要自行部署，观澜目前不内置模型权重或推理服务。',source:'https://github.com/Tencent-Hunyuan/HunyuanVideo'}
};
function modelFor(p){const target=Object.values(adapters).find(a=>a.name===p.videoTarget);if(p.adapter&&p.adapter!=='generic'&&adapters[p.adapter])return adapters[p.adapter];if(target)return target;return p.videoTarget&&p.videoTarget!=='通用视频模型'?{...adapters.generic,name:p.videoTarget,unverified:true}:adapters.generic;}
function normalize(p){if(Number(p.schemaVersion)>3)throw Error('请升级程序以读取此项目');p=old.normalize(p);if(p.schemaVersion>3)throw Error('项目版本高于当前程序，请升级后打开');p.schemaVersion=3;for(const collection of [p.assets,p.sequences,...p.sequences.map(s=>s.segments)])for(const item of collection)if(!/^[A-Za-z][\w-]{0,100}$/.test(item.id))throw Error('项目含无效实体编号');for(const key of ['facts','rules','comments','deliveries','feedback','experiments','changeLog','assetProposals'])if(!Array.isArray(p[key]))p[key]=[];p.brief||={};p.adapter||='generic';p.owner||='创作者';p.compact=Boolean(p.compact);p.sourceFingerprint||=hash(p.script);p.rights||={script:'unknown',images:'unknown',notes:''};p.adapterSettings||={};for(const a of p.assets){if(!Array.isArray(a.references)||!Array.isArray(a.versions))throw Error('资产集合结构损坏');a.aliases=Array.isArray(a.aliases)?a.aliases:[];a.variants||='';a.sourceRevision||=p.scriptRevision;}for(const s of p.sequences){s.axis||='场景俯视图：左西右东、上北下南；坐标0–100。机位在对话轴同一侧。';for(const g of s.segments){if(!Array.isArray(g.shots))throw Error('镜头集合结构损坏');g.stageStart=Array.isArray(g.stageStart)?g.stageStart:[];g.stageEnd=Array.isArray(g.stageEnd)?g.stageEnd:[];g.factIds||=[];g.owner||=p.owner;g.reviewStatus||=g.reviewed?'approved':'draft';g.stateSchema||=0;}}return p;}
function units(text){const out=[];const re=/[^\n。！？!?]+[。！？!?]*(?:\r?\n)*|[\n。！？!?]+/g;let m;while((m=re.exec(text)))out.push({id:out.length+1,start:m.index,end:m.index+m[0].length,text:m[0]});return out;}
function locate(p,g){if(Number.isInteger(g.sourceStart)&&p.script.slice(g.sourceStart,g.sourceEnd)===g.sourceText)return {start:g.sourceStart,end:g.sourceEnd};const start=p.script.indexOf(g.sourceText);if(!g.sourceText||start<0)return null;if(p.script.indexOf(g.sourceText,start+1)>=0)return null;return {start,end:start+g.sourceText.length};}
function diff(before,after,fields){return fields.filter(k=>JSON.stringify(before?.[k])!==JSON.stringify(after?.[k])).map(k=>({field:k,before:before?.[k],after:after?.[k]}));}
function touch(p,reason,assetId){const affected=[];for(const s of p.sequences){if(assetId&&!s.assetIds.includes(assetId))continue;for(const g of s.segments){g.reviewed=false;g.reviewStatus='draft';g.stale=Boolean(g.shots.length||g.prompt);g.staleReason=reason;affected.push(g.id);}}p.changeLog.unshift({id:C.id('change'),at:new Date().toISOString(),reason,affected});p.changeLog=p.changeLog.slice(0,100);return affected;}
function scriptChanged(p){p.sourceFingerprint=hash(p.script);for(const f of p.facts)if(f.status==='confirmed')f.status='stale';for(const a of p.assets){a.sourceReview=true;}touch(p,'剧本已修改：原文事实、资产依据和片段需要复核');}
function addProposal(p,item,range){const name=String(item.name||'').trim();const a=p.assets.find(a=>a.kind===item.kind&&(a.name===name||a.aliases.includes(name)));if(!a){p.assets.push({id:C.id('a'),kind:item.kind,name,basis:C.toText(item.basis),design:C.toText(item.design),continuity:C.toText(item.continuity),aliases:[],variants:'',references:[],versions:[],status:'draft',revision:1,sourceRevision:p.scriptRevision,sourceRanges:[range]});return;}
const proposed={basis:C.toText(item.basis),design:C.toText(item.design),continuity:C.toText(item.continuity)};const key=hash(JSON.stringify({asset:a.id,proposed,range}));if(p.assetProposals.some(x=>x.key===key))return;p.assetProposals.push({id:C.id('proposal'),key,assetId:a.id,proposed,range,status:'pending',at:new Date().toISOString()});a.sourceReview=true;touch(p,`资产 ${a.name} 有新依据待审批`,a.id);}
function factText(f){return `[${f.id}] ${f.text}（原文字符${f.start}–${f.end}，剧本版本${f.revision}，${f.kind==='suggestion'?'创作建议':'事实'}）`;}
function activeRules(p,stage){const rules=p.rules.filter(r=>r.enabled&&r.status==='approved'&&(r.stage==='all'||r.stage===stage)&&(!r.profile||r.profile==='all'||r.profile===p.selectedProfile));const groups=new Map();for(const r of rules){if(!r.conflictKey)continue;const list=groups.get(r.conflictKey)||[];list.push(r);groups.set(r.conflictKey,list);}for(const [key,list] of groups){if(list.length>1)throw Error(`导演规则冲突「${key}」：请在规则台停用冲突项，仅保留一条`);}return rules.sort((a,b)=>Number(b.priority||0)-Number(a.priority||0));}
function context(p,s,g,knowledge){const range=locate(p,g);if(!range)throw Error('本段原文无法唯一定位，请在原文定位中绑定字符范围');g.sourceStart=range.start;g.sourceEnd=range.end;
const assets=p.assets.filter(a=>s.assetIds.includes(a.id));if(assets.some(a=>a.sourceReview))throw Error('引用资产存在未复核的原文变化或提案');const relevant=p.facts.filter(f=>(f.critical||g.factIds.includes(f.id)||s.assetIds.includes(f.entityId))&&(!f.revealAt||Number(f.revealAt)<=range.end)&&(!f.validTo||Number(f.validTo)>=range.start));if(relevant.some(f=>f.status==='stale'))throw Error('关键事实已经过期，请先在事实台账复核');const facts=relevant.filter(f=>f.status==='confirmed');const rules=activeRules(p,'shots');const extension=`\n场次资产版本与别名：${JSON.stringify(assets.map(a=>({id:a.id,aliases:a.aliases,variants:a.variants})))}\n当前原文范围：${range.start}–${range.end}\n不可遗漏的已确认事实：\n${facts.map(factText).join('\n')||'尚未确认事实，不得补写未知信息。'}\n优先执行规则（不能覆盖用户确认事实）：\n${rules.map(r=>r.text).join('\n')}\n品类规范：${genres[p.selectedProfile]||genres.general}\n品类简报：${JSON.stringify(p.brief)}\n场景空间：${s.axis}\n结构化开场状态：${JSON.stringify(g.stageStart)}\n`;
const budget=Math.min(150000,Number(p.maxContextChars)||28000);if(extension.length>budget-8000)throw Error('关键事实与规则过多，无法安全纳入预算；请缩小事实适用范围');const originalBudget=p.maxContextChars;const base=old.context({...p,maxContextChars:Math.max(16000,budget-extension.length)},s,g,knowledge);const warnings=[];if(!base.sources.some(x=>x.ref==='bible')&&p.analysis)warnings.push('故事圣经因预算未全部纳入；当前任务以确认事实和原文为准');const enabled=knowledge.filter(k=>p.knowledgeOverrides[k.id]??k.enabledByDefault);for(const k of enabled)if(!base.sources.some(x=>x.ref.startsWith(k.id+':')))warnings.push(`未召回资料：${k.name}`);if(relevant.some(f=>f.status==='draft'))warnings.push('有相关事实尚未确认，未作为固定事实使用');const text=base.text+extension;if(text.length>budget)throw Error('本次上下文超过预算，请增加预算或缩小本段范围');return {...base,text,characters:text.length,budget:originalBudget||28000,warnings,factIds:facts.map(f=>f.id),sources:[...base.sources,...facts.map(f=>({label:factText(f),ref:f.id})),...rules.map(r=>({label:r.text,ref:r.id}))]};}
function canonical(state){return JSON.stringify((Array.isArray(state)?state:[]).map(x=>Object.fromEntries(['assetId',...Object.keys(actorFields)].map(k=>[k,k==='x'||k==='y'?Number(x[k]):String(x[k]??(k==='presence'?'present':''))]))).sort((a,b)=>a.assetId.localeCompare(b.assetId)));}
function stateErrors(state,ids,label){const errors=[];if(!Array.isArray(state))return [label+'缺少状态'];if(state.length!==ids.length||new Set(state.map(x=>x.assetId)).size!==ids.length||ids.some(id=>!state.some(x=>x.assetId===id)))errors.push(label+'人物集合与场景不一致');const props=new Map();for(const a of state){for(const [k,l] of Object.entries(actorFields)){if(k==='presence'){if(a.presence&&!['present','offscreen','absent'].includes(a.presence))errors.push(label+'在场状态无效');continue;}if(a.presence==='absent'&&!['left','right','phase'].includes(k))continue;if(k==='x'||k==='y'){if(a[k]===''||a[k]==null||!Number.isFinite(Number(a[k]))||Number(a[k])<0||Number(a[k])>100)errors.push(label+l+'必须在0–100');}else if(!String(a[k]??'').trim()||String(a[k]).includes('待确认'))errors.push(label+'缺少'+l);}for(const hand of ['left','right']){const prop=String(a[hand]||'');if(!prop||['空','无','none'].includes(prop))continue;if(props.has(prop)&&props.get(prop)!==a.assetId)errors.push(label+'道具同时被不同人物持有：'+prop);props.set(prop,a.assetId);}}return errors;}
function continuity(s,g,p){const errors=[];const propIds=p.assets.filter(a=>s.assetIds.includes(a.id)&&a.kind==='prop').map(a=>a.id);for(const state of [g.stageStart,g.stageEnd,...g.shots.flatMap(sh=>[sh.stateIn,sh.stateOut])])for(const actor of (Array.isArray(state)?state:[]))for(const hand of ['left','right'])if(actor[hand]&&!['空','无','none'].includes(actor[hand])&&!propIds.includes(actor[hand]))errors.push('手部道具必须使用本组已选择的道具资产ID：'+actor[hand]);const ids=p.assets.filter(a=>s.assetIds.includes(a.id)&&a.kind==='character').map(a=>a.id);errors.push(...stateErrors(g.stageStart,ids,'片段开场'),...stateErrors(g.stageEnd,ids,'片段结束'));let prev=g.stageStart;for(let i=0;i<g.shots.length;i++){const sh=g.shots[i];errors.push(...stateErrors(sh.stateIn,ids,`镜${i+1}开始`),...stateErrors(sh.stateOut,ids,`镜${i+1}结束`));if(canonical(sh.stateIn)!==canonical(prev))errors.push(`镜${i+1}与前一时刻状态不一致`);if(canonical(sh.stateIn)!==canonical(sh.stateOut)&&!String(sh.transition||'').trim())errors.push(`镜${i+1}状态变化缺少动作解释`);if(!String(sh.reactions||'').trim())errors.push(`镜${i+1}缺少在场人物反应设计`);if(sh.axisSide&&i&&g.shots[i-1].axisSide&&sh.axisSide!==g.shots[i-1].axisSide&&!String(sh.axisReason||'').trim())errors.push(`镜${i+1}越轴缺少动机与过渡`);prev=sh.stateOut;}if(g.shots.length&&canonical(prev)!==canonical(g.stageEnd))errors.push('末镜状态与片段结束不一致');const index=s.segments.indexOf(g);if(index>0&&canonical(g.stageStart)!==canonical(s.segments[index-1].stageEnd))errors.push('结构化开场与上一片段结束不一致');return [...new Set(errors)];}
function validate(s,g){const errors=old.validate(s,g);if(!Number.isFinite(Number(g.duration))||Number(g.duration)<=0)errors.push('片段时长必须为正数');g.shots.forEach((sh,i)=>{if(!Number.isFinite(Number(sh.duration)))errors.push(`镜${i+1}时长不是有效数字`);});return errors;}
function audit(p,s,g){const problems=validate(s,g);if(!g.shots.length)problems.push('没有镜头');if(p.analysisDirty)problems.push('故事圣经过期');if(!s.assetIds.length)problems.push('未选择资产');if(s.assetIds.some(id=>!p.assets.find(a=>a.id===id&&a.status==='confirmed'&&!a.sourceReview)))problems.push('所选资产缺失、未确认或待复核');if(!locate(p,g))problems.push('原文定位失效');const i=s.segments.indexOf(g);if(i>0&&(!s.segments[i-1].reviewed||s.segments[i-1].stale))problems.push('前一片段未审核');problems.push(...continuity(s,g,p));try{context(p,s,g,[]);}catch(e){problems.push(e.message);}const blocking=p.comments.filter(c=>c.blocking&&!c.resolved&&(!c.segmentId||c.segmentId===g.id));if(blocking.length)problems.push(`还有${blocking.length}条阻断性审稿意见`);return [...new Set(problems)];}
function invalidateAfter(s,index,reason){old.invalidateAfter(s,index,reason);for(let i=index+1;i<s.segments.length;i++){s.segments[i].stageStart=C.clone(s.segments[i-1]?.stageEnd||[]);s.segments[i].reviewStatus='draft';}}
function timing(p,g){const rate=Number(p.brief?.speechRate),unit=p.brief?.speechUnit||'none',warnings=[];let uncalibrated=false;g.shots.forEach((sh,i)=>{const speech=String(sh.voice||'').trim();if(/^(无|无对白|无人声|无台词|无语言|静默|none|silent|no dialogue|no speech)[。.!\s]*$/i.test(speech))return;const quoted=[...speech.matchAll(/[“「『"]([^”」』"]+)[”」』"]/g)].map(x=>x[1]).join(' ');const content=quoted||speech;if(!content)return;if(!['characters','words'].includes(unit)||!(rate>0)){uncalibrated=true;return;}const count=unit==='characters'?[...content.replace(/[\s\p{P}\p{S}]/gu,'')].length:(content.match(/[\p{L}\p{N}]+(?:['’’-][\p{L}\p{N}]+)*/gu)||[]).length;if(unit==='words'&&/[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Thai}]/u.test(content)){warnings.push(`镜${i+1}含不适合简单分词估算的文字，请按实际配音核对时长`);return;}if(count/rate>Number(sh.duration))warnings.push(`镜${i+1}人声约需${(count/rate).toFixed(1)}秒，超过镜头${sh.duration}秒（按自定每秒${rate}${unit==='characters'?'字':'词'}粗估，不含表演停顿）`);});if(uncalibrated)warnings.push('人声时长尚未校准：请按剧本语言与实际配音核对，或在叙事与声音中设置估算单位和速度。');if(p.selectedProfile==='mv'&&Number(p.brief?.bpm)>0){const beat=60/Number(p.brief.bpm);warnings.push(`音乐节拍${beat.toFixed(3)}秒；本片段约${(g.duration/beat).toFixed(1)}拍，请核对实际音乐起点`);}return warnings;}
function promptText(s,g,p){const assets=p.assets.filter(a=>s.assetIds.includes(a.id));return old.promptText(s,g,p)+'\n\n逐镜表演与交接：\n'+g.shots.map((sh,i)=>'镜'+(i+1)+' · 人物反应：'+(sh.reactions||'待补充')+'；动作状态变化：'+(sh.transition||'待补充')+'；轴线侧：'+(sh.axisSide||'未设')+'；过渡：'+(sh.axisReason||'同侧保持')).join('\n')+'\n\n固定资产锚点（不得改变）：\n'+assets.map(a=>`[${a.id} v${a.revision}] ${a.name}\n${a.design}\n${a.continuity}\n场次版本：${a.variants||'遵守当前固定设计'}\n参考：${a.references.map(r=>r.name).join('、')||'未绑定'}`).join('\n\n')+'\n\n结构化首尾状态：\n'+JSON.stringify({start:g.stageStart,end:g.stageEnd},null,2)+'\n\n生成辅助方案，请人工检查；文本审核不等于成片审核。';}
function compile(p,s,g){const adapter={...modelFor(p),...(p.adapterSettings||{})};if(adapter.aspects&&!adapter.aspects.includes(p.aspect))throw Error(`${adapter.name}不支持${p.aspect}画幅，请在项目设置中选择${adapter.aspects.join(' / ')}`);const tasks=[];const anchors=p.assets.filter(a=>s.assetIds.includes(a.id)).map(a=>({id:a.id,name:a.name,revision:a.revision,design:a.design,continuity:a.continuity,variants:a.variants,references:a.references.map(r=>({id:r.id,name:r.name}))}));g.shots.forEach((sh,i)=>{const seconds=Number(sh.duration);if(Number.isFinite(adapter.max)&&seconds>adapter.max)throw Error(`镜${i+1}超过适配时长${adapter.max}秒，请先拆镜后交付`);const generateDuration=adapter.durations?.find(x=>x>=seconds);if(adapter.durations&&!generateDuration)throw Error(`镜${i+1}没有适用的生成时长档位，请拆镜或调整适配方案`);const prompt=p.adapter==='runway4'?`主体运动：${sh.action}。自然反应：${sh.reactions}。摄影机运动：${sh.motion}。动作进程：${sh.transition}。保持参考图中的人物与空间。`: `场景：${sh.scene}。构图机位：${sh.camera}，${sh.frame}。动作：${sh.action}。人物反应：${sh.reactions}。运镜：${sh.motion}。对白：${sh.voice}。声音：${sh.sound}。连续动作：${sh.transition}。`;
tasks.push({id:`${g.id}_shot_${i+1}`,shot:i+1,editDuration:seconds,generateDuration:generateDuration||seconds,prompt,referenceRequired:adapter.reference,referenceIds:anchors.flatMap(a=>a.references.map(r=>r.id)),startState:sh.stateIn,endState:sh.stateOut,anchors,notes:generateDuration&&generateDuration!==seconds?`生成${generateDuration}秒后剪取${seconds}秒，重新核对剪切点动作状态`:'按镜头时长生成并核对结果'});});return {adapter:adapter.name,verifiedAt:adapter.unverified?null:'2026-10-05',source:adapter.source,aspect:p.aspect,tasks,warnings:[...timing(p,g),...(adapter.reference&&!anchors.some(a=>a.references.length)?['当前没有参考图，图生视频任务无法直接执行']:[]),...(p.adapter==='runway45'&&p.aspect!=='16:9'?['Runway Gen-4.5 非16:9画幅需使用图生视频并核对参考图裁剪。']:[]),...(adapter.unverified?['自定义模型的画幅与时长尚未核对；30 秒仅为观澜交付占位上限，请按目标平台重设。']:[])],disclosure:'AI辅助制作方案，未自动调用视频生成服务。'};}
function dependencyStamp(p,s,g){return hash(JSON.stringify({script:p.sourceFingerprint,narrativeMode:p.narrativeMode||'drama',allowInnerVoice:!!p.allowInnerVoice,voiceLanguage:p.voiceLanguage||'保持原文语言',languagePolicy:p.languagePolicy||'source',style:p.style,notes:p.notes,brief:p.brief,profile:p.selectedProfile,assets:p.assets.filter(a=>s.assetIds.includes(a.id)).map(a=>({id:a.id,revision:a.revision,design:a.design,continuity:a.continuity,variants:a.variants,aliases:a.aliases,refs:a.references.map(r=>[r.id,r.name])})),facts:p.facts,rules:p.rules,knowledge:p.knowledgeOverrides,knowledgeRevision:p.knowledgeRevision||0,source:g.sourceText,axis:s.axis,start:g.stageStart,end:g.stageEnd,shots:g.shots,duration:g.duration}));}
const baseAudit=audit;
Object.assign(C,{normalize,hash,units,locate,diff,touch,scriptChanged,addProposal,factText,activeRules,context,canonical,stateErrors,continuity,validate,audit:(p,s,g)=>{const errors=baseAudit(p,s,g);if(g.reviewed&&g.basisFingerprint&&g.basisFingerprint!==C.dependencyStamp(p,s,g))errors.push('审核依据已经变化，必须重新核对后确认');return errors;},dependencyStamp,invalidateAfter,timing,promptText,compile,actorFields,genres,adapters,modelFor});return C;
});
