const EXPERIENCE={back:[],forward:[],current:null,replay:false,dialogs:[],restoring:false,personalDraft:null};
WS_PAGES.film='拉片学习';icons.film='M3 4h18v16H3z M7 4v16 M17 4v16 M3 9h4 M3 15h4 M17 9h4 M17 15h4';
const systemColors=matchMedia('(prefers-color-scheme: dark)');
function colorRGB(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));}
function appearanceApply(p){const theme=p.theme==='system'?(systemColors.matches?'dark':'light'):(p.theme||'dark');WS.preferences.theme=theme;WS.preferences.density=p.density||WS.preferences.density;wsPrefs();document.querySelector('.brand-mark')?.setAttribute('src',theme==='light'?'assets/brand/guanlan-mark-light.svg':'assets/brand/guanlan-mark-dark.svg');const root=document.documentElement,accent=/^#[a-f\d]{6}$/i.test(p.accent||'')?p.accent:'#75bcae',rgb=colorRGB(accent),light=rgb[0]*.299+rgb[1]*.587+rgb[2]*.114;root.style.setProperty('--brand',theme==='dark'&&light<110?'color-mix(in srgb, '+accent+' 60%, white)':theme==='light'&&light>180?'color-mix(in srgb, '+accent+' 60%, black)':accent);root.style.setProperty('--on-brand',theme==='dark'&&light<110||theme==='light'&&light>180?'#ffffff':light>145?'#10231f':'#ffffff');root.style.setProperty('--focus','var(--brand)');root.style.setProperty('--soft','color-mix(in srgb, var(--brand) 16%, var(--bg))');root.style.setProperty('--selected','var(--soft)');root.style.setProperty('--panel-alpha',((Math.max(94,Math.min(100,p.opacity??100)))/100).toString());root.style.setProperty('--personal-blur',Math.max(0,Math.min(4,p.blur||0))+'px');root.style.setProperty('--wallpaper-alpha',((Math.max(0,Math.min(12,p.backgroundOpacity||0)))/100).toString());root.style.setProperty('--wallpaper',p.background?'url("'+p.background+'")':'none');if(/^#[a-f\d]{6}$/i.test(p.surface||''))root.style.setProperty('--surface','color-mix(in srgb, '+p.surface+' 18%, '+(theme==='dark'?'#20242a':'#f8f9fa')+')');else root.style.removeProperty('--surface');document.body.classList.toggle('personal-wallpaper',!!p.background);document.body.classList.toggle('nav-collapsed',!!p.sidebarCollapsed);if(p.assetMode)WS.assetMode=p.assetMode;}
applyPersonal=function(p){p={...p,theme:p.theme||'dark'};PRODUCT.personal=p;appearanceApply(p);};systemColors.addEventListener('change',()=>{if(PRODUCT.personal.theme==='system')appearanceApply(PRODUCT.personal);});
function personalValues(){const old=EXPERIENCE.personalDraft||PRODUCT.personal;return {...old,name:$('person-name')?.value??old.name,studio:$('person-studio')?.value??old.studio,role:$('person-role')?.value??old.role,bio:$('person-bio')?.value??old.bio,theme:$('person-theme')?.value||old.theme||'system',density:$('person-density')?.value||old.density||'standard',scale:Number($('person-scale')?.value||old.scale||100),home:$('person-home')?.value||old.home||'home',assetMode:$('person-assets')?.value||old.assetMode||'list',accent:$('person-accent')?.value||old.accent||'#75bcae',surface:$('person-surface')?.value||old.surface||'',opacity:Number($('person-opacity')?.value||old.opacity||100),backgroundOpacity:Number($('person-bg-opacity')?.value??old.backgroundOpacity??0),blur:Number($('person-blur')?.value??old.blur??0)};}
personalCenter=async function(draft=null){const p=draft||await call('personal:get');EXPERIENCE.personalDraft=p;showModal('个人中心与外观',`<div class="personal-identity">${p.avatar?`<img class="personal-avatar" src="${esc(p.avatar)}" alt="个人头像">`:'<span class="personal-avatar avatar-letter">'+esc((p.name||'导演').slice(0,1))+'</span>'}<div><strong>${esc(p.name||'我的创作空间')}</strong><div class="toolbar">${btn('更换头像','personal-avatar')}${p.avatar?btn('移除','personal-avatar-clear'):''}</div></div></div><div class="grid">${inputHtml('person-name','名称',p.name||'')}${inputHtml('person-studio','工作室',p.studio||'')}${inputHtml('person-role','创作身份',p.role||'')}</div><details><summary>个人简介</summary>${area('person-bio','简介',p.bio||'')}</details><h3>工作区外观</h3><div class="grid"><label>颜色模式<select id="person-theme">${opts({system:'跟随系统',dark:'暗色',light:'浅色'},p.theme||'system')}</select></label><label>主题强调色<input type="color" id="person-accent" value="${esc(p.accent||'#75bcae')}"></label><label>面板色调<input type="color" id="person-surface" value="${esc(p.surface||'#20242a')}"></label><label>面板不透明度<input type="range" id="person-opacity" min="94" max="100" value="${p.opacity??100}"></label></div><div class="toolbar">${btn('选择背景图片','personal-background')}${p.background?btn('移除背景','personal-background-clear'):''}${btn('恢复默认外观','personal-reset')}</div>${p.background?`<img class="wallpaper-preview" src="${esc(p.background)}" alt="背景图片预览">`:''}<div class="grid"><label>背景显现程度<input type="range" id="person-bg-opacity" min="0" max="12" value="${p.backgroundOpacity||0}"></label><label>毛玻璃模糊<input type="range" id="person-blur" min="0" max="4" value="${p.blur||0}"></label></div><p class="muted">透明效果只在软件内部叠加背景图，不会透出其他程序。面板不透明度限制在94%—100%，背景显现最多12%，模糊最多4px，预览图不加滤镜。设置保存后生效。</p><details><summary>更多偏好 · 布局、显示、启动</summary><div class="grid"><label>密度<select id="person-density">${opts({standard:'标准',compact:'紧凑'},p.density||'standard')}</select></label><label>界面缩放<select id="person-scale">${opts({90:'90%',100:'100%',110:'110%',125:'125%'},p.scale||100)}</select></label><label>启动页<select id="person-home">${opts({dashboard:'首页',assets:'视觉资产',workbench:'镜头工作区',film:'拉片学习'},p.home==='home'?'dashboard':p.home||'dashboard')}</select></label><label>资产视图<select id="person-assets">${opts({list:'列表',grid:'缩略图'},p.assetMode||'list')}</select></label></div></details><p class="muted">头像、背景和个人资料仅保存在本机。默认暗色，也可跟随系统或自选。主题色会适度调整明暗以便阅读。</p><div class="toolbar">${btn('模型中心','settings')}${btn('使用指南','help')}${btn('意见反馈','product-feedback')}${btn('关于与版本','about')}</div>`,async()=>{applyPersonal(await call('personal:save',personalValues()));render();toast('个人设置已保存');},true,'保存设置');};
function routeSnapshot(){return {page:S.page,project:S.project?.id,asset:S.assetId,seq:S.seqId,tab:WS.tab,param:WS.param,view:WS.view,film:FILM.selected,shot:FILM.shot,wsShot:S.project?WS.selected[S.project.id]:null,dwShot:DWUI.selected,help:HELP.chapter,query:DWUI.query,status:DWUI.status,scroll:document.querySelector('main')?.scrollTop||0};}
function routeKey(r){return [r?.project,r?.page,r?.page==='assets'?r.asset:r?.page==='shots'?r.seq:r?.page==='film'?r.film:r?.page==='workbench'?[r.view]:r?.page==='guide'?r.help:''].join(':');}
function routeRender(){const now=routeSnapshot();if(!EXPERIENCE.replay&&EXPERIENCE.current&&routeKey(now)!==routeKey(EXPERIENCE.current)){EXPERIENCE.back.push(EXPERIENCE.current);EXPERIENCE.back=EXPERIENCE.back.slice(-50);EXPERIENCE.forward=[];}EXPERIENCE.current=now;const bar=$('ws-stage-nav');if(bar){bar.insertAdjacentHTML('afterbegin',btn(icon('chevron-left'),'nav-back',`aria-label="返回上一页" title="返回上一页（Alt+←）" ${EXPERIENCE.back.length?'':'disabled'}`)+btn(icon('chevron-right'),'nav-forward',`aria-label="前进" title="前进（Alt+→）" ${EXPERIENCE.forward.length?'':'disabled'}`));bar.insertAdjacentHTML('beforeend','<nav class="top-stages" aria-label="顶部制作导航">'+[['home','剧本'],['assets','资产'],['shots','规划'],['workbench','镜头'],['review','审核'],['delivery','交付']].map(([page,label])=>btn(label,'page',`data-page="${page}" ${S.page===page?'aria-current="page"':''}`,S.page===page?'active':'')).join('')+'</nav>');}const nav=$('nav');nav.insertAdjacentHTML('beforeend',navItem('film','拉片学习'));nav.querySelectorAll('button').forEach(b=>{b.title=b.textContent.trim();b.setAttribute('aria-label',b.textContent.trim());});const brand=document.querySelector('.brand');if(brand&&!$('nav-collapse'))brand.insertAdjacentHTML('beforeend',btn(icon(PRODUCT.personal.sidebarCollapsed?'expand':'collapse'),'nav-collapse','id="nav-collapse" aria-label="展开或收起导航" title="展开或收起导航"'));else if($('nav-collapse'))$('nav-collapse').innerHTML=icon(PRODUCT.personal.sidebarCollapsed?'expand':'collapse');const person=document.querySelector('header [data-action="personal-center"]');if(person){person.innerHTML=(PRODUCT.personal.avatar?`<img class="header-avatar" src="${esc(PRODUCT.personal.avatar)}" alt="">`:`<span class="header-avatar header-avatar-fallback" aria-hidden="true">${esc((PRODUCT.personal.name||'我').slice(0,1))}</span>`)+`<span class="header-person-name">${esc(PRODUCT.personal.name||'个人中心')}</span>`;person.title='个人中心与外观';}document.querySelectorAll('.aside-bottom button').forEach(b=>{b.title=b.textContent;b.setAttribute('aria-label',b.textContent);});document.querySelector('.brand-mark')?.setAttribute('src',document.documentElement.dataset.theme==='light'?'assets/brand/guanlan-mark-light.svg':'assets/brand/guanlan-mark-dark.svg');}
const experienceRender=render;render=function(){experienceRender();routeRender();};
const originalModal=showModal;showModal=function(title,body,submit,wide,label){const dialog=$('modal');if(dialog.open&&!EXPERIENCE.restoring&&$('modal-title').textContent!==title){const container=document.createDocumentFragment();while($('modal-body').firstChild)container.append($('modal-body').firstChild);EXPERIENCE.dialogs.push({title:$('modal-title').textContent,nodes:container,submit:S.modalSubmit,label:$('modal-submit').textContent,wide:dialog.classList.contains('wide'),drawer:dialog.classList.contains('drawer')});}originalModal(title,body,submit,wide,label);modalBackButton();};
function modalBackButton(){if(!$('dialog-back'))$('modal').querySelector('.dialog-head').insertAdjacentHTML('afterbegin',btn('‹ 返回','dialog-back','id="dialog-back"'));$('dialog-back').hidden=!EXPERIENCE.dialogs.length;}
const originalClose=closeModal;closeModal=function(){originalClose();EXPERIENCE.dialogs=[];};
async function navigateHistory(direction){if(S.job||S.storageBusy)throw Error('请先完成或停止任务');const stack=direction==='back'?EXPERIENCE.back:EXPERIENCE.forward,other=direction==='back'?EXPERIENCE.forward:EXPERIENCE.back;if(!stack.length)return;await persist();const dest=stack.pop();if(dest.project&&!S.projects.some(x=>x.id===dest.project)){toast('原项目已不在当前资料库');return;}other.push(routeSnapshot());EXPERIENCE.replay=true;try{S.project=S.projects.find(x=>x.id===dest.project)||null;S.page=dest.page;S.assetId=dest.asset;S.seqId=dest.seq;Object.assign(WS,{tab:dest.tab,param:dest.param,view:dest.view});DWUI.view=dest.view==='flow'?'flow':'board';FILM.selected=dest.film;FILM.shot=dest.shot;if(S.project)WS.selected[S.project.id]=dest.wsShot;DWUI.selected=dest.dwShot;DWUI.query=dest.query||'';DWUI.status=dest.status||'all';HELP.chapter=dest.help||'start';render();document.querySelector('main').scrollTop=dest.scroll;}finally{EXPERIENCE.replay=false;}}
const experiencePersist=persist;persist=function(){return (FILM.timer?filmSave():FILM.saveChain).then(()=>experiencePersist());};
const experienceAct=act;act=async function(action,d={}){
 if(action==='nav-back'||action==='nav-forward')return navigateHistory(action==='nav-back'?'back':'forward');
 if(action==='dialog-back'){const state=EXPERIENCE.dialogs.pop();if(!state)return;EXPERIENCE.restoring=true;try{originalModal(state.title,'',state.submit,state.wide,state.label);$('modal-body').append(state.nodes);$('modal').classList.toggle('drawer',state.drawer);modalBackButton();}finally{EXPERIENCE.restoring=false;}return;}
 if(action==='nav-collapse'){const p={...PRODUCT.personal,sidebarCollapsed:!PRODUCT.personal.sidebarCollapsed};applyPersonal(await call('personal:save',p));render();return;}
 if(action==='personal-center'||action==='ws-appearance'){if(action==='ws-appearance'&&typeof U80!=='undefined')U80.settingsTab='appearance';return personalCenter();}
 if(action.startsWith('personal-')){if(S.job||S.storageBusy)throw Error('请等待任务完成');let p=personalValues();if(action==='personal-avatar'||action==='personal-background'){const data=await call('personal:image');if(!data)return;p[action==='personal-avatar'?'avatar':'background']=data;if(action==='personal-background'){p.backgroundOpacity=12;p.opacity=94;p.blur=4;}}if(action==='personal-avatar-clear')p.avatar='';if(action==='personal-background-clear')p.background='';if(action==='personal-reset')p={...p,theme:'dark',accent:'#75bcae',surface:'',opacity:100,backgroundOpacity:0,blur:0,background:''};return personalCenter(p);}
 if(action==='page'&&d.page==='film'&&!FILM.loaded)await filmLoad();
 if(S.page==='film'&&['page','help','guide-chapter','select-project'].includes(action))await filmSave();
 if(['page','help','guide-chapter','select-project'].includes(action)&&$('modal').open)closeModal();
 if(action==='ws-settings')return modelCenter('chat');
 return experienceAct(action,d);
};
$ ('modal').addEventListener('close',()=>{if(!$('modal').open)EXPERIENCE.dialogs=[];});
document.addEventListener('keydown',e=>{if(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();if($('modal').open){if(e.key==='ArrowLeft')act('dialog-back').catch(showError);}else act(e.key==='ArrowLeft'?'nav-back':'nav-forward').catch(showError);}});
document.addEventListener('keydown',e=>{
 if(!e.ctrlKey||e.altKey||e.shiftKey||e.defaultPrevented)return;
 if(e.key.toLowerCase()==='s'&&S.project){e.preventDefault();persist().then(()=>toast('项目已保存到本机')).catch(showError);return;}
 if(e.key.toLowerCase()==='k'&&S.project&&!$('modal').open){
  e.preventDefault();if(S.page==='home'){document.querySelector('.script-card textarea')?.focus();return;}
  if(S.page!=='workbench'){S.page='workbench';WS.view='studio';render();}
  const search=$('ws-query');if(search?.getClientRects().length){search.focus();search.select();return;}
  showModal('查找镜头',`<label>搜索场景、画面或动作<input id="quick-shot-query" value="${esc(DWUI.query)}"></label>`,async()=>{DWUI.query=$('quick-shot-query').value.trim();DWUI.status='all';render();},false,'查找');
 }
});
document.querySelector('main').addEventListener('scroll',()=>{if(EXPERIENCE.current)EXPERIENCE.current.scroll=document.querySelector('main').scrollTop;},{passive:true});
const libraryBoot=boot;boot=async function(){EXPERIENCE.back=[];EXPERIENCE.forward=[];EXPERIENCE.current=null;FILM.loaded=false;FILM.records=[];await libraryBoot();if(S.page==='film')await filmLoad();};


