const Zip=require('adm-zip'),Report=require('./film-report');
const M='http://schemas.openxmlformats.org/spreadsheetml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships',P='http://schemas.openxmlformats.org/package/2006/relationships';
const xml=v=>String(v??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])).slice(0,32767);
function col(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
function cell(v,j,i,style){const r=col(j)+i;return typeof v==='number'&&Number.isFinite(v)?`<c r="${r}" s="${style}"><v>${v}</v></c>`:`<c r="${r}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`;}
function sheet(rows,widths,o={}){const body=rows.map((entry,i)=>{const row=i+1,values=Array.isArray(entry)?entry:entry.values,style=Array.isArray(entry)?0:entry.style||0,ht=o.heights?.[row];return `<row r="${row}"${ht?` ht="${ht}" customHeight="1"`:''}>${values.map((v,j)=>cell(v,j,row,style)).join('')}</row>`;}).join('');
 const pane=o.freeze?`<pane xSplit="${o.freeze.x}" ySplit="${o.freeze.y}" topLeftCell="${col(o.freeze.x)}${o.freeze.y+1}" activePane="bottomRight" state="frozen"/>`:'';
 return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="${M}" xmlns:r="${R}"><sheetViews><sheetView workbookViewId="0" zoomScale="85">${pane}</sheetView></sheetViews><sheetFormatPr defaultRowHeight="23"/><cols>${widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData>${body}</sheetData>${o.merge?.length?`<mergeCells count="${o.merge.length}">${o.merge.map(ref=>`<mergeCell ref="${ref}"/>`).join('')}</mergeCells>`:''}${o.filter?`<autoFilter ref="${o.filter}"/>`:''}${o.drawing?'<drawing r:id="rId1"/>':''}${o.landscape?'<printOptions horizontalCentered="1"/><pageMargins left="0.25" right="0.25" top="0.45" bottom="0.45" header="0.2" footer="0.2"/><pageSetup orientation="landscape" paperSize="8" fitToWidth="2" fitToHeight="0"/>':''}</worksheet>`;}
function dimensions(b,t){if(t==='png'&&b.length>=24&&b.subarray(1,4).toString()==='PNG')return [b.readUInt32BE(16),b.readUInt32BE(20)];
 if(t==='webp'&&b.length>=30&&b.subarray(0,4).toString()==='RIFF'){const tag=b.subarray(12,16).toString();if(tag==='VP8X')return [1+b.readUIntLE(24,3),1+b.readUIntLE(27,3)];if(tag==='VP8 ')return [b.readUInt16LE(26)&0x3fff,b.readUInt16LE(28)&0x3fff];}
 if(t==='jpeg'&&b[0]===255&&b[1]===216){let i=2;while(i+9<b.length){if(b[i]!==255){i++;continue;}const marker=b[i+1];if(marker===216||marker===1){i+=2;continue;}if(marker===217||marker===218)break;const length=b.readUInt16BE(i+2);if(length<2||i+2+length>b.length)break;if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return [b.readUInt16BE(i+7),b.readUInt16BE(i+5)];i+=2+length;}}return null;}
function picture(data){const m=/^data:image\/(png|jpeg|webp);base64,([a-z0-9+/=\s]+)$/i.exec(data||'');if(!m)return null;const bytes=Buffer.from(m[2],'base64'),size=dimensions(bytes,m[1].toLowerCase());return size&&size[0]>0&&size[1]>0?{ext:m[1].toLowerCase(),bytes,size}:null;}
function rowHeight(s,hasImage){const fields=[[s.observation,46],[s.performance,34],[s.composition,32],[s.movement,32],[s.subtitle,28],[s.editing,36],[s.purpose,39],[s.transfer,42],[s.uncertainty,33],[s.analysis,48]];const lines=Math.max(1,...fields.map(([value,width])=>String(value||'').split('\n').reduce((sum,line)=>sum+Math.max(1,Math.ceil([...line].reduce((n,c)=>n+(/[^\x00-\x7f]/.test(c)?2:1),0)/(width-3))),0)));return Math.min(400,Math.max(hasImage?118:55,lines*18+18));}
module.exports=function(study){const zip=new Zip(),put=(name,v)=>zip.addFile(name,Buffer.isBuffer(v)?v:Buffer.from(v,'utf8')),shots=study.shots||[],review=study.reviewed?'已人工复核':'草稿，待人工复核';
 const overview=[{style:2,values:['观澜 · 拉片学习工作簿','']},{style:3,values:['片名',study.name||'未命名']},['原片文件',study.sourceName||'未记录'],['镜头数',shots.length],['分析范围（秒）',Number(shots.reduce((sum,s)=>sum+Math.max(0,s.end-s.start),0).toFixed(3))],['自动拆镜依据',study.detection?`${study.detection.method}；${study.detection.sampleInterval}秒/采样；${study.detection.cutCount}个候选切点${study.detection.uncertain?'；短镜头可能漏检':''}`:'未使用或未记录'],['AI 分析进度',study.analysisRun?`${study.analysisRun.done}/${study.analysisRun.total} 镜 · ${study.analysisRun.state}`:'未记录'],['复核状态',review],['记录更新时间',study.updatedAt||study.createdAt||''],['整体叙事与节奏',study.summary||'待填写'],['结构段落复盘',study.structure||'待填写；可按时间段记录段落任务、信息变化和情绪变化。'],['可复用导演方法',study.methods||'待填写'],['适用条件与限制',study.limitations||'待填写'],['阅读说明','逐镜拉片页对应原片证据；结构复盘页按镜头顺序查看叙事作用；方法迁移页记录可借鉴内容。'],['证据边界','截图为稀疏采样，不代表完整运动；声音、字幕及未采样动作必须人工核对。原视频不在工作簿内。']];
 const headers=['镜号','原片截图','开始时间','结束时间','时长（秒）','画面内容与动作','人物表演与反应','景别／机位','构图／空间','拍摄／运镜','字幕／画面文字','剪辑／声音','光线／色彩','镜头作用与解释','可借鉴方法／边界','待核对项','AI 分析草稿（待复核）'];
 const detail=[{style:2,values:[`${study.name||'未命名'} · 逐镜拉片`]},{style:3,values:[`原片：${study.sourceName||'未记录'}　｜　${shots.length} 镜　｜　${review}`]},{style:3,values:['先看截图与可见动作，再读拍法和镜头作用；声音与运动需对照原片。AI 草稿不等于人工结论。']},[],{style:1,values:headers}];
 const heights={1:34,2:28,3:30,5:35},imageRels=[],anchors=[];
 for(const [i,s] of shots.entries()){const row=i+6,img=picture(s.frames?.[0]),cutNote=s.cut?`自动切点建议 ${Math.round(s.cut.confidence*100)}% · ${s.cut.reason}；请回看确认。`:'';detail.push({style:i%2?5:0,values:[i+1,img?`采样时间 ${s.frameTimes?.[0]!=null?Report.time(s.frameTimes[0]):'未记录'}`:'未提取关键帧',Report.time(s.start),Report.time(s.end),Number(Math.max(0,s.end-s.start).toFixed(3)),s.observation||'',s.performance||'',s.size||'',s.composition||'',s.movement||'',s.subtitle||'',[s.editing,s.sound].filter(Boolean).join('\n'),s.light||'',s.purpose||'',s.transfer||'',[cutNote,s.uncertainty].filter(Boolean).join('\n'),s.analysis||'']});heights[row]=rowHeight(s,!!img);if(!img)continue;
  const n=imageRels.length+1,{size,ext,bytes}=img;put(`xl/media/image${n}.${ext}`,bytes);imageRels.push(`<Relationship Id="rId${n}" Type="${R}/image" Target="../media/image${n}.${ext}"/>`);
  const scale=Math.min(174/size[0],126/size[1]),w=Math.round(size[0]*scale),h=Math.round(size[1]*scale),x=Math.round((180-w)/2)*9525,y=Math.round((138-h)/2)*9525;
  anchors.push(`<xdr:oneCellAnchor><xdr:from><xdr:col>1</xdr:col><xdr:colOff>${x}</xdr:colOff><xdr:row>${row-1}</xdr:row><xdr:rowOff>${y}</xdr:rowOff></xdr:from><xdr:ext cx="${w*9525}" cy="${h*9525}"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="${n}" name="镜${i+1}关键帧"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip r:embed="rId${n}"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor>`);}
 if(!shots.length)detail.push(['尚未拆镜；请先在观澜拉片学习页添加镜头并补充关键帧。']);
 const structure=[{style:2,values:['结构复盘']},{style:3,values:['按镜头顺序核对叙事任务；段落划分以人工填写的结构复盘为准。']},['人工结构笔记',study.structure||'待填写'],[],{style:1,values:['镜号','时间范围','时长（秒）','可见动作','镜头作用','剪辑与接续','人物反应','声音记录','待核对']}];
 for(const [i,s] of shots.entries())structure.push([i+1,`${Report.time(s.start)}—${Report.time(s.end)}`,Number(Math.max(0,s.end-s.start).toFixed(3)),s.observation||'',s.purpose||'',s.editing||'',s.performance||'',s.sound||'',s.uncertainty||'']);
 const methods=[{style:2,values:['方法迁移']},{style:3,values:['只迁移经过核对的导演方法；不要自动复制参考片的剧情、台词或镜头顺序。']},['整体方法',study.methods||'待填写'],['适用边界',study.limitations||'待填写'],[],{style:1,values:['镜号','原片时间','原片证据','可借鉴方法','镜头作用','限制与待核对']}];
 for(const [i,s] of shots.entries())methods.push([i+1,`${Report.time(s.start)}—${Report.time(s.end)}`,s.observation||'',s.transfer||'',s.purpose||'',s.uncertainty||'']);
 const sheets=[['影片概况',sheet(overview,[26,102],{heights:{1:34},merge:['A1:B1']})],['逐镜拉片',sheet(detail,[8,27,14,14,11,46,34,22,32,32,28,36,28,39,42,33,48],{heights,merge:['A1:Q1','A2:Q2','A3:Q3'],freeze:{x:2,y:5},filter:`A5:Q${Math.max(5,shots.length+5)}`,drawing:!!anchors.length,landscape:true})],['结构复盘',sheet(structure,[9,29,13,49,43,38,36,35,33],{heights:{1:34,2:30,3:70,5:32},merge:['A1:I1','A2:I2','B3:I3'],freeze:{x:0,y:5},filter:`A5:I${Math.max(5,shots.length+5)}`})],['方法迁移',sheet(methods,[9,29,54,52,45,40],{heights:{1:34,2:30,3:70,4:70,6:32},merge:['A1:F1','A2:F2','B3:F3','B4:F4'],freeze:{x:0,y:6},filter:`A6:F${Math.max(6,shots.length+6)}`})]];
 put('[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Default Extension="jpeg" ContentType="image/jpeg"/><Default Extension="webp" ContentType="image/webp"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}${anchors.length?'<Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/>':''}</Types>`);
 put('_rels/.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="${P}"><Relationship Id="rId1" Type="${R}/officeDocument" Target="xl/workbook.xml"/></Relationships>`);
 put('xl/workbook.xml',`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="${M}" xmlns:r="${R}"><sheets>${sheets.map(([name],i)=>`<sheet name="${xml(name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`);
 put('xl/_rels/workbook.xml.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="${P}">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="${R}/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="${R}/styles" Target="styles.xml"/></Relationships>`);
 put('xl/styles.xml',`<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="${M}"><fonts count="4"><font><sz val="11"/><name val="Microsoft YaHei"/><color rgb="FF25313B"/></font><font><b/><sz val="11"/><name val="Microsoft YaHei"/><color rgb="FFFFFFFF"/></font><font><b/><sz val="17"/><name val="Microsoft YaHei"/><color rgb="FF183C3F"/></font><font><sz val="10"/><name val="Microsoft YaHei"/><color rgb="FF57656D"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF28585A"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFF1F6F5"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border><left/><right/><top/><bottom/><diagonal/></border><border><left style="thin"><color rgb="FFD8E2E2"/></left><right style="thin"><color rgb="FFD8E2E2"/></right><top style="thin"><color rgb="FFD8E2E2"/></top><bottom style="thin"><color rgb="FFD8E2E2"/></bottom><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="6"><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1" applyAlignment="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="3" fillId="0" borderId="0" xfId="0" applyFont="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="3" borderId="1" xfId="0" applyFill="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`);
 sheets.forEach(([,content],i)=>put(`xl/worksheets/sheet${i+1}.xml`,content));
 if(anchors.length){put('xl/worksheets/_rels/sheet2.xml.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="${P}"><Relationship Id="rId1" Type="${R}/drawing" Target="../drawings/drawing1.xml"/></Relationships>`);put('xl/drawings/drawing1.xml',`<?xml version="1.0" encoding="UTF-8"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${R}">${anchors.join('')}</xdr:wsDr>`);put('xl/drawings/_rels/drawing1.xml.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="${P}">${imageRels.join('')}</Relationships>`);}
 return zip.toBuffer();
};
