const fs=require('node:fs/promises');
const os=require('node:os');
const path=require('node:path');
const dns=require('node:dns/promises');
const https=require('node:https');
const {isIP}=require('node:net');
const {spawn}=require('node:child_process');

const LIMIT=512*1024*1024;
function runtimePaths(){const home=process.resourcesPath&&process.defaultApp!==true?path.join(process.resourcesPath,'runtime'):path.join(__dirname,'..','vendor');const bundled=path.join(home,'yt-dlp.exe');return {downloader:require('node:fs').existsSync(bundled)?bundled:process.env.DIRECTOR_YTDLP_PATH||'yt-dlp',ffmpeg:path.join(home,'ffmpeg')};}
function extractUrl(input){const raw=String(input||'').trim(),match=raw.match(/https:\/\/[^\s<>"'，。]+/i);if(!match)throw Error('请粘贴以 https:// 开头的公开视频链接');return match[0].replace(/[）)\]】》；;,]+$/,'');}
function publicAddress(address){if(isIP(address)===4){const [a,b,c]=address.split('.').map(Number);return !(a===0||a===10||a===127||a>=224||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&b===168||a===100&&b>=64&&b<=127||a===198&&b>=18&&b<=19||a===192&&b===0&&c===0||a===192&&b===0&&c===2||a===198&&b===51&&c===100||a===203&&b===0&&c===113);}if(isIP(address)===6)return /^[23][0-9a-f]/i.test(address)&&!/^2001:db8:/i.test(address);return false;}
async function checkedUrl(raw){let url;try{url=new URL(raw);}catch{throw Error('视频链接格式无效');}if(url.protocol!=='https:'||url.port&&url.port!=='443'||url.username||url.password)throw Error('仅支持公开的 HTTPS 视频链接');const addresses=isIP(url.hostname)?[{address:url.hostname,family:isIP(url.hostname)}]:await dns.lookup(url.hostname,{all:true});if(!addresses.length||addresses.some(x=>!publicAddress(x.address)))throw Error('链接地址不是公网地址，无法导入');return {url,address:addresses[0]};}
function request(url,address){return new Promise((resolve,reject)=>{const req=https.get(url,{lookup:(_host,options,callback)=>options.all?callback(null,[address]):callback(null,address.address,address.family),headers:{'User-Agent':'Guanlan-Film-Study/1.0','Accept':'video/*,application/octet-stream,text/html;q=0.5'}},resolve);req.setTimeout(30000,()=>req.destroy(Error('连接视频来源超时')));req.on('error',reject);});}
function videoExt(url,type){const ext=path.extname(url.pathname).toLowerCase();if(['.mp4','.webm','.mov','.m4v'].includes(ext))return ext;if(/video\/webm/i.test(type))return '.webm';if(/video\/(quicktime|mov)/i.test(type))return '.mov';if(/video\/(mp4|m4v)/i.test(type))return '.mp4';return null;}
async function directDownload(raw,folder){let current=raw;for(let redirect=0;redirect<5;redirect++){const {url,address}=await checkedUrl(current),res=await request(url,address);if([301,302,303,307,308].includes(res.statusCode)){res.resume();if(!res.headers.location)throw Error('视频链接跳转缺少目标地址');current=new URL(res.headers.location,url).href;continue;}if(res.statusCode!==200){res.resume();if(res.statusCode>=400&&res.statusCode<500)return null;throw Error('视频来源返回 HTTP '+res.statusCode);}const type=String(res.headers['content-type']||''),ext=videoExt(url,type);if(!ext||/text\/html|application\/json/i.test(type)){res.resume();return null;}if(Number(res.headers['content-length'])>LIMIT){res.destroy();throw Error('在线视频超过 512MB，请先下载或裁剪后从本机导入');}const file=path.join(folder,'clip'+ext),handle=await fs.open(file,'w');let bytes=0;try{for await(const chunk of res){bytes+=chunk.length;if(bytes>LIMIT)throw Error('在线视频超过 512MB，请先裁剪后导入');await handle.write(chunk);}if(bytes<1024)throw Error('链接没有返回有效的视频内容');}catch(error){res.destroy();await handle.close();await fs.rm(file,{force:true});throw error;}await handle.close();return {file,title:decodeURIComponent(path.basename(url.pathname,ext))||url.hostname};}throw Error('视频链接跳转过多，请使用最终视频地址');}
async function pageDownload(url,folder){const runtime=runtimePaths(),executable=runtime.downloader;const args=['--ignore-config','--no-playlist','--max-downloads','1','--max-filesize','512M','--socket-timeout','20','--retries','1','--no-progress','--no-warnings','--ffmpeg-location',runtime.ffmpeg,'--merge-output-format','mp4','-f','bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/b[ext=webm]/b','-o',path.join(folder,'clip.%(ext)s'),'--print','before_dl:%(title)s','--',url];let output='';await new Promise((resolve,reject)=>{const child=spawn(executable,args,{cwd:folder,windowsHide:true,shell:false});const timeout=setTimeout(()=>{child.kill();reject(Error('链接解析超过 5 分钟，请检查网络或改用本机导入'));},300000);for(const stream of [child.stdout,child.stderr])stream.on('data',chunk=>{output=(output+chunk.toString()).slice(-8000);});child.on('error',e=>{clearTimeout(timeout);reject(e.code==='ENOENT'?Error('分享页解析组件缺失，请重新下载完整的观澜便携版，或导入本机视频。'):e);});child.on('close',code=>{clearTimeout(timeout);if(code===0)resolve();else reject(Error('分享页未能取得公开视频：'+(output.trim().split('\n').at(-1)||'请检查链接或改用本机导入').slice(0,300)));});});const names=(await fs.readdir(folder)).filter(x=>/^clip\.(mp4|webm|mov|m4v)$/i.test(x));if(names.length!==1)throw Error('分享页没有返回可播放视频；可先下载 MP4 再从本机导入');const file=path.join(folder,names[0]);if((await fs.stat(file)).size>LIMIT)throw Error('在线视频超过 512MB，请先裁剪后导入');const title=output.split(/\r?\n/).find(x=>x.trim()&&!/^\[/.test(x))?.trim()||new URL(url).hostname;return {file,title};}
async function helperVersion(){return new Promise(resolve=>{const child=spawn(runtimePaths().downloader,['--version'],{windowsHide:true,shell:false});let output='';const timer=setTimeout(()=>{child.kill();resolve(null);},5000);child.stdout.on('data',chunk=>output=(output+chunk.toString()).slice(0,100));child.on('error',()=>{clearTimeout(timer);resolve(null);});child.on('close',code=>{clearTimeout(timer);resolve(code===0?output.trim().slice(0,40):null);});});}
async function importLink(input,filmStore){const raw=extractUrl(input);await checkedUrl(raw);const folder=await fs.mkdtemp(path.join(os.tmpdir(),'guanlan-film-link-'));try{const result=await directDownload(raw,folder)||await pageDownload(raw,folder);const title=result.title.replace(/[\x00-\x1f<>:"/\\|?*]/g,' ').trim().slice(0,120)||'网络拉片';return await filmStore.importVideo(result.file,{title,sourceName:title+path.extname(result.file),sourceUrl:raw});}finally{await fs.rm(folder,{recursive:true,force:true});}}
module.exports={extractUrl,publicAddress,checkedUrl,runtimePaths,helperVersion,importLink};

