const crypto=require('node:crypto'),fs=require('node:fs/promises'),sync=require('node:fs'),path=require('node:path');
module.exports=({root,read,write,media})=>{
 const file=()=>path.join(root(),'film-studies.json');let chain=Promise.resolve();const serial=fn=>{const next=chain.catch(()=>{}).then(fn);chain=next;return next;};
 const list=()=>read(file(),[]);
 const save=input=>serial(async()=>{if(!/^film_[\w-]+$/.test(input.id))throw Error('无效拉片编号');const records=await list(),index=records.findIndex(x=>x.id===input.id);if(index<0)throw Error('拉片记录不存在');if(JSON.stringify(input).length>40*1024*1024)throw Error('拉片资料过大，请拆分片段');const value=await media({...input,sourceVideo:records[index].sourceVideo,sourcePath:records[index].sourcePath,sourceName:records[index].sourceName,sourceUrl:records[index].sourceUrl,updatedAt:new Date().toISOString()});records[index]=value;await write(file(),records);return value;});
 async function importVideo(source,meta={}){const stat=await fs.stat(source),ext=path.extname(source).toLowerCase();if(!['.mp4','.webm','.mov','.m4v'].includes(ext)||!stat.isFile())throw Error('请选择MP4、WebM或MOV视频');if(stat.size>512*1024*1024)throw Error('单个视频最多512MB，请先裁成需要学习的片段');const hash=crypto.createHash('sha256');for await(const chunk of sync.createReadStream(source))hash.update(chunk);const name=hash.digest('hex')+ext;await fs.mkdir(path.join(root(),'clips'),{recursive:true});const target=path.join(root(),'clips',name);await fs.copyFile(source,target,sync.constants.COPYFILE_EXCL).catch(e=>{if(e.code!=='EEXIST')throw e;});return serial(async()=>{const records=await list();const value={id:'film_'+crypto.randomUUID(),name:String(meta.title||path.basename(source,ext)).slice(0,120),sourceName:String(meta.sourceName||path.basename(source)).slice(0,200),sourceUrl:meta.sourceUrl||'',sourceVideo:'director-video://clip/'+name,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),duration:0,shots:[],summary:'',methods:'',tags:'',status:'draft'};records.unshift(value);await write(file(),records);return value;});}
 async function importLinked(source){const stat=await fs.stat(source),ext=path.extname(source).toLowerCase();if(!['.mp4','.webm','.mov','.m4v'].includes(ext)||!stat.isFile())throw Error('请选择可播放的视频');const id='film_'+crypto.randomUUID(),now=new Date().toISOString(),value={id,name:path.basename(source,ext),sourceName:path.basename(source),sourcePath:source,sourceVideo:'director-video://linked/'+id,createdAt:now,updatedAt:now,duration:0,shots:[],summary:'',methods:'',tags:'',status:'draft'};return serial(async()=>{const records=await list();records.unshift(value);await write(file(),records);return value;});}
 async function publish(id){const study=(await list()).find(s=>s.id===id);if(!study?.reviewed||!String(study.methods||'').trim())throw Error('请先填写导演方法并确认已审阅');const knowledgePath=path.join(root(),'knowledge.json'),all=await read(knowledgePath,[]),key='filmref_'+id;const value={id:key,name:'拉片参考 · '+study.name,source:'本机拉片 '+id,kind:'reference',builtin:false,enabledByDefault:false,stages:['analysis','assets','shots'],version:String(study.revision||1),importedAt:new Date().toISOString(),text:`【拉片学习参考，不能覆盖当前剧本事实】\n来源：${study.name}\n标签：${study.tags||''}\n导演方法：${study.methods}\n总体分析：${study.summary}\n适用边界：${study.limitations||'待核对'}\n可核对镜头：\n${study.shots.map((s,i)=>`${i+1}. ${s.start.toFixed(2)}–${s.end.toFixed(2)}秒：${s.observation||''}\n${s.analysis||''}\n${Object.entries(require('./film-report').fields).map(([k,n])=>s[k]?n+'：'+s[k]:'').filter(Boolean).join('\n')}`).join('\n')}`};const at=all.findIndex(x=>x.id===key);if(at>=0)all[at]=value;else all.push(value);await write(knowledgePath,all);return value;}
 async function restore(payload){if(payload?.format!=='guanlan-film-study'||![1,2].includes(payload.version)||!Array.isArray(payload.study?.shots)||payload.study.shots.length>300)throw Error('无效拉片分析资料');const s=payload.study;const textKeys=['name','sourceName','summary','structure','methods','tags','limitations','analyzedModel'];const value=Object.fromEntries(textKeys.map(k=>[k,String(s[k]||'').slice(0,100000)]));value.name=(value.name||'拉片资料')+'（导入）';Object.assign(value,{id:'film_'+crypto.randomUUID(),sourceVideo:'',duration:Math.max(0,Number(s.duration)||0),reviewed:false,revision:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});value.shots=s.shots.map(row=>{if(!Number.isFinite(row.start)||!Number.isFinite(row.end)||row.start<0||row.end<=row.start)throw Error('镜头时间无效');const r={id:'cut_'+crypto.randomUUID(),start:row.start,end:row.end};for(const k of ['observation','analysis','analysisModel',...Object.keys(require('./film-report').fields)])r[k]=String(row[k]||'').slice(0,100000);r.aiFields=Object.fromEntries(Object.keys(require('./film-report').fields).filter(k=>k!=='sound'&&typeof row.aiFields?.[k]==='string').map(k=>[k,row.aiFields[k].slice(0,100000)]));r.frames=(row.frames||[]).slice(0,4).filter(x=>/^data:image\/(png|jpeg|webp);base64,[a-z0-9+/=\s]+$/i.test(x));r.frameTimes=(row.frameTimes||[]).slice(0,r.frames.length).map(x=>Number.isFinite(x)?x:null);return r;});const embedded=await media(value);return serial(async()=>{const records=await list();records.unshift(embedded);await write(file(),records);return embedded;});}
 async function relink(id,source){if(!(await list()).some(x=>x.id===id))throw Error('拉片不存在');const stat=await fs.stat(source),linked=stat.size>512*1024*1024;if(linked){const ext=path.extname(source).toLowerCase();if(!stat.isFile()||!['.mp4','.webm','.mov','.m4v'].includes(ext))throw Error('请选择可播放的视频');return serial(async()=>{const records=await list(),study=records.find(x=>x.id===id);if(!study)throw Error('拉片不存在');study.sourceVideo='director-video://linked/'+id;study.sourcePath=source;study.sourceName=path.basename(source);study.reviewed=false;study.updatedAt=new Date().toISOString();await write(file(),records);return study;});}const added=await importVideo(source);return serial(async()=>{const records=await list(),study=records.find(x=>x.id===id);if(!study)throw Error('拉片不存在');study.sourceVideo=added.sourceVideo;study.sourceName=added.sourceName;delete study.sourcePath;study.reviewed=false;study.updatedAt=new Date().toISOString();await write(file(),records.filter(x=>x.id!==added.id));return study;});}
 return {list,save,importVideo,importLinked,publish,restore,relink};
};
