const {app,BrowserWindow,ipcMain,dialog,safeStorage,clipboard,shell,protocol}=require('electron');
const path=require('node:path'),fs=require('node:fs/promises'),crypto=require('node:crypto');
const AdmZip=require('adm-zip'),C=require('./performance');require('./director-workspace').install(C);
let feedbackEmail='';try{const value=require('./private-feedback.json').email;if(typeof value==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))feedbackEmail=value;}catch{}
// Keep the legacy internal name and appId so existing userData and storage-location settings remain accessible.
app.setName('ai-director-desk');
if(process.env.DIRECTOR_DATA_DIR)app.setPath('userData',path.resolve(process.env.DIRECTOR_DATA_DIR));
const locations=require('./data-location')(app.getPath('userData'));
const root=()=>locations.root();
async function importClip(source,ext){const h=crypto.createHash('sha256');for await(const chunk of require('node:fs').createReadStream(source))h.update(chunk);const hash=h.digest('hex'),dir=path.join(root(),'clips'),target=path.join(dir,hash+ext);await fs.mkdir(dir,{recursive:true});try{await fs.access(target);}catch{await fs.copyFile(source,target);}return 'director-video://clip/'+hash+ext;}
const usageStore=require('./usage-store')(root);
protocol.registerSchemesAsPrivileged([{scheme:'director-video',privileges:{standard:true,secure:true,supportFetchAPI:true,corsEnabled:true,stream:true}},{scheme:'director-media',privileges:{standard:true,secure:true,supportFetchAPI:true}}]);
let storage;const store=()=>storage||(storage=require('./storage')(root()));
let win,locationChanging=false,activeCalls=0,locationChoice;const requests=new Map(),writes=new Map();
async function read(file,fallback){try{return JSON.parse(await fs.readFile(file,'utf8'));}catch(e){if(e.code==='ENOENT')return fallback;throw Error(`资料读取失败，原文件保留：${path.basename(file)}`);}}
async function write(file,data){const task=(writes.get(file)||Promise.resolve()).catch(()=>{}).then(async()=>{await fs.mkdir(path.dirname(file),{recursive:true});const temp=file+'.tmp';await fs.writeFile(temp,JSON.stringify(data,null,2),'utf8');try{await fs.copyFile(file,file+'.bak');}catch(e){if(e.code!=='ENOENT')throw e;}await fs.rename(temp,file);});writes.set(file,task);try{await task;}finally{if(writes.get(file)===task)writes.delete(file);}}
const validId=id=>{if(!/^p_[\w-]+$/.test(id))throw Error('无效项目编号');return id;};
async function settings(){const s=await read(path.join(root(),'settings.json'),{});if(s.encryptedKey){try{s.apiKey=safeStorage.decryptString(Buffer.from(s.encryptedKey,'base64'));}catch{s.apiKey='';}}return s;}
async function modules(){const core=[...await read(path.join(__dirname,'builtin-knowledge.json'),[]),...await read(path.join(__dirname,'builtin-course.json'),[])];const personal=await read(path.join(root(),'knowledge.json'),[]);return [...core.map(k=>({...k,builtin:true,scope:'core'})),...personal.map(k=>({...k,builtin:false,scope:'personal'}))];}
async function documentText(file,buffer){const ext=path.extname(file).toLowerCase(),data=buffer||await fs.readFile(file);if(data.length>40*1024*1024)throw Error('文档超过 40MB，请拆分后导入');
 if(ext==='.docx')return require('./docx-text').extract(data);
 if(ext==='.pdf'){const pdf=await import('pdfjs-dist/legacy/build/pdf.mjs');const loadingTask=pdf.getDocument({data:new Uint8Array(data),useSystemFonts:true,isEvalSupported:false});try{const doc=await loadingTask.promise;const pages=[];for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n);pages.push((await page.getTextContent()).items.map(x=>x.str||'').join(' '));}const text=pages.join('\n\n');if(text.trim().length<20)throw Error('该 PDF 没有可提取文本，请先进行 OCR');return text;}finally{await loadingTask.destroy();}}
 if(ext==='.srt')return require('./script-import').subtitleToScript(data.toString('utf8'));
 if(!['.txt','.md','.json','.yaml','.yml'].includes(ext))throw Error('支持 TXT、Markdown、SRT、DOCX 和文字型 PDF');return data.toString('utf8').replace(/^\uFEFF/,'');}
function endpoint(s){const local=s.provider==='local',url=new URL((local?(s.localUrl||'http://localhost:11434/v1'):(s.baseUrl||'https://dashscope.aliyuncs.com/compatible-mode/v1')).replace(/\/$/,''));if(!['https:','http:'].includes(url.protocol))throw Error('API 地址必须是 HTTP 或 HTTPS');if(url.protocol==='http:'&&!['localhost','127.0.0.1','[::1]'].includes(url.hostname))throw Error('远程云端 API 请使用 HTTPS');return {base:url.href.replace(/\/$/,''),key:s.apiKey||'',local};}
function register(name,handler){ipcMain.handle(name,async(event,...args)=>{if(locationChanging&&name!=='storage:info')throw Error('资料迁移中，请稍候');if(!name.startsWith('storage:')&&!['app:close','app:info','projects:rescue','model:cancel','clipboard:copy'].includes(name))await locations.ready();if(locationChanging&&name!=='storage:info')throw Error('资料迁移中，请稍候');activeCalls++;try{return await handler(...args,event);}finally{activeCalls--;}});}
const modelHub=require('./model-hub')({root,path,read,write,safeStorage});
const videoGeneration=require('./video-generation')({root,read,write,safeStorage});
register('video:config',()=>videoGeneration.publicConfig());
register('video:config:save',input=>videoGeneration.saveConfig(input));
register('video:list',projectId=>videoGeneration.list(projectId));
register('video:submit',input=>videoGeneration.submit(input));
register('video:poll',id=>videoGeneration.poll(id));
register('connections:list',()=>modelHub.list());
register('connections:save',input=>modelHub.save(input));
register('connections:activate',id=>modelHub.activate(id));
register('connections:remove',id=>modelHub.remove(id));
register('image:generate',async input=>{const config=await modelHub.imageSettings();if(input.connectionId&&config.id!==input.connectionId)throw Error('生图连接已变化，请重新确认生成');return require('./image-client').generate(config,input,requests,value=>store().media(value));});
register('image:export',async ref=>{if(!/^director-media:\/\/image\/[a-f0-9]{64}\.(png|jpeg|webp)$/.test(ref.data||''))throw Error('请选择已保存的图片');const source=new URL(ref.data).pathname.slice(1);const result=await dialog.showSaveDialog(win,{defaultPath:'观澜-资产图.'+source.split('.').at(-1)});if(result.canceled)return null;await fs.copyFile(path.join(root(),'media',source),result.filePath);return result.filePath;});
const filmStore=require('./film-store')({root,read,write,media:value=>store().media(value)});
register('film:list',()=>filmStore.list());
register('film:save',input=>filmStore.save(input));
register('film:publish',id=>filmStore.publish(id));
register('film:import',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'参考片段',extensions:['mp4','webm','mov','m4v']}]});if(r.canceled)return null;const file=r.filePaths[0],stat=await fs.stat(file);return stat.size>512*1024*1024?filmStore.importLinked(file):filmStore.importVideo(file);});
register('film:importLink',input=>require('./film-link').importLink(input,filmStore));
register('film:linkSupport',()=>require('./film-link').helperVersion());
register('film:export',async input=>{const id=typeof input==='string'?input:input.id,format=typeof input==='string'?'html':input.format;const study=(await filmStore.list()).find(x=>x.id===id);if(!study)throw Error('拉片不存在');return require('./film-export')({study,format,dialog,win,BrowserWindow,media:(v,e)=>store().media(v,e)});});
register('film:restore',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'拉片分析资料',extensions:['json']}]});if(r.canceled)return null;if((await fs.stat(r.filePaths[0])).size>45*1024*1024)throw Error('分析资料过大');return filmStore.restore(JSON.parse(await fs.readFile(r.filePaths[0],'utf8')));});
register('film:relink',async id=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'原片段',extensions:['mp4','webm','mov','m4v']}]});if(r.canceled)return null;return filmStore.relink(id,r.filePaths[0]);});
const previewFiles=new Map();
async function canvasVideoFile(id){if(!/^video_[\w-]+$/.test(String(id||'')))throw Error('视频任务编号无效');const job=(await videoGeneration.list()).find(x=>x.id===id);if(job?.status!=='succeeded'||!job.file?.path)throw Error('视频尚未生成完成');const folder=path.resolve(root(),'generated-videos'),file=path.resolve(job.file.path),relative=path.relative(folder,file);if(!relative||relative.startsWith('..')||path.isAbsolute(relative)||!/^video_[\w-]+\.mp4$/.test(path.basename(file)))throw Error('视频文件位置无效');await fs.access(file).catch(()=>{throw Error('生成文件已移动或丢失');});return file;}
register('video:preview',async id=>{const file=await canvasVideoFile(id),token=crypto.randomUUID();previewFiles.set(token,file);if(previewFiles.size>100)previewFiles.delete(previewFiles.keys().next().value);return 'director-video://result/'+token;});
register('video:export',async id=>{const file=await canvasVideoFile(id),choice=await dialog.showSaveDialog(win,{title:'导出画布生成视频',defaultPath:'观澜画布-'+id+'.mp4',filters:[{name:'MP4 视频',extensions:['mp4']}]});if(choice.canceled||!choice.filePath)return null;await fs.copyFile(file,choice.filePath);return choice.filePath;});
const diagnosisStore=require('./diagnosis-store')({root,read,write});
const assistantHistoryFile=()=>path.join(root(),'assistant-history.json');
function assistantHistory(input){if(!Array.isArray(input))throw Error('助手记录格式无效');return input.slice(-30).filter(x=>x&&['user','assistant'].includes(x.role)&&typeof x.text==='string').map(x=>({role:x.role,text:x.text.slice(0,6000),at:String(x.at||'').slice(0,40),guide:typeof x.guide==='string'?x.guide.slice(0,80):undefined}));}
register('assistant:history:get',async()=>assistantHistory(await read(assistantHistoryFile(),[])));
register('assistant:history:save',async input=>{const rows=assistantHistory(input);await write(assistantHistoryFile(),rows);return rows.length;});
const assistantConversations=require('./assistant-conversations');
const assistantConversationsFile=()=>path.join(root(),'assistant-conversations.json');
register('assistant:conversations:get',async()=>{const saved=await read(assistantConversationsFile(),null);return saved?assistantConversations.clean(saved):assistantConversations.migrateLegacy(await read(assistantHistoryFile(),[]));});
register('assistant:conversations:save',async input=>{const value=assistantConversations.clean(input);await write(assistantConversationsFile(),value);return value;});
const skillStore=require('./skill-store')({root,read,write});
register('skills:list',()=>skillStore.list());
register('skills:save',input=>skillStore.save(input));
register('skills:import',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'观澜技能',extensions:['md','zip']}]});return r.canceled?null:skillStore.importFile(r.filePaths[0]);});
register('skills:enable',({name,enabled})=>skillStore.setEnabled(name,enabled));
register('skills:remove',name=>skillStore.remove(name));
const assistantFilesPath=()=>path.join(root(),'assistant-files.json');
function assistantFileRows(value){return Array.isArray(value)?value.slice(0,20).filter(x=>x&&typeof x.id==='string'&&typeof x.name==='string'&&typeof x.text==='string').map(x=>({id:x.id.slice(0,80),name:x.name.slice(0,200),text:x.text.slice(0,100000),truncated:!!x.truncated,addedAt:String(x.addedAt||'').slice(0,40)})):[];}
register('assistant:files:list',async()=>assistantFileRows(await read(assistantFilesPath(),[])));
register('assistant:files:add',async()=>{const r=await dialog.showOpenDialog(win,{title:'添加给澜芯阅读的文件',properties:['openFile','multiSelections'],filters:[{name:'文本文档',extensions:['txt','md','docx','pdf']}]});if(r.canceled)return [];
 const current=assistantFileRows(await read(assistantFilesPath(),[])),added=[];if(r.filePaths.length+current.length>20)throw Error('最多保留 20 份助手文件');
 for(const file of r.filePaths){const st=await fs.stat(file);if(st.size>10*1024*1024)throw Error(path.basename(file)+' 超过 10MB');const text=(await documentText(file)).trim();if(!text)throw Error(path.basename(file)+' 没有可读取文字');added.push({id:crypto.randomUUID(),name:path.basename(file),text:text.slice(0,100000),truncated:text.length>100000,addedAt:new Date().toISOString()});}
 await write(assistantFilesPath(),[...current,...added]);return added.map(({id,name,truncated,addedAt})=>({id,name,truncated,addedAt}));});
register('assistant:files:remove',async id=>{const rows=assistantFileRows(await read(assistantFilesPath(),[]));await write(assistantFilesPath(),rows.filter(x=>x.id!==id));return true;});
register('diagnosis:list',()=>diagnosisStore.list());
register('diagnosis:import',async()=>{const result=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'待诊断短片',extensions:['mp4','webm','mov','m4v']}]});if(result.canceled)return null;return diagnosisStore.add(result.filePaths[0]);});
register('diagnosis:save',input=>diagnosisStore.save(input));
register('diagnosis:preview',async id=>{const record=(await diagnosisStore.list()).find(x=>x.id===id);if(!record)throw Error('诊断记录不存在');await fs.access(record.source).catch(()=>{throw Error('原视频已移动，请重新导入短片');});const token=crypto.randomUUID();previewFiles.set(token,record.source);return 'director-video://result/'+token;});
const studyLibrary=require('./study-library')({root,read,write,documentText});
register('study:list',()=>studyLibrary.list());
register('study:register',paths=>studyLibrary.register(paths));
register('study:choose',async()=>{const result=await dialog.showOpenDialog(win,{properties:['openDirectory','multiSelections'],title:'选择每日一镜期数文件夹'});return result.canceled?null:studyLibrary.register(result.filePaths);});
register('study:text',({id,relative})=>studyLibrary.text(id,relative));
register('study:image',({id,relative})=>studyLibrary.image(id,relative));
register('study:video',async({id,relative})=>{const {entry,file}=await studyLibrary.fileFor(id,relative);if(entry.kind!=='video')throw Error('请选择原片');const token=crypto.randomUUID();previewFiles.set(token,file);return 'director-video://result/'+token;});
register('study:makeFilm',async({id,relative})=>{const {entry,file}=await studyLibrary.fileFor(id,relative);if(entry.kind!=='video')throw Error('请选择原片');return filmStore.importLinked(file);});
register('study:open',async({id,relative})=>{const {file}=await studyLibrary.fileFor(id,relative),error=await shell.openPath(file);if(error)throw Error('无法打开原文件：'+error);return true;});
register('results:preview',async({projectId,resultId})=>{const p=(await store().list()).find(x=>x.id===projectId),result=p?.videoResults?.find(x=>x.id===resultId);if(!result)throw Error('请先保存成片记录');if(!/\.(mp4|mov|webm|m4v)$/i.test(result.file.path))throw Error('此记录不是可播放视频，请使用视频文件');await fs.access(result.file.path).catch(()=>{throw Error('原视频已移动，请重新关联成片');});const token=crypto.randomUUID();previewFiles.set(token,result.file.path);if(previewFiles.size>100)previewFiles.delete(previewFiles.keys().next().value);return 'director-video://result/'+token;});
register('personal:image',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'头像或背景图',extensions:['png','jpg','jpeg','webp']}]});if(r.canceled)return null;const data=await fs.readFile(r.filePaths[0]);if(data.length>8*1024*1024)throw Error('图片最多8MB');const ext=require('./image-client').imageType(data);return store().media('data:image/'+ext+';base64,'+data.toString('base64'));});
register('personal:bootVideo',async kind=>{const label=kind==='skin'?'皮肤背景视频':'启动视频';const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:label,extensions:['mp4','webm']}]});if(r.canceled)return null;const source=r.filePaths[0],stat=await fs.stat(source);if(stat.size>80*1024*1024)throw Error(label+'最多 80MB');const ext=path.extname(source).toLowerCase(),data=await fs.readFile(source),hash=crypto.createHash('sha256').update(data).digest('hex');await fs.mkdir(path.join(root(),'clips'),{recursive:true});await fs.writeFile(path.join(root(),'clips',hash+ext),data);return 'director-video://clip/'+hash+ext;});
register('canvas:import-media',async kind=>{if(!['audio','video'].includes(kind))throw Error('请选择音频或视频节点');const extensions=kind==='audio'?['mp3','wav','m4a']:['mp4','webm','mov','m4v'];const r=await dialog.showOpenDialog(win,{title:'导入画布'+(kind==='audio'?'音频':'视频'),properties:['openFile'],filters:[{name:kind==='audio'?'音频':'视频',extensions}]});if(r.canceled)return null;const source=r.filePaths[0],ext=path.extname(source).toLowerCase();if(!extensions.includes(ext.slice(1)))throw Error('文件格式与节点类型不匹配');const stat=await fs.stat(source),limit=kind==='audio'?100*1024*1024:512*1024*1024;if(!stat.isFile()||stat.size>limit)throw Error('素材过大或不是文件');const media=await importClip(source,ext);return {name:path.basename(source),media};});
register('personal:get',()=>read(path.join(root(),'personal.json'),{}));
register('personal:save',async input=>{const p=require('./personal-preferences')(input);await write(path.join(root(),'personal.json'),p);win.webContents.setZoomFactor(p.scale/100);return p;});
register('personal:apply',async()=>{const p=await read(path.join(root(),'personal.json'),{});win.webContents.setZoomFactor(([90,100,110,125].includes(p.scale)?p.scale:100)/100);return true;});
register('feedback:get',()=>read(path.join(root(),'feedback-draft.json'),{}));
register('feedback:save',async input=>{const p={type:String(input.type||'问题反馈').slice(0,40),title:String(input.title||'').slice(0,120),body:String(input.body||'').slice(0,6000),contact:String(input.contact||'').slice(0,100),environment:!!input.environment,at:new Date().toISOString()};await write(path.join(root(),'feedback-draft.json'),p);return p;});
register('feedback:email',async input=>{if(!feedbackEmail)throw Error('当前版本未配置反馈邮箱，请复制反馈内容自行发送');const subject=String(input.subject||'观澜使用反馈').slice(0,160),body=String(input.body||'').slice(0,8000);await shell.openExternal('mailto:'+feedbackEmail+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body));return true;});
register('storage:info',()=>locations.info());
register('storage:choose',async mode=>{const r=await dialog.showOpenDialog(win,{title:mode==='connect'?'选择已有导演资料目录':'选择空文件夹作为新资料目录',properties:['openDirectory','createDirectory']});if(r.canceled)return null;locationChoice={token:crypto.randomUUID(),path:r.filePaths[0],mode};return {token:locationChoice.token,path:locationChoice.path,resumable:mode==='migrate'&&await fs.access(path.join(locationChoice.path,'.director-migration.json')).then(()=>true,()=>false)};});
register('storage:apply',async input=>{if(!locationChoice||input.token!==locationChoice.token||input.mode!==locationChoice.mode)throw Error('请重新选择资料目录');if(activeCalls>1||requests.size)throw Error('仍有读写或模型任务，请完成后重试');locationChanging=true;try{await Promise.all([...writes.values()]);const result=await (input.mode==='connect'?locations.connect(locationChoice.path):locations.migrate(locationChoice.path,progress=>win.webContents.send('storage:progress',progress)));storage=null;locationChoice=null;return result;}finally{locationChanging=false;}});
register('app:info',()=>({version:app.getVersion(),edition:'统一版',packaged:app.isPackaged,storage:locations.root(),signed:'未配置发布签名',headless:!!process.env.DIRECTOR_HEADLESS,feedbackEmailAvailable:!!feedbackEmail}));
register('projects:rescue',async p=>{const r=await dialog.showSaveDialog(win,{defaultPath:p.name+'-救援.director.json',filters:[{name:'内存项目救援',extensions:['json']}]});if(r.canceled)return null;const data=await require('./rescue')(p,root());const temp=r.filePath+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(temp,JSON.stringify(data,null,2));await fs.rename(temp,r.filePath);return {path:r.filePath,missing:data.missingMedia.length};});
register('projects:list',()=>store().list());
const globalLibrary=require('./global-library');
const globalLibraryFile=()=>path.join(root(),'global-library.json');
register('library:list',async()=>{const rows=await read(globalLibraryFile(),[]);return Array.isArray(rows)?rows.slice(0,1000).map(x=>{try{return globalLibrary.clean(x);}catch{return null;}}).filter(Boolean):[];});
register('library:save',async input=>{const item=globalLibrary.clean(input),rows=await read(globalLibraryFile(),[]),index=rows.findIndex(x=>x.id===item.id);if(index>=0)rows[index]=item;else{if(rows.length>=1000)throw Error('个人资产库最多保存 1000 项');rows.unshift(item);}await write(globalLibraryFile(),rows);return item;});
register('projects:create',async name=>store().save(C.normalize({id:C.id('p'),name:String(name||'新项目').trim().slice(0,80),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),selectedProfile:'manju'})));
register('projects:save',async project=>{validId(project.id);project.updatedAt=new Date().toISOString();await store().save(project);return {updatedAt:project.updatedAt};});
register('projects:archive',id=>store().archive(id));
register('projects:archived',()=>store().archived());
register('projects:unarchive',key=>store().unarchive(key));
register('projects:removeArchived',key=>store().removeArchived(key));
register('recovery:list',()=>store().recoveryList());
register('recovery:restore',({id,snapshot})=>store().recover(id,snapshot));
register('recovery:raw',async id=>{const files=await store().rawBackup(id);const r=await dialog.showSaveDialog(win,{defaultPath:id+'-原始资料.zip'});if(r.canceled)return;const zip=new AdmZip();for(const f of files)zip.addFile(f.name,f.data);zip.writeZip(r.filePath);return r.filePath;});
register('projects:backup',async p=>{const r=await dialog.showSaveDialog(win,{defaultPath:p.name+'.director.json',filters:[{name:'导演项目（含参考图，不含密钥）',extensions:['json']}]});if(r.canceled)return null;await fs.writeFile(r.filePath,JSON.stringify({format:'director-project',version:2,project:await store().media(p,true)},null,2),'utf8');return r.filePath;});
register('projects:restore',async()=>{const r=await dialog.showOpenDialog(win,{filters:[{name:'导演项目备份',extensions:['json']}],properties:['openFile']});if(r.canceled)return null;if((await fs.stat(r.filePaths[0])).size>150*1024*1024)throw Error('备份文件过大');const parsed=JSON.parse(await fs.readFile(r.filePaths[0],'utf8'));if(parsed.format!=='director-project'||!parsed.project?.name)throw Error('不是有效的导演项目备份');const p=C.normalize(parsed.project);if(parsed.rescue){p.rescueManifest=parsed.missingMedia||[];for(const a of p.assets){const missing=a.references.filter(r=>!r.data);if(missing.length){a.missingReferences=missing.map(r=>({id:r.id,name:r.name}));a.references=a.references.filter(r=>r.data);a.status='draft';a.sourceReview=true;}}C.touch(p,'救援恢复：请补齐缺失素材并重新审核');}p.id=C.id('p');p.name+='（恢复）';p.updatedAt=new Date().toISOString();for(const a of p.assets)for(const ref of a.references)if(!/^data:image\/(png|jpeg|webp);base64,/.test(ref.data||''))throw Error('备份含不支持的参考图内容');return store().save(p);});
register('files:result',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'成片或证据',extensions:['mp4','mov','webm','png','jpg','pdf']}]});if(r.canceled)return null;const stat=await fs.stat(r.filePaths[0]);return {path:r.filePaths[0],name:path.basename(r.filePaths[0]),bytes:stat.size,modifiedAt:stat.mtime.toISOString()};});
register('files:results',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile','multiSelections'],filters:[{name:'成片或证据',extensions:['mp4','mov','webm','png','jpg','pdf']}]});if(r.canceled)return [];if(r.filePaths.length>30)throw Error('一次最多关联30个文件，请分批处理');return Promise.all(r.filePaths.map(async filePath=>{const stat=await fs.stat(filePath);if(!stat.isFile())throw Error('所选项目不是文件');return {path:filePath,name:path.basename(filePath),bytes:stat.size,modifiedAt:stat.mtime.toISOString()};}));});
register('files:script',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'剧本与字幕',extensions:['txt','md','srt','docx','pdf']}]});if(r.canceled)return null;return {name:path.basename(r.filePaths[0]),text:await documentText(r.filePaths[0])};});
register('spatial:embed',async value=>{if(!/^director-media:\/\/image\/[a-f0-9]{64}\.(png|jpeg|webp)$/.test(value||''))throw Error('无效底图');return store().media(value,true);});
register('files:image',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile','multiSelections'],filters:[{name:'参考图',extensions:['png','jpg','jpeg','webp']}]});if(r.canceled)return [];const refs=[];for(const file of r.filePaths){const data=await fs.readFile(file);if(data.length>8*1024*1024)throw Error('单张参考图请控制在 8MB 以内');const ext=path.extname(file).slice(1).replace('jpg','jpeg');refs.push({id:C.id('r'),name:path.basename(file),data:`data:image/${ext};base64,${data.toString('base64')}`});}return store().media(refs);});
register('knowledge:list',modules);
register('knowledge:import',async mode=>{const r=await dialog.showOpenDialog(win,mode==='folder'?{properties:['openDirectory']}:{properties:['openFile','multiSelections'],filters:[{name:'导演资料',extensions:['md','txt','docx','pdf','zip']}]});if(r.canceled)return {added:[],skipped:[]};const files=[];
 async function walk(dir){for(const item of await fs.readdir(dir,{withFileTypes:true})){if(item.name.startsWith('~$')||item.name.startsWith('.'))continue;const file=path.join(dir,item.name);if(item.isDirectory())await walk(file);else if(/\.(md|txt|docx|pdf)$/i.test(file))files.push(file);if(files.length>200)throw Error('一次最多导入 200 份资料');}}
 if(mode==='folder')await walk(r.filePaths[0]);else files.push(...r.filePaths);const existing=await modules(),custom=await read(path.join(root(),'knowledge.json'),[]),added=[],skipped=[];
 async function add(name,source,data){try{const text=await documentText(name,data);if(!text.trim())return;const hash=crypto.createHash('sha256').update(text).digest('hex');if(existing.some(k=>k.hash===hash)||added.some(k=>k.hash===hash)){skipped.push(name+'（重复）');return;}added.push({id:C.id('k'),name:path.basename(name,path.extname(name)),source,hash,text,kind:'reference',stages:['analysis','assets','shots'],enabledByDefault:false,version:'1',importedAt:new Date().toISOString(),builtin:false,scope:'personal'});}catch(e){skipped.push(name+'：'+e.message);}}
 for(const file of files){if(path.extname(file).toLowerCase()==='.zip'){const zip=new AdmZip(file);let total=0;const entries=zip.getEntries();if(entries.length>500)throw Error('压缩包条目过多');for(const entry of entries){if(entry.isDirectory||!(/\.(md|txt|docx|pdf)$/i.test(entry.entryName)))continue;total+=entry.header.size;if(total>50*1024*1024)throw Error('压缩包解压内容超过 50MB');await add(entry.entryName,path.basename(file)+'/'+entry.entryName,entry.getData());}}else await add(file,file);}
 await write(path.join(root(),'knowledge.json'),[...custom,...added]);return {added,skipped};});
register('knowledge:save',async item=>{const list=await read(path.join(root(),'knowledge.json'),[]),index=list.findIndex(k=>k.id===item.id);if(index<0)throw Error('内置资料不可覆盖，可通过项目开关控制');list[index]={...list[index],name:String(item.name),kind:item.kind,stages:item.stages,version:item.version};await write(path.join(root(),'knowledge.json'),list);return true;});
register('knowledge:remove',async id=>{const list=await read(path.join(root(),'knowledge.json'),[]);await write(path.join(root(),'knowledge.json'),list.filter(k=>k.id!==id));return true;});
register('settings:get',async()=>{const s=await settings();delete s.encryptedKey;const hasKey=Boolean(s.apiKey);delete s.apiKey;return {...s,hasKey};});
register('settings:save',async input=>{const old=await settings(),s={provider:input.provider,baseUrl:input.baseUrl,localUrl:input.localUrl,model:input.model,contextTokens:Number(input.contextTokens)||65536,outputTokens:Number(input.outputTokens)||8192,vision:Boolean(input.vision),stream:input.stream!==false,inputPrice:Number(input.inputPrice)||0,outputPrice:Number(input.outputPrice)||0,currency:input.currency||'CNY'};endpoint(s);const sameOrigin=old.baseUrl&&new URL(old.baseUrl).origin===new URL(s.baseUrl).origin;const key=input.clearKey?'':input.apiKey||(sameOrigin?old.apiKey:'')||'';if(key){if(!safeStorage.isEncryptionAvailable())throw Error('当前系统无法加密保存密钥');s.encryptedKey=safeStorage.encryptString(key).toString('base64');}await write(path.join(root(),'settings.json'),s);await modelHub.captureLegacy(s);return true;});
register('model:models',async()=>{const s=await settings(),{base,key}=endpoint(s);const r=await fetch(base+'/models',{headers:key?{Authorization:`Bearer ${key}`}:{},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`模型列表读取失败 HTTP ${r.status}`);return ((await r.json()).data||[]).map(x=>x.id);});
register('model:cancel',async id=>{requests.get(id)?.abort();return true;});
register('usage:list',()=>usageStore.list());
register('model:generate',async(input,event)=>{const s=await settings();input.images=await Promise.all((input.images||[]).map(x=>store().media(x,true)));return require('./model-client')(s,input,event,requests,endpoint,usage=>usageStore.append({...usage,id:input.requestId,kind:input.kind==='film'?'film':'generation',projectId:input.projectId,projectName:input.projectName}));});
register('model:diagnose',async(_,event)=>{const s=await settings(),started=Date.now();const text=await require('./model-client')(s,{requestId:'diagnose_'+Date.now(),system:'Return only valid JSON.',user:'Return exactly {"connected":true} without any extra text.',images:[]},event,requests,endpoint,usage=>usageStore.append({...usage,id:'diagnosis_'+started,kind:'diagnosis'}));let structured=false;try{structured=C.parseJson(text).connected===true;}catch{}return {model:s.model,latency:Date.now()-started,chat:true,structured,vision:s.vision?'用户声明支持，尚未读图验证':'未启用',at:new Date().toISOString()};});
register('clipboard:copy',async text=>{clipboard.writeText(String(text));return true;});
register('files:export',async({name,format,text})=>{const r=await dialog.showSaveDialog(win,{defaultPath:name+'.'+format,filters:[{name:format.toUpperCase(),extensions:[format]}]});if(r.canceled)return null;await fs.writeFile(r.filePath,String(text),'utf8');return r.filePath;});
register('files:openData',async()=>{await fs.mkdir(root(),{recursive:true});await shell.openPath(root());});
register('delivery:export',payload=>require('./delivery')(payload,win,store()));
register('review:import',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'审稿返回文件',extensions:['json']}]});if(r.canceled)return null;if((await fs.stat(r.filePaths[0])).size>5*1024*1024)throw Error('审稿文件过大');const value=JSON.parse(await fs.readFile(r.filePaths[0],'utf8'));if(!Array.isArray(value.comments)||value.comments.length>500)throw Error('无效审稿文件');return value;});
register('app:close',async()=>{win.destroy();});
if(!app.requestSingleInstanceLock())app.quit();
app.on('second-instance',()=>{if(win){win.show();win.focus();}});
app.whenReady().then(()=>{protocol.handle('director-video',async request=>{const u=new URL(request.url);let linked=u.hostname==='result'?previewFiles.get(u.pathname.slice(1)):null;if(u.hostname==='linked'&&/^\/film_[\w-]+$/.test(u.pathname))linked=(await filmStore.list()).find(x=>x.id===u.pathname.slice(1))?.sourcePath;if(!linked&&(u.hostname!=='clip'||!/^\/[a-f0-9]{64}\.(mp4|webm|mov|m4v|mp3|wav|m4a)$/.test(u.pathname)))return new Response('Not found',{status:404});try{const file=linked||path.join(root(),'clips',u.pathname.slice(1)),stat=await fs.stat(file),range=request.headers.get('range');let start=0,end=stat.size-1,status=200;const headers={'Content-Type':file.toLowerCase().endsWith('.webm')?'video/webm':file.toLowerCase().endsWith('.mp3')?'audio/mpeg':file.toLowerCase().endsWith('.wav')?'audio/wav':file.toLowerCase().endsWith('.m4a')?'audio/mp4':'video/mp4','Accept-Ranges':'bytes','Access-Control-Allow-Origin':'*'};if(range){const match=/^bytes=(\d+)-(\d*)$/.exec(range);if(!match)return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+stat.size}});start=Number(match[1]);end=match[2]?Math.min(Number(match[2]),end):end;if(start>end)return new Response(null,{status:416,headers:{'Content-Range':'bytes */'+stat.size}});status=206;headers['Content-Range']='bytes '+start+'-'+end+'/'+stat.size;}headers['Content-Length']=String(end-start+1);return new Response(require('node:stream').Readable.toWeb(require('node:fs').createReadStream(file,{start,end})),{status,headers});}catch{return new Response('Not found',{status:404});}});protocol.handle('director-media',async request=>{const u=new URL(request.url);if(u.hostname!=='image'||!/^\/[a-f0-9]{64}\.(png|jpeg|webp)$/.test(u.pathname))return new Response('Not found',{status:404});try{return new Response(await fs.readFile(path.join(root(),'media',u.pathname.slice(1))),{headers:{'Content-Type':'image/'+u.pathname.split('.').at(-1)}});}catch{return new Response('Not found',{status:404});}});win=new BrowserWindow({width:1460,height:980,minWidth:1050,minHeight:720,show:!process.env.DIRECTOR_HEADLESS,title:'观澜 · AI 导演创作工作台',icon:path.join(__dirname,'assets','brand','guanlan-256.png'),backgroundColor:'#f5f3ed',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.on('close',event=>{if(!win.webContents.isLoading()){event.preventDefault();win.webContents.send('app:closing');}});win.removeMenu();win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());win.loadFile(path.join(__dirname,'index.html'));});
app.on('window-all-closed',()=>app.quit());


