const crypto=require('node:crypto');
module.exports=function({root,path,read,write,safeStorage}){
 let chain=Promise.resolve();const file=()=>path.join(root(),'model-connections.json');
 const serial=fn=>{const task=chain.catch(()=>{}).then(fn);chain=task;return task;};
 const load=async()=>{const data=await read(file(),null);if(data)return data;const old=await read(path.join(root(),'settings.json'),{});return {profiles:old.model?[{...old,baseUrl:old.provider==='local'?(old.localUrl||'http://localhost:11434/v1'):old.baseUrl,id:'legacy-chat',name:'原有文字模型',kind:'chat'}]:[],activeChat:old.model?'legacy-chat':null,activeImage:null};};
 function validateUrl(value){let u;try{u=new URL(String(value));}catch{throw Error('请填写有效的接口地址');}if(u.username||u.password||u.search||u.hash)throw Error('接口地址不可包含账号、密码或查询参数');if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))throw Error('云端接口必须使用 HTTPS；本机接口允许 HTTP');return u.href.replace(/\/$/,'');}
 function clean(p){const {encryptedKey,apiKey,...value}=p;return {...value,hasKey:!!encryptedKey};}
 function decrypt(p){if(!p)return null;const value={...p};delete value.encryptedKey;if(p.encryptedKey){try{value.apiKey=safeStorage.decryptString(Buffer.from(p.encryptedKey,'base64'));}catch{throw Error('此连接密钥无法解密，请重新填写');}}return value;}
 async function list(){const data=await load();return {...data,profiles:data.profiles.map(clean)};}
 async function save(input){return serial(async()=>{const data=await load(),old=data.profiles.find(p=>p.id===input.id);if(input.id&&!old)throw Error('连接已不存在，请重新打开配置');const name=String(input.name||'').trim().slice(0,80),model=String(input.model||'').trim().slice(0,180);if(!name||!model)throw Error('请填写连接名称和模型名称');if(!['chat','image'].includes(input.kind))throw Error('无效模型用途');if(old&&old.kind!==input.kind)throw Error('连接用途不可更改');const baseUrl=validateUrl(input.baseUrl),local=input.provider==='local';if(local&&!['localhost','127.0.0.1','[::1]'].includes(new URL(baseUrl).hostname))throw Error('本机模型请填写 localhost 或 127.0.0.1');const s={id:old?.id||crypto.randomUUID(),name,kind:input.kind,provider:local?'local':'cloud',baseUrl,localUrl:baseUrl,model,presetId:String(input.presetId||''),chatAdapter:['standard','openai','anthropic'].includes(input.chatAdapter)?input.chatAdapter:'standard',adapter:['siliconflow','dashscope','seedream','gemini','standard'].includes(input.adapter)?input.adapter:'standard',sizes:Array.isArray(input.sizes)?input.sizes.filter(x=>/^\d{3,4}x\d{3,4}$/.test(x)).slice(0,12):['1024x1024'],contextTokens:Number(input.contextTokens)||65536,outputTokens:Number(input.outputTokens)||8192,vision:!!input.vision,stream:input.stream!==false,inputPrice:Math.max(0,Number(input.inputPrice)||0),outputPrice:Math.max(0,Number(input.outputPrice)||0),currency:String(input.currency||'CNY').slice(0,8)};if(!Number.isFinite(s.outputTokens)||!Number.isFinite(s.contextTokens)||s.outputTokens<512||s.outputTokens>32000||s.contextTokens<=s.outputTokens)throw Error('输出预留须为512–32000，且小于上下文上限');const same=old&&new URL(old.baseUrl||old.localUrl).origin===new URL(baseUrl).origin;const key=String(input.apiKey||'').trim();if(key){if(!safeStorage.isEncryptionAvailable())throw Error('系统无法加密保存密钥');s.encryptedKey=safeStorage.encryptString(key).toString('base64');}else if(same&&!input.clearKey&&old.encryptedKey)s.encryptedKey=old.encryptedKey;if(!s.sizes.length)s.sizes=['1024x1024'];if(old)data.profiles[data.profiles.indexOf(old)]=s;else data.profiles.push(s);await write(file(),data);if(data.activeChat===s.id)await write(path.join(root(),'settings.json'),s);return clean(s);});}
 async function activate(id){return serial(async()=>{const data=await load(),p=data.profiles.find(x=>x.id===id);if(!p)throw Error('连接不存在');if(p.kind==='chat'){await write(path.join(root(),'settings.json'),p);data.activeChat=id;}else data.activeImage=id;await write(file(),data);return true;});}
 async function remove(id){return serial(async()=>{const data=await load();if([data.activeChat,data.activeImage].includes(id))throw Error('当前使用中的连接不可删除，请先启用其他连接');data.profiles=data.profiles.filter(p=>p.id!==id);await write(file(),data);return true;});}
 async function captureLegacy(s){return serial(async()=>{const data=await load(),id=data.activeChat||'legacy-chat',old=data.profiles.find(x=>x.id===id);const value={...s,baseUrl:s.provider==='local'?(s.localUrl||'http://localhost:11434/v1'):s.baseUrl,id,name:old?.name||'文字模型',kind:'chat'};data.profiles=data.profiles.filter(x=>x.id!==id);data.profiles.push(value);data.activeChat=id;await write(file(),data);});}
 async function imageSettings(){const data=await load(),p=data.profiles.find(x=>x.id===data.activeImage&&x.kind==='image');if(!p)throw Error('请先在模型中心配置并启用生图模型');return decrypt(p);}
 return {list,save,activate,remove,captureLegacy,imageSettings,validateUrl};
};
