function audioRow(i,c){const characters=Object.fromEntries(S.project.assets.filter(a=>selectedSequence().assetIds.includes(a.id)&&a.kind==='character').map(a=>[a.id,a.name]));return `<section class="card" data-audio-row="${i}"><div class="grid">${modalSelect(`audio-${i}-type`,'类型',{dialogue:'角色对白',narration:'旁白',inner:'内心独白'},c.type||'dialogue')}${modalSelect(`audio-${i}-speaker`,'说话者',{'':'叙述者',...characters},c.speaker||'')}${inputHtml(`audio-${i}-language`,'本句语言',c.language||'')}${inputHtml(`audio-${i}-start`,'开始秒',c.start??0,'number')}${inputHtml(`audio-${i}-end`,'结束秒',c.end??1,'number')}</div>${area(`audio-${i}-text`,'台词（保留原文语言）',c.text||'')}${inputHtml(`audio-${i}-overlap`,'重叠理由（不重叠可留空）',c.overlapReason||'')}<label class="check"><input id="audio-${i}-lip" type="checkbox" ${c.lipSync?'checked':''}>说话者对口型</label>${btn('删除此声音','audio-remove',`data-index="${i}"`,'small')}</section>`;}
function showPerformanceEditor(g,index){const s=selectedSequence(),p=S.project,sh=g.shots[index];if(!sh)throw Error('镜头不存在');const actors=p.assets.filter(a=>s.assetIds.includes(a.id)&&a.kind==='character');const changes=(sh.stateOut||[]).filter(a=>{const prev=sh.stateIn?.find(x=>x.assetId===a.assetId);return prev&&(prev.presence||'present')!==(a.presence||'present');});
 showModal('声音、人物反应与进出画',`<p>没有人声时保留空列表。此处保存后会同步镜头人声文本。旧文本：${esc(sh.voice)}</p><div id="audio-rows">${(sh.audio||[]).map((c,i)=>audioRow(i,c)).join('')}</div>${btn('增加一句声音','audio-add')}<h3>逐人反应</h3>${actors.map(a=>area('reaction-'+a.id,a.name+'（离场可留空，背影也需自然反应）',sh.actorReactions?.find(r=>r.assetId===a.id)?.text||'')).join('')}<h3>进出画事件</h3>${changes.map(a=>inputHtml('event-'+a.assetId,(actors.find(x=>x.id===a.assetId)?.name||a.assetId)+' · '+(sh.stateIn.find(x=>x.assetId===a.assetId).presence||'present')+' → '+(a.presence||'present'),sh.presenceEvents?.find(e=>e.assetId===a.assetId)?.reason||'')).join('')||'<p>当前首尾没有进出画变化。</p>'}`,async()=>{
  const audio=[...$('audio-rows').children].map(el=>{const i=el.dataset.audioRow;return {type:$(`audio-${i}-type`).value,speaker:$(`audio-${i}-speaker`).value,text:$(`audio-${i}-text`).value.trim(),language:$(`audio-${i}-language`).value.trim(),start:Number($(`audio-${i}-start`).value),end:Number($(`audio-${i}-end`).value),lipSync:$(`audio-${i}-lip`).checked,overlapReason:$(`audio-${i}-overlap`).value.trim()};});
  const actorReactions=actors.map(a=>({assetId:a.id,text:$('reaction-'+a.id).value.trim()})).filter(r=>r.text);
  const presenceEvents=changes.map(a=>({assetId:a.assetId,from:sh.stateIn.find(x=>x.assetId===a.assetId).presence||'present',to:a.presence||'present',reason:$('event-'+a.assetId).value.trim()}));
  const updated={...sh,audio,actorReactions,presenceEvents,voice:C.audioText(audio),reactions:actorReactions.map(r=>(actors.find(a=>a.id===r.assetId)?.name||r.assetId)+'：'+r.text).join('；')||'环境自然变化'};
  const errors=C.performanceIssues(p,s,{...g,performanceSchema:2,shots:[updated]});if(errors.length)throw Error(errors.join('；'));snapshotSegment(g);Object.assign(sh,updated);if(g.shots.every(x=>Array.isArray(x.audio)&&Array.isArray(x.actorReactions)))g.performanceSchema=2;g.reviewed=false;C.invalidateAfter(s,s.segments.indexOf(g),'声音或人物表演变化');await persist();render();
 },true,'保存并同步镜头');
}
