PromptGuide.install(C);
function skinVideoSync(p){const old=document.getElementById('skin-background');if(p.skin!=='deepsea'||!p.skinVideo){old?.remove();return;}let video=old;if(!video){video=document.createElement('video');video.id='skin-background';video.autoplay=true;video.muted=true;video.loop=true;video.playsInline=true;video.setAttribute('aria-hidden','true');document.body.prepend(video);}if(video.getAttribute('src')!==p.skinVideo)video.setAttribute('src',p.skinVideo);if(document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches)video.pause();else video.play().catch(()=>{});}
const skinApplyBase=applyPersonal;applyPersonal=function(p){skinApplyBase(p);document.documentElement.dataset.skin=p.skin||'default';if(p.skin==='deepsea'){const root=document.documentElement;root.dataset.theme='dark';for(const [key,color]of Object.entries({'--brand':'#8bbfd0','--focus':'#8bbfd0','--surface':'#1b2934','--bg':'#111b24','--title-surface':'#23333e','--floating':'#263641','--line':'#31434d','--border':'#50636d','--muted':'#b7c9ce','--ink':'#e5eff0','--preview':'#0d1720'}))root.style.setProperty(key,color);root.style.setProperty('--on-brand','#11212b');}else{for(const key of ['--bg','--title-surface','--floating','--line','--border','--muted','--ink','--preview'])document.documentElement.style.removeProperty(key);}skinVideoSync(p);};
document.addEventListener('visibilitychange',()=>skinVideoSync(PRODUCT.personal));
const skinValuesBase=personalValues;personalValues=function(){const p=skinValuesBase();p.skin=$('person-skin')?.value||p.skin||'default';p.bootFrequency=$('person-boot-frequency')?.value||p.bootFrequency||'once';p.bootEnabled=p.bootFrequency!=='never';return p;};
const skinCenterBase=personalCenter;personalCenter=async function(draft=null){await skinCenterBase(draft);const p=draft||EXPERIENCE.personalDraft||PRODUCT.personal,body=$('modal-body'),target=body.querySelector('.u80-settings-content [data-setting-section="appearance"]')?.parentElement||body;const section=document.createElement('section');section.className='skin-settings';section.dataset.settingSection='appearance';section.innerHTML=`<h3>工作台皮肤与启动片头</h3><div class="grid"><label>工作台皮肤<select id="person-skin">${opts({default:'观澜 · 标准工作台',deepsea:'观澜 · 深海工作台（原创）'},p.skin||'default')}</select></label><label class="check"><input id="person-boot-enabled" type="checkbox" ${p.bootEnabled!==false?'checked':''}>每次启动展示片头（可跳过）</label></div><p class="muted">深海皮肤是观澜原创配色，不预装第三方「鲸鱼娘」素材。可自行导入有权使用的本机背景视频；背景透明度固定 6%，减少长时间创作时的视觉干扰。</p><div class="toolbar">${btn('导入皮肤背景视频','personal-skin-video')}${p.skinVideo?btn('移除背景视频','personal-skin-clear'):''}${btn('导入启动视频','personal-boot-video')}${p.bootVideo?btn('移除启动视频','personal-boot-clear'):''}${btn('预览片头','personal-boot-preview')}</div><p class="muted">启动片头静音播放，最长 8 秒，可随时跳过；系统设置为减少动态效果时，背景视频会暂停。</p>`;target.append(section);u80SettingsShow?.();};
let bootTimer=0,bootReturn=null;
function bootHide(){clearTimeout(bootTimer);document.getElementById('guanlan-boot')?.remove();const draft=bootReturn;bootReturn=null;if(draft)personalCenter(draft).catch(showError);}
function bootShow(p,returnDraft=null){bootHide();bootReturn=returnDraft;const overlay=document.createElement('div');overlay.id='guanlan-boot';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-label','观澜启动片头');overlay.innerHTML=`${p.bootVideo?`<video autoplay muted playsinline aria-hidden="true" src="${esc(p.bootVideo)}"></video>`:''}<div class="boot-vignette"></div><div class="boot-center"><img src="assets/brand/guanlan-mark-dark.svg" alt=""><strong>观澜</strong><span>AI 导演创作工作台</span><i></i></div><button class="boot-skip" type="button" aria-label="跳过启动片头">跳过片头　↵</button>`;document.body.append(overlay);overlay.querySelector('.boot-skip').addEventListener('click',bootHide);overlay.querySelector('video')?.addEventListener('ended',bootHide,{once:true});overlay.querySelector('video')?.addEventListener('error',()=>overlay.querySelector('video')?.remove(),{once:true});bootTimer=setTimeout(bootHide,p.bootVideo?8000:2600);}
document.addEventListener('keydown',e=>{if(document.getElementById('guanlan-boot')&&['Escape','Enter',' '].includes(e.key)){e.preventDefault();bootHide();}});
const skinActBase=act;act=async function(action,d={}){if(action==='personal-reset'){return personalCenter({...personalValues(),skin:'default',skinVideo:'',theme:'dark',accent:'#75bcae',surface:'',opacity:100,backgroundOpacity:0,blur:0,background:''});}if(action==='personal-skin-video'||action==='personal-boot-video'){const p=personalValues(),url=await call('personal:bootVideo',action==='personal-skin-video'?'skin':'boot');if(url){p[action==='personal-skin-video'?'skinVideo':'bootVideo']=url;return personalCenter(p);}return;}if(action==='personal-skin-clear'||action==='personal-boot-clear'){const p=personalValues();p[action==='personal-skin-clear'?'skinVideo':'bootVideo']='';return personalCenter(p);}if(action==='personal-boot-preview'){const p=personalValues();closeModal();return bootShow(p,p);}return skinActBase(action,d);};
const richSampleBase=createSample;createSample=async function(){await richSampleBase();if(S.project?.name!=='原创示例 · 雨夜归还')return;const seq=S.project.sequences[0],shots=seq?.segments[0]?.shots||[];if(shots[0])Object.assign(shots[0],{purpose:'建立桌面两侧的人物关系，交代钥匙仍由陈安持有，并让林舟注意到钥匙。',performance:'陈安说话前呼吸停半拍，目光从林舟面部移向自身右手钥匙；林舟先看钥匙，再轻点头一次，双手保持空置。',expression:'前段陈安嘴唇自然闭合；说“钥匙还你”时下颌小幅张合，句末嘴角回到中性。林舟听到“还你”后上眼睑略抬，视线下移到钥匙，点头时眉间保持放松；所有变化以脸部比例为参照，不指定无依据毫米数。'});if(shots[1])Object.assign(shots[1],{purpose:'把钥匙的归属从陈安转给林舟；用先接稳、后松手的顺序完成因果闭环。',performance:'陈安右臂从肘部前伸，钥匙柄朝向林舟；林舟右手先张开拇指与食指，指腹夹稳钥匙后陈安才松开；两人目光随钥匙移动，交接后各停约一秒。',expression:'陈安松手前视线停在两人指尖，松手后眼睑自然回落、下颌放松；林舟接稳时目光短暂落在钥匙，嘴唇轻抿后恢复自然闭合。变化按镜头时间先后描述，不虚构实际长度。'});if(seq?.segments[0])seq.segments[0].prompt=C.promptText(seq,seq.segments[0],S.project);await persist();render();};
setTimeout(async()=>{try{const info=await call('app:info');if(info.headless)return;for(let i=0;i<50&&!PRODUCT.ready;i++)await new Promise(r=>setTimeout(r,100));if(!PRODUCT.ready)return;const p=PRODUCT.personal,frequency=p.bootFrequency||'once';if(frequency==='never'||p.bootEnabled===false)return;if(frequency==='once'){if(localStorage.getItem('guanlan.boot.seen.v1'))return;localStorage.setItem('guanlan.boot.seen.v1','1');}bootShow(p);}catch{}},0);
