(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Spatial=api;})(globalThis,()=>{
 const copy=x=>JSON.parse(JSON.stringify(x)),finite=Number.isFinite,clamp=x=>Math.max(0,Math.min(100,Number(x))),fields=['scene','camera','frame','action','motion','continuity','transition','reactions'];
 const convention='【本镜方位约定】画面左/右以本镜摄像机的观众视角为准；人物自身左/右手按人物解剖方向，不随反打互换；场景坐标仅按已标定轴线；物体自身左右仅在该物体正向已确认时使用。每个方位动作就地注明参照，不使用无主语的左、右、前、后。换机位重新描述画面位置；环绕或越轴按开始/结束分阶段描述，不把场景位置与画面位置混同。';
 function create(){return {version:1,revision:0,width:1000,height:700,image:null,origin:{x:50,y:50},axis:{x:75,y:50},axisName:'场景横轴正向',originName:'场景中心',scale:{a:{x:20,y:80},b:{x:80,y:80},meters:0},anchors:[],confirmed:false};}
 function pixel(l,p){return {x:Number(p.x)*l.width/100,y:Number(p.y)*l.height/100};}
 function distance(l,a,b){a=pixel(l,a);b=pixel(l,b);return Math.hypot(a.x-b.x,a.y-b.y);}
 function coord(l,p){const a=pixel(l,l.origin),b=pixel(l,l.axis),q=pixel(l,p),len=Math.hypot(b.x-a.x,b.y-a.y);if(len<1)throw Error('原点与横轴方向点不能重合');const ex={x:(b.x-a.x)/len,y:(b.y-a.y)/len},scale=l.scale?.meters>0?l.scale.meters/distance(l,l.scale.a,l.scale.b):100/Math.max(l.width,l.height);return {x:((q.x-a.x)*ex.x+(q.y-a.y)*ex.y)*scale,y:((q.x-a.x)*ex.y-(q.y-a.y)*ex.x)*scale,unit:l.scale?.meters>0?'米':'相对单位'};}
 function valid(l){const errors=[];if(l?.version!==1)return ['不支持的场景标定版本'];if(!finite(l.width)||!finite(l.height)||l.width<=0||l.height<=0)errors.push('底图尺寸无效');const point=(p,n)=>{if(!p||!finite(p.x)||!finite(p.y)||p.x<0||p.x>100||p.y<0||p.y>100)errors.push(n+'必须位于底图0–100范围');};point(l.origin,'原点');point(l.axis,'横轴方向点');if(!String(l.axisName||'').trim()||!String(l.originName||'').trim())errors.push('请命名原点与横轴方向');if(distance(l,l.origin||{},l.axis||{})<1)errors.push('原点与横轴方向点不能重合');if(!finite(l.scale?.meters)||l.scale.meters<0)errors.push('比例尺长度必须是非负数');if(l.scale?.meters>0){point(l.scale.a,'标尺起点');point(l.scale.b,'标尺终点');if(distance(l,l.scale.a,l.scale.b)<1)errors.push('比例尺两点不能重合');}if(!Array.isArray(l.anchors)||l.anchors.length>100)errors.push('场景锚点最多100个');else{const ids=new Set();for(const a of l.anchors){if(!/^[\w-]+$/.test(a.id)||ids.has(a.id))errors.push('锚点编号重复或无效');ids.add(a.id);point(a,a.name||'锚点');if(!a.name?.trim())errors.push('锚点名称不能为空');if(!finite(a.radius)||a.radius<0||a.radius>50)errors.push('障碍半径须为0–50（底图宽度百分比）');if(a.heading!=null&&(!finite(a.heading)||a.heading<0||a.heading>=360))errors.push('物体正向应为0–359度');}}if(l.image&&!/^(director-media:\/\/image\/[a-f0-9]{64}\.(png|jpeg|webp)|data:image\/(png|jpeg|webp);base64,[a-z0-9+/=\s]+)$/i.test(l.image.data||''))errors.push('不支持的底图来源');return errors;}
 function layout(p,s){return p.assets.find(a=>a.id===s.spatialSceneId&&a.kind==='scene')?.spatialLayout;}
 function info(p,s){const l=layout(p,s);return l?{sceneId:s.spatialSceneId,revision:l.revision,width:l.width,height:l.height,origin:l.origin,originName:l.originName,axis:l.axis,axisName:l.axisName,scale:l.scale,anchors:l.anchors,confirmed:l.confirmed,defaultCamera:s.spatialCamera||null}:null;}
 function projection(l,c,p){if(!c||distance(l,c,{x:c.tx,y:c.ty})<1)return null;const a=pixel(l,c),b=pixel(l,{x:c.tx,y:c.ty}),q=pixel(l,p),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);const side=((q.x-a.x)*-dy+(q.y-a.y)*dx)/len*(c.mirror?-1:1),depth=((q.x-a.x)*dx+(q.y-a.y)*dy)/len;return {side,depth,label:depth<=0?'机位后方（不保证入画）':Math.abs(side)<Math.max(l.width,l.height)*.015?'当前机位光轴附近':side<0?'当前机位画面左侧方向':'当前机位画面右侧方向'};}
 function cameraErrors(l,c){if(!c)return [];const e=[];for(const k of ['x','y','tx','ty',...(c.mode==='moving'?['ex','ey','etx','ety']:[])])if(!finite(c[k])||c[k]<0||c[k]>100)e.push('机位'+k+'须为0–100');if(distance(l,c,{x:c.tx,y:c.ty})<1)e.push('机位与注视点不能重合');if(c.mode==='moving'&&distance(l,{x:c.ex,y:c.ey},{x:c.etx,y:c.ety})<1)e.push('结束机位与注视点不能重合');return e;}
 function lint(text,l){const found=[];for(const sentence of String(text||'').split(/([。；;\n])/).filter(x=>x.trim()&&!/^[。；;\n]$/.test(x))){let clean=sentence.replace(/左右两难|左右为难|前后两次|前后文|左顾右盼|右键|左键|\d+(?:\.\d+)?\s*(?:秒|分钟|米|人|个)?左右/g,'');const terms=[...clean.matchAll(/左手|右手|向左|向右|往左|往右|左侧|右侧|左边|右边|左方|右方|前方|后方|前面|后面|向前|向后|往前|往后|[左右](?=入画|出画|移动|转身|转头|[，。；、\s]|$)|画面左|画面右|(?<![a-z])(?:left|right|front|behind|forward|backward)(?![a-z])/gi)];if(!terms.length)continue;for(const m of terms){const term=m[0],near=clean.slice(Math.max(0,m.index-16),m.index+term.length+12);const hand=/[左右]手/.test(term)||/^(?:left|right)$/i.test(term)&&/^\s*(?:hand|arm|leg|foot)\b/i.test(clean.slice(m.index+term.length));let ok=hand?/(?:自身|解剖|anatomical|own).{0,12}(?:[左右]手|(?:left|right)\s+(?:hand|arm|leg|foot))/i.test(near):/(?:画面|屏幕|观众视角|screen|frame|camera view).{0,12}(?:左|右|前|后|left|right|front|behind)/i.test(near)||/(?:以|按).{0,30}(?:画面|自身朝向|已标定场景|场景标定).{0,12}(?:为准|参照|坐标)/.test(clean);if(!hand&&/(?:人物|角色)自身(?:朝向)?(?:的)?(?:左|右|前|后)/.test(near)&&!l?.anchors.some(a=>near.includes(a.name+'自身')))ok=true;if(hand&&/^以.+自身(?:朝向|解剖方向)为准/.test(clean))ok=true;if(!ok&&l?.confirmed)ok=l.anchors.some(a=>a.heading!=null&&(clean.startsWith('以'+a.name+'自身正向为准')||clean.includes(a.name+'自身')&&near.includes('自身')));if(!ok)found.push({sentence,term,reason:hand?'需注明人物自身解剖方向':'缺少明确画面/人物自身/场景标定/物体自身参照'});}}
 return [...new Map(found.map(x=>[x.sentence+'|'+x.reason,x])).values()];}
 function issues(p,s,g){const out=[],l=layout(p,s);if(s.spatialSceneId&&!l)out.push('场景空间底图已丢失，请重新绑定');if(l){out.push(...valid(l));if(!l.confirmed)out.push('场景底图及标定尚未人工确认');}for(const [i,sh]of g.shots.entries()){for(const a of [...(sh.stateIn||[]),...(sh.stateOut||[])])if(a.heading!=null&&(!finite(a.heading)||a.heading<0||a.heading>=360))out.push('镜'+(i+1)+' 人物朝向角度无效');for(const [id,path]of Object.entries(sh.spatialPaths||{})){if(!Array.isArray(path)||path.length>100||path.some(q=>!finite(q.x)||!finite(q.y)||q.x<0||q.x>100||q.y<0||q.y>100))out.push('镜'+(i+1)+' 移动路径坐标无效');if(!p.assets.some(a=>a.id===id&&a.kind==='character'))out.push('镜'+(i+1)+' 移动路径人物不存在');}for(const key of fields)for(const x of lint(sh[key],l))out.push('镜'+(i+1)+' '+key+'：'+x.reason+'「'+x.sentence.trim().slice(0,90)+'」');if(l)out.push(...cameraErrors(l,sh.spatialCamera||s.spatialCamera).map(x=>'镜'+(i+1)+' '+x));}return [...new Set(out)];}
 function spatialText(p,s,sh){const l=layout(p,s);sh={...sh,spatialCamera:sh.spatialCamera||s.spatialCamera};let text=convention;if(!l)return text+'\n未绑定俯视图：仅执行文字明确声明的参照，不推断未知机位或真实尺度。';text+='\n场景锚定：'+JSON.stringify(info(p,s))+'\n坐标说明：人物x/y为底图宽高百分比；标定坐标原点为'+l.originName+'，+X指向'+l.axisName+'，+Y在俯视图中相对+X逆时针90度；'+(l.scale.meters>0?'已设比例尺。':'未设比例尺，不得输出真实米数。');text+='\n【供外部生成器理解的俯视参照】俯视图左上角=(0%,0%)，右下角=(100%,100%)；原点“'+l.originName+'”位于底图('+l.origin.x+'%,'+l.origin.y+'%)；+X朝向“'+l.axisName+'”方向点('+l.axis.x+'%,'+l.axis.y+'%)；机位与人物坐标都以同一张俯视图为准，不是最终画面像素坐标。';text+='\n固定锚点：'+(l.anchors.length?l.anchors.map(a=>a.name+' 位于底图('+a.x+'%,'+a.y+'%)'+(a.blocked?'，为遮挡/障碍':'')).join('；'):'尚无命名锚点；请先添加门、桌、窗等可见参照，避免只给数字坐标。');for(const [label,states,cam]of [['开始',sh.stateIn,sh.spatialCamera],['结束',sh.stateOut,sh.spatialCamera?.mode==='moving'?{...sh.spatialCamera,x:sh.spatialCamera.ex,y:sh.spatialCamera.ey,tx:sh.spatialCamera.etx,ty:sh.spatialCamera.ety}:sh.spatialCamera]]){text+='\n'+label+'空间：'+(states||[]).filter(a=>a.presence!=='absent').map(a=>{const q=coord(l,a),screen=projection(l,cam,a);return (p.assets.find(x=>x.id===a.assetId)?.name||a.assetId)+' 位于俯视图('+a.x+'%,'+a.y+'%)；标定坐标('+q.x.toFixed(2)+','+q.y.toFixed(2)+')'+q.unit+'；'+(screen?screen.label:'未定机位，不推断画面左右')+'；身体朝向'+(a.heading==null?a.facing||'待定':a.heading+'度（底图正上为0，顺时针）')+'；视线目标'+(p.assets.find(x=>x.id===a.gaze)?.name||l.anchors.find(x=>x.id===a.gaze)?.name||a.gaze||'待定')+'；自身左手='+a.left+'，自身右手='+a.right;}).join('\n');}text+='\n机位与路径：'+JSON.stringify({camera:sh.spatialCamera,paths:sh.spatialPaths||{}})+'\n请把俯视图作为空间参考图一同输入支持参考图的生成器；纯文本坐标只能约束相对关系，不能保证外部模型精确落点。以上画面方向为俯视几何辅助推导，不是镜头透视/遮挡仿真。运动机位须分阶段叙述；实际生成结果仍需核对。';return text;}
 function obstacles(l,points){const found=[];for(const a of l.anchors.filter(a=>a.blocked&&a.radius>0)){const o=pixel(l,a),r=a.radius*l.width/100;for(let i=0;i<points.length;i++){const u=pixel(l,points[Math.max(0,i-1)]),v=pixel(l,points[i]),dx=v.x-u.x,dy=v.y-u.y,t=Math.max(0,Math.min(1,((o.x-u.x)*dx+(o.y-u.y)*dy)/(dx*dx+dy*dy||1)));if(Math.hypot(u.x+t*dx-o.x,u.y+t*dy-o.y)<r){found.push(a.name);break;}}}return found;}
 function invalidate(p,sceneId){for(const s of p.sequences.filter(s=>s.spatialSceneId===sceneId)){const l=layout(p,s);if(l)s.axis='底图宽高百分比坐标；原点：'+l.originName+'；+X指向'+l.axisName+'；+Y为俯视逆时针90度。';for(const g of s.segments){g.reviewed=false;g.stale=true;g.staleReason='场景底图、锚点或标定改变，请复核全部相关镜头';g.prompt='';}}}
 function install(C){if(C.spatialInstalled)return;C.spatialInstalled=true;C.spatialIssues=issues;const old={context:C.context,audit:C.audit,promptText:C.promptText,compile:C.compile,dependencyStamp:C.dependencyStamp};C.audit=(p,s,g)=>[...old.audit(p,s,g),...issues(p,s,g)];C.dependencyStamp=(p,s,g)=>C.hash(old.dependencyStamp(p,s,g)+JSON.stringify(info(p,s)));C.context=(p,s,g,k)=>{const ctx=old.context(p,s,g,k);const extra='\n'+convention+'\n本场景空间参数：'+JSON.stringify(info(p,s))+'\n已有镜头的机位与路径：'+JSON.stringify(g.shots.map(sh=>({id:sh.id,camera:sh.spatialCamera,paths:sh.spatialPaths})));if(ctx.text.length+extra.length>ctx.budget)throw Error('场景空间资料超出上下文预算，请减少无关锚点或增加预算');ctx.text+=extra;ctx.characters=ctx.text.length;ctx.sources.push({label:'方位参照规范与场景标定',ref:s.spatialSceneId||'direction-convention'});return ctx;};C.promptText=(s,g,p)=>old.promptText(s,g,p)+'\n\n逐镜方位前置条件与空间依据：\n'+g.shots.map((sh,i)=>'镜'+(i+1)+'\n'+spatialText(p,s,sh)).join('\n\n');C.compile=(p,s,g)=>{const errors=issues(p,s,g);if(errors.length)throw Error(errors.join('；'));const result=old.compile(p,s,g);for(const t of result.tasks){const sh=g.shots[t.shot-1];t.prompt=spatialText(p,s,sh)+'\n\n'+t.prompt;if(layout(p,s)?.image)t.spatialReference={id:layout(p,s).image.id,role:'topdown-layout',note:'空间规划底图，不是最终画面构图参考'};t.spatial={layout:info(p,s),camera:copy(sh.spatialCamera||s.spatialCamera||null),paths:copy(sh.spatialPaths||{})};}return result;};}
 return {create,copy,clamp,fields,convention,pixel,distance,coord,valid,layout,info,projection,cameraErrors,lint,issues,spatialText,obstacles,invalidate,install};
});
