const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const {DatabaseSync}=require('node:sqlite');const C=require('./domain');
const collections=['assets','sequences','facts','rules','comments','deliveries','feedback','experiments','changeLog','assetProposals','jobs','analysisChunks'];
const valid=id=>{if(!/^p_[\w-]+$/.test(id))throw Error('无效项目编号');return id;};
module.exports=function(root){
const folder=id=>path.join(root,'projects',valid(id));let issues=[];
async function media(value,embed=false){if(Array.isArray(value))return Promise.all(value.map(x=>media(x,embed)));if(value&&typeof value==='object'){const out={};for(const [k,v] of Object.entries(value))out[k]=await media(v,embed);return out;}if(typeof value!=='string')return value;
if(embed&&/^director-media:\/\/image\/[a-f0-9]{64}\.(png|jpeg|webp)$/.test(value)){const name=new URL(value).pathname.slice(1),data=await fs.readFile(path.join(root,'media',name));return `data:image/${name.split('.').at(-1)};base64,${data.toString('base64')}`;}
const m=!embed&&value.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=\r\n]+)$/);if(m){const buffer=Buffer.from(m[2],'base64');if(buffer.length>8*1024*1024)throw Error('单张参考图超过8MB');const name=crypto.createHash('sha256').update(buffer).digest('hex')+'.'+m[1];await fs.mkdir(path.join(root,'media'),{recursive:true});await fs.writeFile(path.join(root,'media',name),buffer,{flag:'wx'}).catch(e=>{if(e.code!=='EEXIST')throw e;});return 'director-media://image/'+name;}return value;}
function open(file){const db=new DatabaseSync(file);db.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; CREATE TABLE IF NOT EXISTS records (kind TEXT NOT NULL,id TEXT NOT NULL,position INTEGER NOT NULL,body TEXT NOT NULL,hash TEXT NOT NULL,PRIMARY KEY(kind,id));');return db;}
async function save(project){const p=await media(C.normalize(project));await fs.mkdir(folder(p.id),{recursive:true});const db=open(path.join(folder(p.id),'project.sqlite'));try{db.exec('BEGIN IMMEDIATE');const old=db.prepare('SELECT kind,id,hash FROM records').all();const hashes=new Map(old.map(r=>[r.kind+':'+r.id,r.hash]));const keep=new Set();const upsert=db.prepare('INSERT INTO records VALUES(?,?,?,?,?) ON CONFLICT(kind,id) DO UPDATE SET position=excluded.position,body=excluded.body,hash=excluded.hash');const write=(kind,id,position,value)=>{const body=JSON.stringify(value),hash=crypto.createHash('sha256').update(position+body).digest('hex'),key=kind+':'+id;keep.add(key);if(hashes.get(key)!==hash)upsert.run(kind,id,position,body,hash);};const head={...p};for(const key of collections){delete head[key];p[key].forEach((item,i)=>write(key,item.id||String(i),i,item));}write('project',p.id,0,head);for(const row of old)if(!keep.has(row.kind+':'+row.id))db.prepare('DELETE FROM records WHERE kind=? AND id=?').run(row.kind,row.id);db.exec('COMMIT');}catch(e){try{db.exec('ROLLBACK');}catch{}throw e;}finally{db.close();}
const snapshots=path.join(folder(p.id),'snapshots');await fs.mkdir(snapshots,{recursive:true});const body=JSON.stringify(p),name=new Date().toISOString().replace(/[:.]/g,'-')+'.json';const temp=path.join(snapshots,'pending.tmp');await fs.writeFile(temp,body);await fs.rename(temp,path.join(snapshots,name));const names=(await fs.readdir(snapshots)).filter(x=>x.endsWith('.json')).sort();for(const file of names.slice(0,-12))await fs.unlink(path.join(snapshots,file));return p;}
async function readProject(id,dir=folder(id)){const file=path.join(dir,'project.sqlite');await fs.access(file);const db=new DatabaseSync(file,{readOnly:true});try{const rows=db.prepare('SELECT * FROM records ORDER BY position').all();const head=rows.find(r=>r.kind==='project');if(!head)throw Error('缺少项目头');const p=JSON.parse(head.body);for(const key of collections)p[key]=rows.filter(r=>r.kind===key).map(r=>JSON.parse(r.body));if(p.id!==id)throw Error('项目身份不匹配');if(Number(p.schemaVersion)>3)throw Error('需要较新版本程序');return C.normalize(p);}finally{db.close();}}
async function list(){issues=[];await fs.mkdir(path.join(root,'projects'),{recursive:true});const result=[];for(const e of await fs.readdir(path.join(root,'projects'),{withFileTypes:true})){if(!e.isDirectory()||!/^p_[\w-]+$/.test(e.name))continue;try{let exists=true;try{await fs.access(path.join(folder(e.name),'project.sqlite'));}catch{exists=false;}if(exists)result.push(await readProject(e.name));else{let p;try{p=JSON.parse(await fs.readFile(path.join(folder(e.name),'project.json'),'utf8'));}catch{p=JSON.parse(await fs.readFile(path.join(folder(e.name),'project.json.bak'),'utf8'));}if(p.id!==e.name)throw Error('项目目录身份不匹配');result.push(await save(p));}}catch(error){issues.push({id:e.name,error:error.message});}}return result.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));}
async function recoveryList(){await list();const records=[];for(const issue of issues){const files=await fs.readdir(path.join(folder(issue.id),'snapshots')).catch(()=>[]);records.push({...issue,snapshots:files.filter(f=>f.endsWith('.json')).sort().reverse()});}return records;}
async function recover(id,snapshot){valid(id);if(!/^[\w.-]+\.json$/.test(snapshot))throw Error('无效快照');const p=C.normalize(JSON.parse(await fs.readFile(path.join(folder(id),'snapshots',snapshot),'utf8')));p.id=C.id('p');p.name+='（恢复副本）';return save(p);}
const archiveRoot=()=>path.join(root,'archive');
const archiveKey=key=>{const match=String(key||'').match(/^(p_[\w-]+)_(\d{13})$/);if(!match)throw Error('无效归档项目');return {key:match[0],id:valid(match[1])};};
async function archive(id){valid(id);await fs.mkdir(archiveRoot(),{recursive:true});let time=Date.now(),key=id+'_'+time;while(await fs.access(path.join(archiveRoot(),key)).then(()=>true,()=>false))key=id+'_'+(++time);await fs.rename(folder(id),path.join(archiveRoot(),key));return key;}
async function archived(){await fs.mkdir(archiveRoot(),{recursive:true});const rows=[];for(const entry of await fs.readdir(archiveRoot(),{withFileTypes:true})){if(!entry.isDirectory())continue;let parsed;try{parsed=archiveKey(entry.name);}catch{continue;}let name=parsed.id;try{name=(await readProject(parsed.id,path.join(archiveRoot(),parsed.key))).name;}catch{}rows.push({key:parsed.key,projectId:parsed.id,name,archivedAt:new Date(Number(parsed.key.slice(-13))).toISOString()});}return rows.sort((a,b)=>b.archivedAt.localeCompare(a.archivedAt));}
async function unarchive(key){const item=archiveKey(key),source=path.join(archiveRoot(),item.key),stat=await fs.lstat(source);if(!stat.isDirectory()||stat.isSymbolicLink())throw Error('归档项目目录无效');await readProject(item.id,source);await fs.mkdir(path.join(root,'projects'),{recursive:true});try{await fs.access(folder(item.id));throw Error('同编号项目已存在，不能覆盖');}catch(error){if(error.code!=='ENOENT')throw error;}await fs.rename(source,folder(item.id));return readProject(item.id);}
async function removeArchived(key){const item=archiveKey(key),base=await fs.realpath(archiveRoot()),target=await fs.realpath(path.join(base,item.key));if(!target.startsWith(base+path.sep))throw Error('归档路径超出回收站');const stat=await fs.lstat(target);if(!stat.isDirectory()||stat.isSymbolicLink())throw Error('归档项目目录无效');await fs.rm(target,{recursive:true,force:false});return true;}
async function rawBackup(id){const files=[];const dir=folder(id);for(const e of await fs.readdir(dir,{withFileTypes:true})){if(e.isFile())files.push({name:e.name,data:await fs.readFile(path.join(dir,e.name))});}return files;}
return {save,list,recoveryList,recover,archive,archived,unarchive,removeArchived,media,rawBackup};};
