const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const PHASES=['第一期','第二期','第三期','第四期','第五期'];
const VIDEO=/\.(mp4|webm|mov|m4v)$/i,IMAGE=/\.(png|jpe?g|webp)$/i,DOC=/\.(docx|pdf|md|txt)$/i,TABLE=/\.xlsx$/i,AUDIO=/\.(mp3|m4a|wav)$/i;
function inside(base,file){const rel=path.relative(base,file);return rel&&!rel.startsWith('..'+path.sep)&&rel!=='..'&&!path.isAbsolute(rel);}
function role(file){const n=file.replaceAll('\\','/');if(VIDEO.test(n))return 'video';if(IMAGE.test(n))return /方法论|总结/.test(n)?'methodImage':'diagram';if(DOC.test(n))return /拉片文案|文案原文/.test(n)?'analysis':/脚本/.test(n)?'script':'document';if(TABLE.test(n))return 'table';if(AUDIO.test(n))return 'audio';return 'other';}
async function scanEpisode(dir,phase){const files=[];async function walk(current,depth){if(depth>6)return;for(const item of await fs.readdir(current,{withFileTypes:true})){if(item.name.startsWith('.')||item.name.startsWith('~$')||item.isSymbolicLink())continue;const full=path.join(current,item.name);if(item.isDirectory())await walk(full,depth+1);else if(item.isFile()){const rel=path.relative(dir,full),kind=role(rel);if(kind!=='other')files.push({name:item.name,relative:rel,kind});if(files.length>3000)throw Error('单集文件超过 3000 个：'+dir);}}}await walk(dir,0);const doc=files.find(f=>f.kind==='analysis')||files.find(f=>f.kind==='script'),id=crypto.createHash('sha256').update(dir).digest('hex').slice(0,20),title=(doc?.name.replace(/\.(docx|pdf|md|txt)$/i,'')||path.basename(dir)).replace(/^每日一镜\d+期\s*[:：｜|-]?\s*/,'');return {id,phase,number:Number(/每日一镜(\d+)期/.exec(path.basename(dir))?.[1]||0),title,dir,files};}
module.exports=function({root,read,write,documentText}){
 const config=()=>path.join(root(),'study-library.json');
 async function list(){return read(config(),{version:1,roots:[],episodes:[]});}
 async function register(paths){if(!Array.isArray(paths)||!paths.length||paths.length>10)throw Error('请选择 1—10 个资料目录');const old=await list(),roots=[...old.roots];for(const raw of paths){const dir=path.resolve(String(raw)),stat=await fs.lstat(dir);if(!stat.isDirectory()||stat.isSymbolicLink())throw Error('请选择普通文件夹');const real=await fs.realpath(dir);if(!roots.includes(real))roots.push(real);}const episodes=[];for(const base of roots){const phase=PHASES.find(x=>path.basename(base).startsWith(x))||path.basename(base);const entries=await fs.readdir(base,{withFileTypes:true});for(const item of entries){if(!item.isDirectory()||item.isSymbolicLink()||!/^每日一镜\d+期拉片资料/.test(item.name))continue;episodes.push(await scanEpisode(path.join(base,item.name),phase));if(episodes.length>500)throw Error('资料集超过 500 期，请分批整理');}}episodes.sort((a,b)=>a.number-b.number);const data={version:1,roots,episodes,updatedAt:new Date().toISOString()};await write(config(),data);return data;}
 async function fileFor(id,relative){const data=await list(),episode=data.episodes.find(e=>e.id===id);if(!episode)throw Error('拉片资料不存在');const entry=episode.files.find(f=>f.relative===relative);if(!entry)throw Error('文件不在本期资料索引中');const file=path.resolve(episode.dir,entry.relative);if(!inside(episode.dir,file))throw Error('无效文件路径');await fs.access(file).catch(()=>{throw Error('原文件已移动，请重新索引资料目录');});return {episode,entry,file};}
 async function text(id,relative){const {entry,file}=await fileFor(id,relative);if(!DOC.test(entry.name))throw Error('请选择文档');const stat=await fs.stat(file);if(stat.size>40*1024*1024)throw Error('文档过大');return (await documentText(file)).slice(0,120000);}
 async function image(id,relative){const {entry,file}=await fileFor(id,relative);if(!IMAGE.test(entry.name))throw Error('请选择图片');const stat=await fs.stat(file);if(stat.size>8*1024*1024)throw Error('图片超过 8MB，请打开原文件查看');const ext=path.extname(file).toLowerCase().slice(1).replace('jpg','jpeg');return 'data:image/'+ext+';base64,'+(await fs.readFile(file)).toString('base64');}
 return {list,register,fileFor,text,image};
};
