const STUDY={mode:'work',data:null,loading:false,selected:null,phase:'all',query:'',view:'overview',document:null,image:null,video:null};
async function studyLoad(refresh=false){if(STUDY.loading)return;STUDY.loading=true;try{STUDY.data=await call('study:list');if(refresh&&STUDY.data.roots.length)STUDY.data=await call('study:register',STUDY.data.roots);if(!STUDY.data.episodes.some(x=>x.id===STUDY.selected))STUDY.selected=STUDY.data.episodes[0]?.id||null;}finally{STUDY.loading=false;}if(S.page==='film')render();}
function studyCurrent(){return STUDY.data?.episodes.find(x=>x.id===STUDY.selected)||null;}
function studyFileButton(e,file,action,label=file.name){return btn(esc(label),action,`data-id="${e.id}" data-relative="${esc(file.relative)}" title="${esc(file.relative)}"`);}
function studyView(){
 const data=STUDY.data;if(!data)return pageHead('拉片资料库','正在读取本机索引…','');
 const episodes=data.episodes.filter(e=>(STUDY.phase==='all'||e.phase===STUDY.phase)&&(!STUDY.query||`${e.number} ${e.title}`.toLowerCase().includes(STUDY.query.toLowerCase()))),phases=['all',...new Set(data.episodes.map(e=>e.phase))],selected=episodes.find(x=>x.id===STUDY.selected)||episodes[0];if(selected)STUDY.selected=selected.id;
 const files=selected?.files||[],videos=files.filter(f=>f.kind==='video'),docs=files.filter(f=>['analysis','script','document'].includes(f.kind)),images=files.filter(f=>['diagram','methodImage'].includes(f.kind)),tables=files.filter(f=>['table','audio'].includes(f.kind));
 const list=(items,action)=>items.length?`<div class="study-file-list">${items.map(f=>studyFileButton(selected,f,action)).join('')}</div>`:'<p class="muted">本期暂无此类资料。</p>';
 const view=STUDY.view,sections={overview:'资料概览',video:'原片',notes:'文案与脚本',images:'拍剪图与方法图',tables:'拉片表与音频'};
 const overview=`<div class="study-overview">${[['video','原片',videos.length,'先看实际画面与声音'],['notes','文案与脚本',docs.length,'再读作者的逐镜解释'],['images','拍剪图与方法图',images.length,'对照图示理解机位和方法'],['tables','拉片表与音频',tables.length,'最后查原始表格与附件']].map(([key,title,count,desc],i)=>`<button class="study-overview-card" data-action="study-view" data-id="${key}"><span>0${i+1} / ${esc(title)}</span><strong>${count} 份</strong><small>${desc}</small></button>`).join('')}</div><p class="muted">按左侧顺序查看资料；自己的观察与作者的分析应分开记录。</p>`;
 const video=`<div class="study-section-head"><h3>原片 <small>${videos.length}</small></h3>${videos.length?studyFileButton(selected,videos[0],'study-make-film','用原片新建我的拉片练习'):''}</div>${list(videos,'study-video')}${STUDY.video?`<video class="study-video" controls preload="metadata" src="${esc(STUDY.video)}"></video>`:'<p class="study-preview-hint">选一条原片在这里播放，再按需要建立自己的拉片记录。</p>'}`;
 const notes=`<h3>拉片文案与脚本 <small>${docs.length}</small></h3>${list(docs,'study-document')}${STUDY.document?`<article class="study-document"><div class="section-head"><h3>${esc(STUDY.document.name)}</h3>${studyFileButton(selected,STUDY.document,'study-open','用原程序打开')}</div><pre>${esc(STUDY.document.text)}</pre></article>`:'<p class="study-preview-hint">选择文案后在此阅读。文案是学习资料，不会自动写进当前项目。</p>'}`;
 const pictures=`<h3>拍剪图与方法图 <small>${images.length}</small></h3>${images.length?`<div class="study-image-list">${images.map(f=>`<div>${studyFileButton(selected,f,'study-image')}${studyFileButton(selected,f,'study-open','原程序打开')}</div>`).join('')}</div>`:'<p class="muted">本期暂无图片资料。</p>'}${STUDY.image?`<figure class="study-image"><img src="${STUDY.image.data}" alt="${esc(STUDY.image.name)}"><figcaption>${esc(STUDY.image.name)}</figcaption></figure>`:'<p class="study-preview-hint">选择图片后在此放大查看。</p>'}`;
 const table=`<h3>拉片表与音频 <small>${tables.length}</small></h3>${list(tables,'study-open')}<p class="muted">表格和音频使用本机已安装的程序打开，不会在观澜里改写原文件。</p>`;
 return pageHead('五期拉片资料库',`${data.episodes.length} 期已索引 · 原文件仍在本机原位置。`,btn('添加期数目录','study-choose')+btn('重新索引','study-refresh'))+`<div class="study-notice">按期数选择 → 按类型查看 → 用原片新建自己的拉片练习。资料不会自动用于当前项目。</div><div class="study-filters"><input id="study-query" placeholder="搜索期号或标题" value="${esc(STUDY.query)}" aria-label="搜索拉片资料">${phases.map(p=>btn(p==='all'?'全部':p,'study-phase',`data-id="${esc(p)}"`,STUDY.phase===p?'active':'')).join('')}<small>${episodes.length} 期匹配</small></div><div class="study-layout"><div class="study-episodes">${episodes.map(e=>`<button class="study-episode ${selected?.id===e.id?'active':''}" data-action="study-select" data-id="${e.id}" aria-current="${selected?.id===e.id?'true':'false'}"><strong>${e.number}期 · ${esc(e.title)}</strong><small>${esc(e.phase)} · 原片 ${e.files.filter(f=>f.kind==='video').length} · 文案 ${e.files.filter(f=>['analysis','script','document'].includes(f.kind)).length} · 图 ${e.files.filter(f=>['diagram','methodImage'].includes(f.kind)).length} · 表 ${e.files.filter(f=>f.kind==='table').length}</small></button>`).join('')||'<p class="muted">没有匹配资料，请调整筛选或添加目录。</p>'}</div><div class="study-detail">${selected?`<div class="section-head"><div><h2>${selected.number}期 · ${esc(selected.title)}</h2><p class="muted">${esc(selected.phase)} · ${files.length} 个可用文件</p></div></div><div class="study-view-tabs" role="tablist">${Object.entries(sections).map(([key,label])=>btn(label,'study-view',`data-id="${key}" role="tab" aria-selected="${view===key}"`,view===key?'active':'')).join('')}</div><div class="study-view-body" role="tabpanel">${({overview,video,notes,images:pictures,tables:table})[view]||overview}</div>`:'<div class="study-empty">从左侧选一期，查看原片、文案、图示和拉片表。</div>'}</div></div>`;
}
const studyRenderBase=render;
render=function(){studyRenderBase();if(S.page!=='film')return;const content=$('content');if(!content)return;const bar=content.querySelector('.u80-context-bar');if(STUDY.mode==='library'){content.innerHTML=studyView();if(bar)content.prepend(bar);if(!STUDY.data&&!STUDY.loading)setTimeout(()=>studyLoad().catch(showError),0);}const tabs=document.createElement('div');tabs.className='study-tabs';tabs.innerHTML=btn('我的拉片练习','study-mode','data-id="work"',STUDY.mode==='work'?'active':'')+btn('五期资料库','study-mode','data-id="library"',STUDY.mode==='library'?'active':'');content.querySelector('.page-head')?.before(tabs);content.querySelector('#study-query')?.addEventListener('input',e=>{STUDY.query=e.target.value;const start=e.target.selectionStart;render();const input=$('study-query');input?.focus();input?.setSelectionRange(start,start);});};
const studyActBase=act;
act=async function(action,d={}){
 if(action==='study-mode'){STUDY.mode=d.id;render();return;}
 if(action==='study-view'){STUDY.view=d.id;render();return;}
 if(action==='study-choose'){const result=await call('study:choose');if(result){STUDY.data=result;STUDY.selected=result.episodes[0]?.id||null;render();}return;}
 if(action==='study-refresh'){await studyLoad(true);return;}
 if(action==='study-phase'){STUDY.phase=d.id;render();return;}
 if(action==='study-select'){STUDY.selected=d.id;STUDY.view='overview';STUDY.document=null;STUDY.image=null;STUDY.video=null;render();return;}
 if(action==='study-document'){const entry=studyCurrent()?.files.find(f=>f.relative===d.relative);if(!entry)return;STUDY.document={name:entry.name,relative:entry.relative,text:await call('study:text',{id:d.id,relative:d.relative})};STUDY.view='notes';render();return;}
 if(action==='study-image'){const entry=studyCurrent()?.files.find(f=>f.relative===d.relative);if(!entry)return;STUDY.image={name:entry.name,data:await call('study:image',{id:d.id,relative:d.relative})};STUDY.view='images';render();return;}
 if(action==='study-video'){STUDY.video=await call('study:video',{id:d.id,relative:d.relative});STUDY.view='video';render();return;}
 if(action==='study-open'){await call('study:open',{id:d.id,relative:d.relative});return;}
 if(action==='study-make-film'){const record=await call('study:makeFilm',{id:d.id,relative:d.relative});FILM.records.unshift(record);FILM.selected=record.id;FILM.shot=null;FILM.loaded=true;STUDY.mode='work';render();toast('已创建独立拉片练习，原资料仍保留在原目录');return;}
 return studyActBase(action,d);
};
