/* Independent tools column. Skills are text-only guidance; no imported script is executed. */
WS_PAGES.tools='AI 实验室';
function toolsView(){const skills=ASSISTANT.skills||[],files=ASSISTANT.files||[];return pageHead('观澜 AI 实验室','把脚本撰写、短片诊断和澜芯扩展集中在一个独立栏目；拉片学习仍在学习区。',btn('打开澜芯','assistant-toggle','','primary')+btn('模型中心','settings'))+
 `<div class="tools-grid"><section class="card tool-card"><small>创作技能 01</small><h2>AI 脚本编导</h2><p>从故事想法起草独立剧本，不覆盖正式原文；人工审阅后再纳入制作流程。</p>${btn('撰写剧本草稿','tool-script','','primary')}</section><section class="card tool-card"><small>创作技能 02</small><h2>AI 短片诊断</h2><p>对自己的成片逐项记录可见证据、问题与修改计划；没有模型也可手工使用。</p>${btn('打开短片诊断','page','data-page="diagnosis"','primary')}</section></div>`+
 `<section class="card"><div class="row wrap"><div class="grow"><h2>澜芯技能</h2><p class="muted">按技能用途决定何时使用；技能正文和参考文字仅供模型参考。导入的脚本不运行。</p></div>${btn('创建技能','skill-create','','primary')}${btn('加载 SKILL.md / ZIP','skill-import')}</div><div class="tool-skill-list">${skills.map(x=>`<article><div class="row"><strong class="grow">${esc(x.name)}</strong><span class="badge">${x.enabled?'已启用':'已停用'}</span></div><p>${esc(x.description)}</p><div class="toolbar">${btn('查看／编辑','skill-edit',`data-name="${esc(x.name)}"`)}${btn(x.enabled?'停用':'启用','skill-enable',`data-name="${esc(x.name)}" data-enabled="${!x.enabled}"`)}${x.source==='builtin'?'':btn('移除','skill-remove',`data-name="${esc(x.name)}"`)}</div></article>`).join('')||'<p class="muted">还没有自定义技能。可从澜芯创建，也可加载已有 SKILL.md。</p>'}</div></section>`+
 `<section class="card"><div class="row wrap"><div class="grow"><h2>澜芯文件</h2><p class="muted">选择文件后，在澜芯对话框勾选需要引用的文件；最多同时发送四份。文件仅保存在当前本机资料库。</p></div>${btn('Add 文件','assistant-add-file')}</div>${files.map(f=>`<div class="row tool-file-row"><span class="grow">${esc(f.name)}${f.truncated?' · 已截取前 10 万字符':''}</span>${btn('移除','assistant-remove-file',`data-id="${esc(f.id)}"`)}</div>`).join('')||'<p class="muted">尚未添加文件。支持 TXT、Markdown、Word 和文字型 PDF。</p>'}</section>`;}
const toolsRenderBase=render;
const TOOL_NAV_PATHS={box:'M3 7h18v14H3z M3 7l3-4h12l3 4 M9 12h6',script:'M5 3h10l4 4v14H5z M15 3v5h4 M8 12h8 M8 16h6',diagnosis:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M8 12l3 3 5-6'};
function toolNavIcon(name){return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${TOOL_NAV_PATHS[name]}"/></svg>`;}
render=function(){toolsRenderBase();const rail=$('nav');rail?.querySelector('.u80-nav-tools [data-page="diagnosis"]')?.remove();if(rail&&!rail.querySelector('.tools-nav')){const section=document.createElement('section');section.className='tools-nav';section.innerHTML=`<span class="learning-label">创作工具</span>${btn(toolNavIcon('box')+'<span>AI 实验室</span>','page','data-page="tools" aria-label="AI 实验室" title="AI 实验室"',S.page==='tools'?'active':'')}${btn(toolNavIcon('script')+'<span>脚本撰写</span>','tool-script','aria-label="脚本撰写" title="脚本撰写"')}${btn(toolNavIcon('diagnosis')+'<span>短片诊断</span>','page','data-page="diagnosis" aria-label="短片诊断" title="短片诊断"',S.page==='diagnosis'?'active':'')}`;(rail.querySelector('.learning-nav')||rail.querySelector('.u80-nav-tools'))?.before(section);}if(S.page==='tools')$('breadcrumb').textContent='本机工作区 / AI 实验室';};
function skillCreateDialog(idea=''){showModal('创建澜芯技能',`<p class="muted">参考导入的 skill-creator 结构：名称、触发用途、工作步骤、输出格式。技能保存后可在澜芯中使用。</p><div class="grid">${inputHtml('skill-name','英文技能名（小写字母和连字符）','')}${inputHtml('skill-title','显示标题','')}</div>${area('skill-description','何时使用 / 触发场景',idea?idea:'')}${area('skill-workflow','工作步骤（至少 20 字）','')}${area('skill-output','输出格式','')}<div class="toolbar">${btn('用已连接模型起草','skill-ai-draft','','small')}</div>`,async()=>{const item=await call('skills:save',{name:$('skill-name').value,title:$('skill-title').value,description:$('skill-description').value,workflow:$('skill-workflow').value,output:$('skill-output').value});await assistantResourcesLoad();render();toast('技能《'+item.name+'》已保存并启用');},true,'保存技能');}
const toolsActBase=act;
act=async function(action,d={}){
 if(action==='tool-script'){if(!S.project)return toolsActBase('new-project');await toolsActBase('page',{page:'home'});return toolsActBase('script-plan');}
 if(action==='assistant-skills'){if(ASSISTANT.open){S.page='tools';render();return;}ASSISTANT.open=true;assistantDraw();S.page='tools';render();return;}
 if(action==='skill-create'){skillCreateDialog(d.idea||'');if(S.settings.model&&d.idea&&d.idea.length>=8)try{await act('skill-ai-draft');}catch(e){toast('技能已打开，请手工填写；自动起草未完成：'+String(e.message||e));}return;}
 if(action==='skill-ai-draft'){if(!S.settings.model)throw Error('请先连接文字模型，或直接手工填写技能步骤');const description=$('skill-description').value.trim(),title=$('skill-title').value.trim();if(!description)throw Error('先填写技能用途或触发场景');const requestId=C.id('skill');const raw=await call('model:generate',{requestId,kind:'assistant',system:'为观澜工作台起草一个文本技能。只返回 JSON：{"name":"英文小写连字符","title":"中文标题","description":"触发用途","workflow":"分步骤工作流程","output":"输出格式"}。不得要求执行脚本、读取任意磁盘文件、调用未提供的工具或自动修改用户项目。',user:JSON.stringify({title,description})});const item=C.parseJson(raw);for(const [id,key] of [['skill-name','name'],['skill-title','title'],['skill-description','description'],['skill-workflow','workflow'],['skill-output','output']])if($(id))$(id).value=String(item[key]||'').slice(0,key==='workflow'?12000:4000);toast('已起草，请检查并保存');return;}
 if(action==='skill-import'){const item=await call('skills:import');if(item){await assistantResourcesLoad();render();toast('技能《'+item.name+'》已加载');}return;}
 if(action==='skill-edit'){const item=ASSISTANT.skills.find(x=>x.name===d.name);if(!item)throw Error('技能不存在');showModal('编辑技能 · '+item.name,`<p class="muted">直接编辑 SKILL.md。技能只提供文字指导，不执行代码。</p><label>技能正文<textarea id="skill-content" class="large" spellcheck="false">${esc(item.content)}</textarea></label>`,async()=>{const updated=await call('skills:save',{content:$('skill-content').value,source:item.source});await assistantResourcesLoad();render();toast('技能《'+updated.name+'》已更新');},true,'保存修改');return;}
 if(action==='skill-enable'){await call('skills:enable',{name:d.name,enabled:d.enabled==='true'});await assistantResourcesLoad();render();return;}
 if(action==='skill-remove'){confirmAction('移除技能','将从当前资料库移除《'+esc(d.name)+'》。',async()=>{await call('skills:remove',d.name);await assistantResourcesLoad();render();});return;}
 if(action==='assistant-add-file'){const added=await call('assistant:files:add');if(added.length){await assistantResourcesLoad();for(const x of added)ASSISTANT.selectedFiles.add(x.id);assistantDraw();render();toast('已添加 '+added.length+' 份文件');}return;}
 if(action==='assistant-remove-file'){await call('assistant:files:remove',d.id);await assistantResourcesLoad();render();return;}
 return toolsActBase(action,d);
};
