const USAGE={records:[],days:30,project:'all',loaded:false,demo:false};
const usageNumber=n=>new Intl.NumberFormat('zh-CN').format(n||0);
const usageKind={generation:'创作生成',diagnosis:'模型诊断',film:'拉片学习'};
function usageRows(){const since=USAGE.days?Date.now()-USAGE.days*86400000:0;return USAGE.records.filter(r=>Date.parse(r.at)>=since&&(USAGE.project==='all'||r.projectId===USAGE.project));}
function usageDemoRows(){const values=[[2100,620],[3600,980],[4200,1350],[3000,770],[5700,1500],[4900,1220],[6400,1820]];return values.map(([input,output],i)=>({at:new Date(Date.now()-(6-i)*86400000).toISOString(),projectId:'demo',projectName:'演示项目',kind:i%3?'generation':'diagnosis',model:'示例模型',input,output,estimated:false,cost:null,currency:'CNY'})).reverse().filter(r=>!USAGE.days||Date.parse(r.at)>=Date.now()-USAGE.days*86400000);}
function usagePrice(rows){const map=new Map();for(const r of rows)if(r.cost!=null)map.set(r.currency,(map.get(r.currency)||0)+r.cost);return map.size?[...map].map(([currency,cost])=>`${currency} ${cost.toFixed(4)}`).join(' / '):'未配置单价';}
function usageView(){
 const rows=USAGE.demo?usageDemoRows():usageRows(),input=rows.reduce((n,r)=>n+r.input,0),output=rows.reduce((n,r)=>n+r.output,0),estimated=rows.filter(r=>r.estimated).length;
 const byDay=new Map(),byModel=new Map(),byProject=new Map();
 for(const r of rows){const day=r.at.slice(0,10);byDay.set(day,(byDay.get(day)||0)+r.input+r.output);const modelKey=r.model+'\0'+r.currency,m=byModel.get(modelKey)||{name:r.model,currency:r.currency,requests:0,input:0,output:0,cost:0,priced:false};m.requests++;m.input+=r.input;m.output+=r.output;if(r.cost!=null){m.cost+=r.cost;m.priced=true;}byModel.set(modelKey,m);const project=r.projectName||usageKind[r.kind]||'本机工作区',q=byProject.get(project)||{name:project,requests:0,tokens:0};q.requests++;q.tokens+=r.input+r.output;byProject.set(project,q);}
 const projectOptions={'all':'全部项目',...Object.fromEntries((USAGE.demo?rows:USAGE.records).filter(r=>r.projectId).map(r=>[r.projectId,r.projectName||r.projectId]))};
 const days=USAGE.days||Math.max(1,Math.min(90,Math.ceil((Date.now()-Date.parse(rows.at(-1)?.at||new Date()))/86400000)+1));
 const series=Array.from({length:days},(_,i)=>{const date=new Date(Date.now()-(days-1-i)*86400000).toISOString().slice(0,10);return {date,count:byDay.get(date)||0};}),maximum=Math.max(1,...series.map(x=>x.count));
 return pageHead('Token 用量','仅统计观澜自身的文字模型调用；不读取 WorkBuddy 或其他软件的日志。',btn('刷新','usage-refresh')+btn('导出明细 CSV','usage-export',USAGE.demo?'disabled':''))+
 `<div class="usage-mode"><div><strong>${USAGE.demo?'演示视图':'真实用量'}</strong><p>${USAGE.demo?'以下是界面演示数据，不是实际调用，不会保存、计费或导出。':'即使尚未连接模型，也可以使用本页筛选、查看空状态和预览布局。'}</p></div>${btn(USAGE.demo?'返回真实用量':'预览有数据时的界面','usage-demo')}</div>`+
 `<div class="usage-filters">${[[1,'今天'],[7,'近 7 天'],[30,'近 30 天'],[0,'全部']].map(([n,label])=>btn(label,'usage-range',`data-days="${n}"`,USAGE.days===n?'active':'')).join('')}<label>项目<select id="usage-project">${opts(projectOptions,USAGE.project)}</select></label></div>`+
 `<div class="usage-kpis"><section><small>总 Token</small><strong>${usageNumber(input+output)}</strong><span>${rows.length} 次成功调用</span></section><section><small>输入 Token</small><strong>${usageNumber(input)}</strong><span>实际 ${rows.length-estimated} 次 / 估算 ${estimated} 次</span></section><section><small>输出 Token</small><strong>${usageNumber(output)}</strong><span>包含模型诊断</span></section><section><small>按设置单价估算</small><strong class="usage-cost">${esc(usagePrice(rows))}</strong><span>不等于服务商账单</span></section></div>`+
 `<section class="card"><div class="section-head"><h2>每日用量</h2><span class="muted">单位：Token</span></div><div class="usage-chart ${rows.length?'':'usage-chart-empty'}" role="img" aria-label="每日 Token 用量柱状图">${rows.length?series.map(x=>`<div class="usage-column" title="${x.date}：${usageNumber(x.count)} Token"><span data-height="${Math.max(x.count?3:0,100*x.count/maximum)}"></span></div>`).join(''):'<p class="muted">这一时间范围暂无调用记录</p>'}</div><div class="usage-axis"><span>${series[0]?.date||''}</span><span>${series.at(-1)?.date||''}</span></div></section>`+
 `<div class="usage-tables"><section class="card"><h2>按模型统计</h2><div class="table-scroll"><table><thead><tr><th>模型</th><th>调用</th><th>输入</th><th>输出</th><th>费用估算</th></tr></thead><tbody>${[...byModel.values()].sort((a,b)=>b.input+b.output-a.input-a.output).map(m=>`<tr><td>${esc(m.name)}</td><td>${m.requests}</td><td>${usageNumber(m.input)}</td><td>${usageNumber(m.output)}</td><td>${m.priced?`${m.currency} ${m.cost.toFixed(4)}`:'未配置单价'}</td></tr>`).join('')||'<tr><td colspan="5">当前时间范围尚无用量。</td></tr>'}</tbody></table></div></section><section class="card"><h2>按项目统计</h2><div class="table-scroll"><table><thead><tr><th>项目 / 操作</th><th>调用</th><th>Token</th></tr></thead><tbody>${[...byProject.values()].sort((a,b)=>b.tokens-a.tokens).map(q=>`<tr><td>${esc(q.name)}</td><td>${q.requests}</td><td>${usageNumber(q.tokens)}</td></tr>`).join('')||'<tr><td colspan="3">暂无记录。</td></tr>'}</tbody></table></div></section></div>`+
 `<section class="card"><h2>最近调用</h2><div class="table-scroll"><table><thead><tr><th>时间</th><th>项目 / 类型</th><th>模型</th><th>输入 / 输出</th><th>来源</th></tr></thead><tbody>${rows.slice(0,100).map(r=>`<tr><td>${esc(new Date(r.at).toLocaleString('zh-CN'))}</td><td>${esc(r.projectName||usageKind[r.kind]||'本机工作区')}</td><td>${esc(r.model)}</td><td>${usageNumber(r.input)} / ${usageNumber(r.output)}</td><td>${r.estimated?'本地估算':'服务商返回'}</td></tr>`).join('')||'<tr><td colspan="5">调用成功后会自动记录。</td></tr>'}</tbody></table></div><p class="muted">服务商未返回完整用量时，估算值仅供趋势参考。失败、取消和服务商重试计费的请求可能无法计入本机记录。</p></section>`;
}
async function usageLoad(){USAGE.records=(await call('usage:list')).sort((a,b)=>b.at.localeCompare(a.at));USAGE.loaded=true;}
const usageRenderBase=render;
render=function(){usageRenderBase();const tool=document.querySelector('.u80-nav-tools');if(tool&&!tool.querySelector('[data-action="usage-dashboard"]'))tool.insertAdjacentHTML('beforeend',btn('Token 用量','usage-dashboard','',S.page==='usage'?'active':''));if(S.page!=='usage')return;WS_PAGES.usage='Token 用量';$('breadcrumb').textContent='本机工作区 / Token 用量';$('content').innerHTML=usageView();document.querySelectorAll('.usage-column span').forEach(el=>el.style.height=el.dataset.height+'%');document.getElementById('usage-project')?.addEventListener('change',e=>{USAGE.project=e.target.value;render();});};
const usageActBase=act;
act=async function(action,d={}){if(action==='usage-dashboard'){if($('modal').open)closeModal();S.page='usage';await usageLoad();render();return;}if(action==='usage-demo'){USAGE.demo=!USAGE.demo;USAGE.project='all';render();return;}if(action==='usage-refresh'){await usageLoad();render();return;}if(action==='usage-range'){USAGE.days=Number(d.days)||0;render();return;}if(action==='usage-export'){if(USAGE.demo)return;const quote=v=>'"'+String(v??'').replace(/^([=+\-@])/,"'$1").replace(/"/g,'""')+'"';const columns=['时间','项目','类型','模型','输入Token','输出Token','是否估算','估算费用','币种'];const csv='\ufeff'+[columns,...usageRows().map(r=>[r.at,r.projectName||'',usageKind[r.kind]||r.kind,r.model,r.input,r.output,r.estimated?'是':'否',r.cost??'',r.currency])].map(row=>row.map(quote).join(',')).join('\r\n');await call('files:export',{name:'观澜-Token用量',format:'csv',text:csv});return;}const result=await usageActBase(action,d);if(action==='sidebar-tools')document.querySelector('#modal-body .sidebar-tools-menu section:nth-child(2)')?.insertAdjacentHTML('beforeend',btn('Token 用量','usage-dashboard'));return result;};
