/* Object-centred workspaces. UI state is separate from project content. */
const U80={mode:WS.preferences.mode||'standard',plan:'draft',refQuery:'',refKind:'all',filmTab:'work',filmReport:'overview',filmNote:'observation',filmQuery:'',assetPick:{},assetCompare:{},batch:new Set(),undo:null,videoUrls:new Map(),resultCompare:[],settingsTab:'identity',scrolls:{}};
const U80_MODES={standard:'标准专业',focus:'专注生成',batch:'批量分镜'};
const U80_PRESETS={standard:{left:240,right:320,bottom:160,leftOpen:true,rightOpen:true},focus:{left:220,right:320,bottom:112,leftOpen:false,rightOpen:true},batch:{left:220,right:320,bottom:320,leftOpen:false,rightOpen:true}};
const u80Esc=FilmReport.esc;
function u80ModeControls(){return `<label class="u80-mode">工作区<select id="u80-mode">${opts(U80_MODES,U80.mode)}</select></label>`;}
function u80Scroll(){return Object.fromEntries(['main','.ws-preview-body','.ws-inspector-body','.ws-shot-list','.ws-sequence-track','.asset-detail','.u80-asset-results','.u80-film-notes','.u80-film-report','#nav'].map(sel=>{const e=document.querySelector(sel);return [sel,e?[e.scrollTop,e.scrollLeft]:[0,0]];}));}
function u80RestoreScroll(values){for(const [sel,v]of Object.entries(values||{})){const e=document.querySelector(sel);if(e){e.scrollTop=v[0];e.scrollLeft=v[1];}}}
const u80Snapshot=routeSnapshot;routeSnapshot=function(){return {...u80Snapshot(),panelScroll:u80Scroll(),assetTab:UI.assetTab,assetQuery:WS.assetQuery,assetFilter:S.filter,filmTab:U80.filmTab,filmReport:U80.filmReport,plan:U80.plan};};
navigateHistory=async function(direction){if(S.job||S.storageBusy)throw Error('请先完成或停止任务');const stack=direction==='back'?EXPERIENCE.back:EXPERIENCE.forward,other=direction==='back'?EXPERIENCE.forward:EXPERIENCE.back;if(!stack.length)return;await persist();const dest=stack.at(-1);if(dest.project&&!S.projects.some(x=>x.id===dest.project))throw Error('原项目已不在当前资料库');stack.pop();other.push(routeSnapshot());EXPERIENCE.replay=true;try{S.project=S.projects.find(x=>x.id===dest.project)||null;S.page=dest.page;S.assetId=dest.asset;S.seqId=dest.seq;S.filter=dest.assetFilter||'all';UI.assetTab=dest.assetTab||'design';Object.assign(WS,{tab:dest.tab,param:dest.param,view:dest.view,assetQuery:dest.assetQuery||''});Object.assign(U80,{filmTab:dest.filmTab||'work',filmReport:dest.filmReport||'overview',plan:dest.plan||'draft'});DWUI.view=dest.view==='flow'?'flow':'board';FILM.selected=dest.film;FILM.shot=dest.shot;if(S.project)WS.selected[S.project.id]=dest.wsShot;DWUI.selected=dest.dwShot;DWUI.query=dest.query||'';DWUI.status=dest.status||'all';HELP.chapter=dest.help||'start';render();u80RestoreScroll(dest.panelScroll);document.querySelector('main').scrollTop=dest.scroll||0;}finally{EXPERIENCE.replay=false;EXPERIENCE.current=routeSnapshot();}};

const u80OldPreview=wsPreview;
function u80ResultComparison(results){const selected=U80.resultCompare.map(id=>results.find(x=>x.id===id)).filter(Boolean);if(selected.length!==2)return results.length>1?'<p class="muted">选择两条记录可并排核对版本。</p>':'';return `<div class="u80-result-compare" aria-label="同镜头两版成片对照">${selected.map(x=>`<section><strong>${esc(x.file.name)}</strong><small>${esc(x.at||'')} · ${esc(x.model||'未记录模型')}</small>${U80.videoUrls.has(x.id)?`<video controls preload="metadata" src="${esc(U80.videoUrls.get(x.id))}"></video>`:btn('加载本机视频','u80-result-play',`data-id="${x.id}"`)}<p>${esc(x.reason)}</p><details><summary>本版实际提示词</summary><pre class="source">${esc(x.prompt)}</pre></details></section>`).join('')}</div>`;}
wsPreview=function(r){if(!r)return u80OldPreview(r);const draft=S.project.workstationDrafts?.[r.sh.id];
 if(WS.tab==='plan'){const value=U80.plan==='draft'&&draft?{...r,sh:{...r.sh,...draft.values}}:r;const changes=draft?WK.fields.filter(k=>String(draft.values[k])!==String(r.sh[k])):[];return `<div class="u80-version-bar"><strong>${value===r?'正式方案':'编辑草稿 · 尚未采用'}</strong>${draft?btn(U80.plan==='draft'?'查看正式版本':'查看编辑草稿','u80-plan')+`<span>${changes.length} 项修改</span>`:''}</div>${u80OldPreview(value)}${draft?`<details class="u80-diff"><summary>查看 ${changes.length} 项修改对照</summary>${changes.map(k=>`<div><strong>${esc(C.shotFields[k]||{duration:'计划时长',reactions:'人物反应'}[k]||k)}</strong><div class="ws-compare"><p><small>正式</small><br>${esc(r.sh[k]||'空')}</p><p><small>草稿</small><br>${esc(draft.values[k]||'空')}</p></div></div>`).join('')}</details>`:''}`;}
 if(WS.tab==='reference')return u80OldPreview(r)+`<div class="toolbar">${S.project.assets.filter(a=>r.s.assetIds.includes(a.id)||(r.sh.directorRefs||[]).some(x=>x.id===a.id)).map(a=>btn('查看 '+esc(a.name),'u80-open-asset',`data-id="${a.id}"`)).join('')}</div>`;
 if(WS.tab==='result'){const results=(S.project.videoResults||[]).filter(x=>x.segmentId===r.g.id&&(x.shot?.id?x.shot.id===r.sh.id:x.shotIndex===r.j));return `<h2>成片检查</h2><p class="muted">播放已关联的本机视频，结合当时提示词记录返工点。</p>${u80ResultComparison(results)}${results.map(x=>`<section class="ws-seam"><div class="row"><strong class="grow">${esc(x.file.name)}</strong>${badge({pending:'待检查',pass:'可用',revise:'需返工',fail:'不可用'}[x.decision]||x.decision,'draft')}</div>${U80.videoUrls.has(x.id)?`<video class="u80-result-video" controls preload="metadata" src="${esc(U80.videoUrls.get(x.id))}"></video>`:btn('加载本机视频','u80-result-play',`data-id="${x.id}"`)}<p>${esc(x.reason)}</p>${btn(U80.resultCompare.includes(x.id)?'取消对照':'选择对照','u80-result-compare',`data-id="${x.id}"`)}${btn('修改反馈','u80-result-feedback',`data-id="${x.id}"`)}<details><summary>生成时的提示词与来源</summary><pre class="source">${esc(x.prompt)}</pre><p>${esc(x.file.path)}</p></details></section>`).join('')||'<p class="empty-inline">尚无成片。可在下方用当前镜头生成候选，或关联外部视频后播放并记录反馈。</p>'}${btn('关联本机成片并记录反馈','result-new',`data-id="${r.g.id}" data-index="${r.j}"`)}${btn('批量关联外部成片','result-batch')}${btn('批量导出逐镜提示词','result-export-prompts')}`;}
 return u80OldPreview(r);
};
const u80Inspector=wsInspector;wsInspector=function(r){let html=u80Inspector(r);if(WS.param==='ai'&&r){html=html.replace('<div class="ws-ref-list">',`<div class="u80-ref-filter"><input id="u80-ref-query" aria-label="搜索引用资产" placeholder="搜索引用资产" value="${esc(U80.refQuery)}"><select id="u80-ref-kind" aria-label="引用资产类型">${opts({all:'全部类型',...labels},U80.refKind)}</select><small id="u80-ref-count"></small></div><div class="ws-ref-list">`);}return html;};
function u80FilterRefs(){const p=S.project;if(!p)return;let visible=0,selected=[];document.querySelectorAll('[data-ws-ref]').forEach(el=>{const a=p.assets.find(x=>x.id===el.dataset.wsRef);if(!a)return;const show=(U80.refKind==='all'||a.kind===U80.refKind)&&a.name.toLowerCase().includes(U80.refQuery.toLowerCase());el.closest('label').hidden=!show;if(show)visible++;if(el.checked)selected.push(a.name);});if($('u80-ref-count'))$('u80-ref-count').textContent=`${visible} 项匹配 · 已选 ${selected.length} 项：${selected.join('、')||'无'}`;}

function u80FilmNotes(f,shot){return `<div class="ws-panel-head"><strong>${shot?'镜 '+(f.shots.indexOf(shot)+1)+' · 观察与分析':'片段分析'}</strong>${btn('保存','film-save','','small')}</div><div class="u80-film-note-tabs">${Object.entries({observation:'逐镜笔记',methods:'导演方法'}).map(([id,name])=>btn(name,'u80-film-note',`data-id="${id}"`,U80.filmNote===id?'active':'')).join('')}</div><div class="u80-film-note-body"><div ${U80.filmNote==='methods'?'hidden':''}>${shot?`<div class="grid"><label>开始（秒）<input type="number" step="0.001" data-film-shot="${shot.id}" data-film-field="start" value="${shot.start}"></label><label>结束（秒）<input type="number" step="0.001" data-film-shot="${shot.id}" data-film-field="end" value="${shot.end}"></label></div><label>人工观察<textarea data-film-shot="${shot.id}" data-film-field="observation" placeholder="先写看见、听见的事实，再分析它的作用">${esc(shot.observation||'')}</textarea></label><details><summary>专业视听字段 · 景别、表演、声音、接续</summary>${Object.entries(FilmReport.fields).map(([key,label])=>`<label>${label}<textarea data-film-shot="${shot.id}" data-film-field="${key}">${esc(shot[key]||'')}</textarea></label>`).join('')}</details><details ${shot.analysis?'open':''}><summary>AI 分析草稿 · 待核对</summary><label>分析内容<textarea class="large" data-film-shot="${shot.id}" data-film-field="analysis">${esc(shot.analysis||'')}</textarea></label>${shot.aiFields&&Object.keys(shot.aiFields).length?`<p class="muted">结构化建议需审阅，不覆盖已填写的人工记录。</p>${btn('审阅并填入空白专业字段','u80-film-fields',`data-id="${shot.id}"`)}`:''}</details><div class="toolbar">${btn('补充本镜采样图','u80-film-frames',f.sourceVideo?'':'disabled')}${btn('与下一镜合并','film-merge',`data-id="${shot.id}" ${f.shots.at(-1)===shot?'disabled':''}`)}</div>`:'<p class="empty-inline">先添加镜头或识别切点，再逐镜记录。</p>'}</div><div ${U80.filmNote==='methods'?'':'hidden'}><label>参考名称<input data-film-field="name" maxlength="120" value="${esc(f.name)}"></label><label>标签<input data-film-field="tags" value="${esc(f.tags||'')}"></label><label>整体叙事与节奏<textarea data-film-field="summary">${esc(f.summary||'')}</textarea></label><label>可复用导演方法<textarea class="large" data-film-field="methods">${esc(f.methods||'')}</textarea></label><label>适用条件与不适用情况<textarea data-film-field="limitations">${esc(f.limitations||'')}</textarea></label></div><label class="check"><input id="film-reviewed" type="checkbox" ${f.reviewed?'checked':''}>已核对原片、分析与方法</label><div class="toolbar">${btn('存入导演参考库','film-publish','','primary')}${S.project?btn('用于当前项目','film-enable'):''}</div><p class="muted">AI 只分析采样图和笔记，不读取音轨。方法入库后需显式启用。</p></div>`;}
const u80FilmNotesBase=u80FilmNotes;
u80FilmNotes=function(f,shot){return u80FilmNotesBase(f,shot).replace('<label>可复用导演方法',`<label>结构段落复盘<textarea class="large" data-film-field="structure" placeholder="按时间段写：段落任务、信息变化、情绪变化，以及对应镜号">${esc(f.structure||'')}</textarea></label><label>可复用导演方法`);};
function u80FilmShots(f){return f.shots.map((s,i)=>`<button class="film-shot ${s.id===(FILM.shot||f.shots[0]?.id)?'active':''}" data-action="film-shot" data-id="${s.id}">${s.frames?.[0]?`<img src="${esc(s.frames[0])}" alt="镜 ${i+1} 采样图">`:'<span class="u80-no-frame">未提取采样图</span>'}<b>镜 ${String(i+1).padStart(2,'0')} · ${(s.end-s.start).toFixed(2)}s</b><small>${FilmReport.time(s.start)} → ${FilmReport.time(s.end)}</small></button>`).join('')||'<p class="empty-inline">添加整段镜头，或在上方“拆镜设置”识别候选切点。</p>';}
filmView=function(){if(!FILM.loaded&&!FILM.loading)setTimeout(()=>filmLoad().catch(showError),0);const f=filmCurrent(),shot=f?.shots.find(x=>x.id===FILM.shot)||f?.shots[0];const top=pageHead('拉片学习','看片与记录同屏，分析可核对，方法可复用',btn('导入视频','film-import','','primary')+btn('导入分析资料','u80-film-import')+(f?btn('导出带图 Excel','film-export'):''));if(!f)return top+'<section class="card u80-onboarding-empty"><h2>从一个好片段开始</h2><p>导入视频 → 校正切点 → 逐镜观察 → 审阅 AI 草稿 → 查看报告 → 导出或存入方法库。</p><p>支持可解码 MP4、WebM、MOV。导入视频只保存在本机；分析前会说明发送的采样图数量。</p></section>';
 const tabs=`<div class="u80-film-heading"><strong title="${esc(f.name)}">${esc(f.name)}</strong>${badge(f.reviewed?'已复核':'待复核',f.reviewed?'green':'warn')}<span class="grow"></span>${btn('看片与记录','u80-film-tab','data-id="work"',U80.filmTab==='work'?'active':'')}${btn('交付报告','u80-film-tab','data-id="report"',U80.filmTab==='report'?'active':'')}${btn('重新关联视频','u80-film-relink')}</div>`;
 if(U80.filmTab==='report')return top+tabs+`<div class="u80-report-tabs">${Object.entries({overview:'整体解读',table:'镜头总表',shots:'逐镜图文',methods:'导演方法',all:'完整报告'}).map(([id,name])=>btn(name,'u80-film-report',`data-id="${id}" aria-pressed="${U80.filmReport===id}"`,U80.filmReport===id?'active':'')).join('')}</div><div class="u80-film-report">${FilmReport.sections(f,U80.filmReport)}</div>`;
 return top+tabs+`<div class="u80-film-work"><section class="ws-panel u80-film-monitor"><div class="ws-panel-head"><strong>原片监看</strong><span id="film-clock">${FilmReport.time(f.playhead)}</span></div>${f.sourceVideo?`<video id="film-player" controls preload="metadata" src="${esc(f.sourceVideo)}"></video>`:'<p class="empty-inline">分析资料已导入，原视频未包含。点击“重新关联视频”即可继续看片。</p>'}<div class="toolbar">${btn('前一帧','film-step','data-delta="-1"')}${btn('后一帧','film-step','data-delta="1"')}<label>步进帧率<select id="film-fps">${opts({24:'24',25:'25',30:'30',60:'60'},f.fps||25)}</select></label>${btn('播放当前镜','u80-film-play')}${btn('当前位置切镜','film-cut')}${btn('添加整段镜头','film-whole')}</div><details class="u80-cut-settings"><summary>拆镜设置与 AI 分析</summary><div class="grid">${inputHtml('film-start','起点（秒）',f.rangeStart||0,'number')}${inputHtml('film-end','终点（秒）',f.rangeEnd||Math.min(f.duration||30,120),'number')}<label>切点敏感度<select id="film-threshold">${opts({0.1:'高',0.18:'标准',0.3:'低'},f.threshold||.18)}</select></label></div><div class="toolbar">${btn('本机识别候选切点','film-detect')}${btn('AI分析镜头','film-analyze','','primary')}</div><p class="muted">每0.5秒采样找切点，每次最多120秒。AI每镜仅接收两张图和笔记，不读取音轨。切点、运镜与声音须人工核对。</p></details></section><section class="ws-panel u80-film-notes">${u80FilmNotes(f,shot)}</section><section class="ws-panel u80-film-sequence"><div class="ws-panel-head"><strong>${f.shots.length} 镜 · 选择即定位</strong><span>采样图不是精确首尾帧</span></div><div class="film-shot-grid">${u80FilmShots(f)}</div></section></div>`;};

function u80AssetResults(a){const images=a.generatedImages||[],chosen=images.find(x=>x.id===U80.assetPick[a.id])||images.at(-1),compare=images.find(x=>x.id===U80.assetCompare[a.id]),ref=a.references[0];return `<section class="ws-panel u80-asset-results"><div class="ws-panel-head"><strong>候选图与定版参考</strong>${btn('生成资产图片','asset-image','','primary')}</div><div class="u80-asset-compare"><figure><span>候选 ${chosen?images.indexOf(chosen)+1:'—'}</span>${chosen?`<img src="${esc(chosen.data)}" alt="当前候选图">`:'<p class="empty-inline">尚无候选图。先完成右侧设计，再生成图片。</p>'}</figure><figure><span>${compare?'对比候选 '+(images.indexOf(compare)+1):'已采用参考'}</span>${compare||ref?`<img src="${esc((compare||ref).data)}" alt="对比图片">`:'<p class="empty-inline">尚无参考图</p>'}</figure></div>${chosen?`<div class="u80-candidate-meta"><p>${esc(chosen.model)} · ${esc(chosen.size)} · 设计依据 v${chosen.assetRevision||'未记录'} ${badge(a.references.some(x=>x.generationId===chosen.id)?'已采用':'候选','draft')}</p><div class="toolbar">${btn('采用为参考图','image-adopt',`data-id="${chosen.id}" ${a.status==='confirmed'||a.references.some(x=>x.generationId===chosen.id)?'disabled':''}`,'primary')}${btn('导出图片','image-export',`data-id="${chosen.id}"`)}${a.status==='confirmed'?btn('解锁后调整','u80-unlock-asset'):''}</div><details><summary>本次提示词与生成依据</summary><p class="pre">${esc(chosen.prompt)}</p></details></div>`:''}<div class="u80-candidates">${images.map((x,i)=>`<div><button data-action="u80-candidate" data-id="${x.id}" class="${chosen?.id===x.id?'active':''}"><img src="${esc(x.data)}" alt="候选${i+1}"><span>候选 ${i+1}</span></button>${btn('加入对比','u80-candidate-compare',`data-id="${x.id}"`,'small')}</div>`).join('')}</div><div class="toolbar">${btn('查看已采用参考图','asset-tab','data-id="references"')}${btn('配置生图模型','model-kind','data-kind="image"')}${compare?btn('恢复参考对比','u80-candidate-compare','data-id=""'):''}</div><p class="muted">此生图入口发送文字提示词，不上传参考图。候选采用后仍需核对人物与场景连续性。</p></section>`;}

function u80Navigation(){const p=S.project,nav=$('nav');let title='当前工作',content='';if(S.page==='film'){title='我的拉片';content=`<input id="u80-film-query" aria-label="搜索拉片" placeholder="搜索拉片" value="${esc(U80.filmQuery)}">`+FILM.records.map(f=>btn(esc(f.name),'film-select',`data-id="${f.id}" data-film-name="${esc(f.name.toLowerCase())}"`,filmCurrent()?.id===f.id?'active':'')).join('');}
 else if(p&&['workbench','canvas','shots','review','delivery','prompts'].includes(S.page)){title='场景与片段';content=p.sequences.map(s=>btn(esc(s.title),'u80-scene',`data-id="${s.id}"`,S.seqId===s.id?'active':'')).join('')||'<p class="muted">先分析剧本并建立场景。</p>';}
 else if(S.page==='assets'){title='资产工作';content='<p class="muted">左侧列表选择资产，中间比较图片，右侧修改设计。</p>'+btn('全部资产','filter-assets','data-id="all"')+Object.entries(labels).map(([id,n])=>btn(n,'filter-assets',`data-id="${id}"`,S.filter===id?'active':'')).join('');}
 else{title='项目与资料';content=btn('剧本与记忆','page','data-page="home"',S.page==='home'?'active':'')+(p?'<p class="muted">'+esc(p.name)+'</p>':'');}
 nav.innerHTML=`<div class="u80-context-nav"><h3>${title}</h3>${content}</div><details class="u80-nav-tools" ${['memory','facts','methods','knowledge','rules','prompts','history','recovery','guide'].includes(S.page)?'open':''}><summary title="项目资料、交付与帮助">资料与记录</summary>${[['memory','故事记忆'],['facts','已确认事实'],['methods','导演方法'],['knowledge','参考资料'],['rules','创作约束'],['prompts','提示词输出'],['history','任务记录'],['recovery','资料恢复'],['guide','使用指南']].map(([id,n])=>btn(n,'page',`data-page="${id}" title="${n}"`,S.page===id?'active':'')).join('')}</details><button class="u80-rail-menu" data-action="u80-side-menu" title="打开对象与资料" aria-label="打开对象与资料">${icon('menu')}</button>`;
 nav.insertAdjacentHTML('afterbegin',`<div class="u80-canvas-entry">${btn('◇ <span>无限画布</span>','page',`data-page="canvas" aria-label="无限画布" ${S.page==='canvas'?'aria-current="page"':''}`,S.page==='canvas'?'active':'')}</div>`);
 nav.querySelectorAll('button').forEach(b=>{const label=b.textContent.trim();b.title=b.title||label;if(label&&!b.hasAttribute('aria-label'))b.setAttribute('aria-label',label);});
 document.querySelectorAll('.aside-bottom button').forEach(b=>{b.dataset.compactLabel='管理';});
 if($('u80-film-query'))document.querySelectorAll('[data-film-name]').forEach(b=>b.hidden=!b.dataset.filmName.includes(U80.filmQuery.toLowerCase()));
}
function u80BatchTable(){const rows=dwRows();return `<div class="u80-batch-tools">${btn('选择当前筛选全部','u80-batch-all')}${btn('清空选择','u80-batch-clear')}${btn('批量修改','u80-batch-edit','', 'primary')}${btn('撤销本次批量','u80-batch-undo',U80.undo?.project===S.project.id?'':'disabled')}<span id="u80-batch-count">已选 ${rows.filter(x=>U80.batch.has(x.sh.id)).length} 镜</span></div><div class="u80-batch-scroll"><table><thead><tr><th>选择</th><th>场景 / 镜头</th><th>时长</th><th>画面</th><th>运镜</th><th>状态</th></tr></thead><tbody>${rows.map(r=>`<tr class="${r.sh.id===wsCurrent()?.sh.id?'selected':''}"><td><input type="checkbox" data-u80-batch="${r.sh.id}" aria-label="选择镜头 ${r.j+1}" ${U80.batch.has(r.sh.id)?'checked':''}></td><td>${btn(esc(r.s.title)+' / '+(r.s.segments.indexOf(r.g)+1)+'-'+(r.j+1),'ws-select',`data-shot="${r.sh.id}"`)}</td><td>${wsTime(r.sh.duration)}</td><td>${esc(r.sh.frame)}</td><td>${esc(r.sh.motion)}</td><td>${dwStatus(r.g)}</td></tr>`).join('')}</tbody></table></div>`;}

const u80BaseRender=render;
render=function(){const same=EXPERIENCE.current&&routeKey(EXPERIENCE.current)===routeKey(routeSnapshot()),scroll=same?u80Scroll():null;u80BaseRender();document.body.dataset.workspace=U80.mode;document.body.dataset.page=S.page;document.body.classList.add('u80');document.body.classList.toggle('u80-small',innerWidth<1400);document.body.classList.toggle('u80-neutral',PRODUCT.personal.neutralPreview!==false);u80Navigation();
 const active=WS_PAGES[S.page]||'工作区',r=S.project&&S.page==='workbench'?wsCurrent():null,a=S.page==='assets'?selectedAsset():null;const context=`${S.project?.name||'本机工作区'} / ${active}${r?' / '+r.s.title+' / 片段 '+(r.s.segments.indexOf(r.g)+1)+' / 镜 '+(r.j+1):a?' / '+a.name+' · v'+a.revision:''}`;const bar=document.createElement('div');bar.className='u80-context-bar';bar.innerHTML=`<span title="${esc(context)}">${esc(context)}</span>${r?btn('前往本片段规划','u80-to-planning','','small'):''}${['review','delivery'].includes(S.page)?btn('返回当前镜头','u80-return-shot','','small'):''}`;$('content').prepend(bar);
 if(S.page==='workbench'&&WS.view==='studio'&&S.project){const tool=document.querySelector('.ws-toolbar');tool.innerHTML=u80ModeControls()+btn('镜头列表','ws-toggle','data-side="left"')+btn('参数面板','ws-toggle','data-side="right"')+'<span class="grow"></span>'+moreMenu(btn('故事板总览','ws-view','data-view="board"')+btn('工作流总览','ws-view','data-view="flow"')+btn('紧凑／标准序列','u80-sequence-density')+btn('保存当前布局','u80-layout-save')+btn('恢复本模式布局','u80-layout-reset')+btn('恢复全部布局','ws-reset')+btn('参数草稿','ws-drafts')+btn('资料与记录','ws-tools')+btn('操作说明','guide-chapter','data-chapter="directing"'));if(U80.mode==='batch'){document.querySelector('.ws-sequence-track').outerHTML='<div class="u80-batch">'+u80BatchTable()+'</div>';}else{const timeline=WK.timeline(dwRows());document.querySelectorAll('.ws-clip').forEach((b,i)=>{const row=timeline[i];if(row){const prev=i?timeline[i-1]:null,changes=prev?DW.seam(prev.sh.stateOut,row.sh.stateIn).filter(x=>x.changed).length:0;b.querySelector('.clamp')?.remove();b.insertAdjacentHTML('beforeend','<span class="u80-seam-status">'+(i===0?'开场镜头':changes?'接缝 '+changes+' 项待核对':'检查首尾状态')+'</span>');}});}u80FilterRefs();}
 if(S.page==='assets'&&selectedAsset()){const detail=document.querySelector('.asset-detail'),split=document.querySelector('.split');document.querySelector('.asset-generation')?.remove();if(split&&detail){split.classList.add('u80-asset-work');detail.insertAdjacentHTML('beforebegin',u80AssetResults(selectedAsset()));detail.classList.add('ws-panel');detail.querySelector('[data-action="asset-image"]')?.remove();}}
 if(S.page==='film'){document.querySelector('.guide-context')?.remove();const v=$('film-player');if(v){v.addEventListener('timeupdate',()=>{if(U80.filmStop!=null&&v.currentTime>=U80.filmStop){v.pause();U80.filmStop=null;}});}if(!filmCurrent()?.sourceVideo)document.querySelectorAll('[data-action="film-step"],[data-action="film-cut"],[data-action="film-whole"],[data-action="film-detect"],[data-action="film-analyze"],[data-action="u80-film-play"]').forEach(b=>b.disabled=true);}
 document.querySelectorAll('.u80-result-video').forEach(v=>v.addEventListener('error',()=>{v.insertAdjacentHTML('afterend','<p class="note">无法解码此视频，请转为 H.264 MP4 后重新关联。</p>');},{once:true}));
 if(scroll)u80RestoreScroll(scroll);EXPERIENCE.current=routeSnapshot();};

const u80Appearance=appearanceApply;appearanceApply=function(p){u80Appearance(p);const root=document.documentElement,bg=WS.preferences.theme==='dark'?'#20242a':'#f8f9fa';const lum=h=>{const a=colorRGB(h).map(n=>{n/=255;return n<=.04045?n/12.92:((n+.055)/1.055)**2.4;});return a[0]*.2126+a[1]*.7152+a[2]*.0722;};const ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);let accent=/^#[a-f\d]{6}$/i.test(p.accent||'')?p.accent:'#75bcae';const to=WS.preferences.theme==='dark'?255:0,initial=colorRGB(accent);for(let n=0;n<=100&&ratio(accent,bg)<4.5;n+=5){accent='#'+initial.map(v=>Math.round(v+(to-v)*n/100).toString(16).padStart(2,'0')).join('');}root.style.setProperty('--brand',accent);root.style.setProperty('--focus',accent);root.style.setProperty('--on-brand',ratio(accent,'#101214')>=ratio(accent,'#ffffff')?'#101214':'#ffffff');document.body.classList.toggle('u80-neutral',p.neutralPreview!==false);};
const u80PersonalValues=personalValues;personalValues=function(){return {...u80PersonalValues(),neutralPreview:$('person-neutral')?.checked??PRODUCT.personal.neutralPreview!==false};};
const u80PersonalCenter=personalCenter;personalCenter=async function(draft=null){await u80PersonalCenter(draft);const body=$('modal-body');body.querySelector('#person-theme')?.closest('.grid')?.insertAdjacentHTML('afterend',`<label class="check"><input id="person-neutral" type="checkbox" ${(draft||PRODUCT.personal).neutralPreview!==false?'checked':''}>创作中性显示：画面检查区固定中性色，不叠加背景图片</label>`);const blocks=[...body.children],container=document.createElement('div');container.className='u80-settings-layout';container.innerHTML='<nav class="u80-settings-nav">'+Object.entries({identity:'个人资料',appearance:'外观与阅读',preferences:'工作习惯',connections:'连接与帮助'}).map(([id,n])=>btn(n,'u80-settings-tab',`data-id="${id}"`,U80.settingsTab===id?'active':'')).join('')+'</nav><div class="u80-settings-content"></div>';let section='identity';for(const node of blocks){if(node.tagName==='H3')section='appearance';if(node.tagName==='DETAILS'&&node.textContent.includes('更多偏好'))section='preferences';if(node.classList.contains('toolbar')&&node.querySelector('[data-action="settings"]'))section='connections';node.dataset.settingSection=section;container.lastElementChild.append(node);}body.append(container);u80SettingsShow();};
function u80SettingsShow(){document.querySelectorAll('[data-setting-section]').forEach(el=>el.hidden=el.dataset.settingSection!==U80.settingsTab);document.querySelectorAll('[data-action="u80-settings-tab"]').forEach(b=>b.classList.toggle('active',b.dataset.id===U80.settingsTab));document.querySelectorAll('#modal-body input[type="range"]').forEach(el=>{let n=el.nextElementSibling;if(!n||!n.classList.contains('u80-range-value')){n=document.createElement('output');n.className='u80-range-value';el.after(n);}n.textContent=el.value+(el.id==='person-blur'?'px':'%');});const details=document.querySelector('[data-setting-section="preferences"]');if(details)details.open=true;}

const u80Connection=connectionEditor;connectionEditor=function(kind,id){u80Connection(kind,id);const body=$('modal-body');body.classList.add('u80-connection-form');const advanced=document.createElement('details');advanced.className='u80-connection-advanced';advanced.innerHTML='<summary>高级连接设置 · 协议、运行位置与密钥清除</summary>';for(const key of ['conn-provider','conn-adapter','conn-chat-adapter','conn-clear']){const el=$(key)?.closest('label');if(el)advanced.append(el);}body.append(advanced);const apply=$('conn-apply');if(apply){const handler=apply.onclick;apply.addEventListener('click',()=>{body.querySelector('#conn-name')?.focus();toast('预设已应用，请核对配置并填写对应密钥。');});} };

const u80Act=act;act=async function(action,d={}){
 if(action==='sidebar-tools'){showModal('工作区与项目管理',`<div class="sidebar-tools-menu"><section><h3>项目维护</h3><p class="muted">从独立备份恢复项目资料。</p>${btn('导入项目备份','restore-project')}</section><section><h3>工作区设置</h3><p class="muted">模型连接与本机资料位置。</p>${btn('模型中心','settings')}${btn('资料存储位置','data-folder')}</section><section><h3>支持</h3>${btn('意见反馈','product-feedback')}</section></div>`,null);return;}
 if(['film-shot','film-select','film-step','u80-film-tab','u80-film-relink','page','ws-go','nav-back','nav-forward'].includes(action))U80.filmStop=null;
 if((S.job||S.storageBusy)&&['u80-film-import','u80-film-relink','u80-film-fields','u80-film-frames','u80-result-feedback'].includes(action))throw Error('请等待当前任务完成后再修改资料');
 if(EXPERIENCE.current&&routeKey(EXPERIENCE.current)===routeKey(routeSnapshot()))EXPERIENCE.current=routeSnapshot();
 if(action==='nav-collapse'&&innerWidth<1400)return act('u80-side-menu');
 if(action==='ws-toggle'&&d.side==='left'&&innerWidth<1400){showModal('镜头列表',`<p class="muted">窄窗口使用对象列表，选择后回到检查区。</p><div class="ws-tool-menu">${dwRows().map(r=>btn(esc(r.s.title)+' · '+(r.j+1),'ws-select',`data-shot="${r.sh.id}"`)).join('')}</div>`,null,true);return;}
 if(['ws-select','film-select','filter-assets'].includes(action)&&$('modal').open)closeModal();
 if(action==='u80-side-menu'){showModal('创作方式与资料',btn('无限画布','ws-go','data-page="canvas"','primary')+document.querySelector('.u80-context-nav').innerHTML.replace('id="u80-film-query"','id="u80-film-query-dialog"')+'<div class="ws-tool-menu">'+[['memory','故事记忆'],['facts','已确认事实'],['methods','导演方法'],['knowledge','参考资料'],['rules','创作约束'],['prompts','提示词输出'],['history','任务记录'],['recovery','资料恢复'],['guide','使用指南']].map(([page,n])=>btn(n,'ws-go',`data-page="${page}"`)).join('')+'</div>',null);return;}
 if(action==='u80-settings-tab'){U80.settingsTab=d.id;u80SettingsShow();return;}
 if(action==='u80-unlock-asset')return act('confirm-asset');
 if(action==='u80-plan'){U80.plan=U80.plan==='draft'?'formal':'draft';render();return;}
 if(action==='u80-open-asset'){await persist();S.assetId=d.id;S.page='assets';render();return;}
 if(action==='u80-return-shot'){S.page='workbench';WS.view='studio';render();return;}
 if(action==='u80-to-planning'){S.seqId=wsCurrent()?.s.id;S.page='shots';render();return;}
 if(action==='u80-scene'){if($('modal').open)closeModal();const r=DW.rows(requireProject()).find(x=>x.s.id===d.id);S.seqId=d.id;if(r){DWUI.query='';DWUI.status='all';WS.selected[S.project.id]=r.sh.id;}if(S.page==='workbench')render();else{S.page='shots';render();}return;}
 if(['u80-layout-save','u80-layout-reset','u80-sequence-density','ws-reset'].includes(action)){if(action==='u80-layout-save'){WS.preferences.layouts||={};WS.preferences.layouts[U80.mode]=Object.fromEntries(['left','right','bottom','leftOpen','rightOpen'].map(k=>[k,WS.preferences[k]]));toast('当前模式布局已保存');}else if(action==='u80-sequence-density')WS.preferences.bottom=WS.preferences.bottom<=120?184:112;else{if(action==='ws-reset'){WS.preferences.layouts={};U80.mode='standard';}Object.assign(WS.preferences,U80_PRESETS[U80.mode]);WS.preferences.mode=U80.mode;}wsPrefs();render();return;}
 if(action==='u80-candidate'||action==='u80-candidate-compare'){(action==='u80-candidate'?U80.assetPick:U80.assetCompare)[selectedAsset().id]=d.id;render();return;}
 if(action==='u80-result-compare'){const selected=U80.resultCompare.filter(id=>id!==d.id);if(!U80.resultCompare.includes(d.id))selected.push(d.id);U80.resultCompare=selected.slice(-2);render();return;}
 if(action==='u80-result-play'){await persist();U80.videoUrls.set(d.id,await call('results:preview',{projectId:requireProject().id,resultId:d.id}));render();return;}
 if(action==='u80-result-feedback'){const p=requireProject(),x=p.videoResults.find(r=>r.id===d.id);showModal('成片反馈',`<p>${esc(x.file.name)}</p><label>人工判断<select id="u80-decision">${opts({pending:'待检查',pass:'可用',revise:'需返工',fail:'不可用'},x.decision)}</select></label>${area('u80-feedback','实际表现与返工点',x.reason)}`,async()=>{const reason=$('u80-feedback').value.trim();if(!reason)throw Error('请填写观察结果');x.reason=reason;x.decision=$('u80-decision').value;await persist();render();});return;}
 if(action.startsWith('u80-batch-'))return u80BatchAction(action);
 if(action==='film-export'){const f=filmCurrent();if(!f)throw Error('请先导入片段');await filmSave();showModal('导出拉片报告',`<p><strong>${esc(f.name)}</strong> · ${f.shots.length} 镜 · ${f.reviewed?'已复核':'草稿，导出将保留待复核标识'}</p><label>交付格式<select id="u80-export-format">${opts({html:'图文阅读报告 HTML · 可离线打开',pdf:'打印与分享 PDF · 图文分页',csv:'逐镜分析表 CSV · 表格软件可编辑',xlsx:'逐镜拉片 Excel · 推荐，截图、逐镜解释、结构与方法',zip:'完整资料包 ZIP · 报告、表格、关键帧与资料',md:'文字笔记 Markdown',json:'结构化分析资料 JSON · 用于备份与导入'},'xlsx')}</select></label><p>报告包含整体解读、节奏统计、镜头总表、逐镜图文与导演方法。只导出已有记录，不会自动补写未知信息。</p><p class="muted">不包含原视频、密钥或本机绝对路径。关键帧保持原比例，采样图不等于准确首尾帧。分享前核对素材使用权限。</p>`,async()=>{await filmSave();const file=await call('film:export',{id:f.id,format:$('u80-export-format').value});if(file)toast('报告已保存：'+file);},true,'保存报告');return;}
 if(action==='u80-film-import'){await filmSave();const f=await call('film:restore');if(f){FILM.records.unshift(f);FILM.selected=f.id;FILM.shot=null;FILM.loaded=true;U80.filmTab='report';S.page='film';render();}return;}
 if(action==='u80-film-relink'){const f=filmCurrent();await filmSave();const next=await call('film:relink',f.id);if(next){Object.assign(f,next);U80.filmTab='work';render();}return;}
 if(action==='u80-film-tab'){await filmSave();U80.filmTab=d.id;render();return;}
 if(action==='u80-film-report'){U80.filmReport=d.id;render();return;}
 if(action==='u80-film-note'){U80.filmNote=d.id;const f=filmCurrent();document.querySelector('.u80-film-notes').innerHTML=u80FilmNotes(f,f.shots.find(x=>x.id===FILM.shot)||f.shots[0]);return;}
 if(action==='film-shot'){const f=filmCurrent(),shot=f.shots.find(x=>x.id===d.id);if(!shot)return;await filmSave();FILM.shot=shot.id;f.playhead=shot.start;const v=$('film-player');if(v){v.pause();if(Number.isFinite(v.duration))v.currentTime=Math.min(shot.start,v.duration-.02);}const notes=document.querySelector('.u80-film-notes');if(notes){notes.innerHTML=u80FilmNotes(f,shot);document.querySelectorAll('.film-shot').forEach(b=>b.classList.toggle('active',b.dataset.id===shot.id));}else render();return;}
 if(action==='u80-film-play'){const f=filmCurrent(),s=f.shots.find(x=>x.id===FILM.shot)||f.shots[0],v=$('film-player');if(!s||!v||!Number.isFinite(v.duration))throw Error('请先拆镜并加载视频');U80.filmStop=s.end;v.currentTime=s.start;await v.play();return;}
 if(action==='u80-film-frames'){const f=filmCurrent(),s=f.shots.find(x=>x.id===FILM.shot)||f.shots[0];if(!s||!f.sourceVideo)throw Error('请先选择镜头并关联视频');filmValidate(f);return filmTask('提取镜头采样图',async()=>{const v=await filmDecoder(f);try{s.frameTimes=[s.start+(s.end-s.start)*.2,s.start+(s.end-s.start)*.8];s.frames=[await filmFrame(v,s.frameTimes[0]),await filmFrame(v,s.frameTimes[1])];f.reviewed=false;}finally{v.remove();}});}
 if(action==='u80-film-fields'){const f=filmCurrent(),s=f.shots.find(x=>x.id===d.id);showModal('审阅结构化分析建议',Object.entries(s.aiFields||{}).map(([k,v])=>`<h3>${esc(FilmReport.fields[k]||k)}</h3><p class="pre">${esc(v)}</p>`).join('')+'<p>仅填入空白字段，已写人工观察保持不变；声音字段仍需自行听辨。</p>',async()=>{for(const [k,v]of Object.entries(s.aiFields||{}))if(k!=='sound'&&!s[k])s[k]=v;filmDirty();await filmSave();render();},true,'填入空白字段');return;}
 const result=await u80Act(action,d);if(['ws-select','ws-step','ws-list-page'].includes(action)){document.querySelector('.ws-shot-row.active')?.scrollIntoView({block:'nearest'});document.querySelector('.ws-clip.active')?.scrollIntoView({block:'nearest',inline:'nearest'});}return result;
};
async function u80BatchAction(action){const p=requireProject(),rows=dwRows();if(action==='u80-batch-all'){rows.forEach(r=>U80.batch.add(r.sh.id));render();return;}if(action==='u80-batch-clear'){U80.batch.clear();render();return;}if(S.job||S.storageBusy)throw Error('请等待当前任务完成');if(action==='u80-batch-undo'){const u=U80.undo;if(!u||u.project!==p.id)throw Error('没有可撤销的批量修改');if(C.hash({...p,updatedAt:''})!==u.after)throw Error('项目已有后续修改，为避免覆盖，请从片段历史恢复');Object.assign(p,C.clone(u.before));U80.undo=null;await persist();render();return;}const chosen=rows.filter(r=>U80.batch.has(r.sh.id));if(!chosen.length)throw Error('请先选择镜头');const fields={duration:'计划时长（秒）',camera:'机位',motion:'运镜',continuity:'连续性约束'};showModal('批量修改 '+chosen.length+' 个镜头',`<p>范围：${esc([...new Set(chosen.map(r=>r.s.title))].join('、'))}。只应用勾选的字段，采用后需复核。</p>`+Object.entries(fields).map(([k,n])=>{const vals=[...new Set(chosen.map(r=>String(r.sh[k]||'')))];return `<label class="check"><input type="checkbox" data-batch-field="${k}">修改${n}${vals.length>1?' · 当前为混合值':''}</label><input id="batch-${k}" type="${k==='duration'?'number':'text'}" value="${vals.length===1?esc(vals[0]):''}" placeholder="${vals.length>1?'混合值，请填写统一值':''}">`;}).join(''),async()=>{const keys=[...document.querySelectorAll('[data-batch-field]:checked')].map(x=>x.dataset.batchField);if(!keys.length)throw Error('请勾选要修改的字段');const values=Object.fromEntries(keys.map(k=>[k,k==='duration'?Number($('batch-'+k).value):$('batch-'+k).value]));if(keys.includes('duration')&&(!Number.isFinite(values.duration)||values.duration<=0||values.duration>3600))throw Error('计划时长需大于0且不超过3600秒');if(chosen.some(r=>p.workstationDrafts?.[r.sh.id]))throw Error('所选镜头含未采用参数草稿，请先处理草稿');const before=C.clone(p),groups=new Set();try{for(const r of chosen){if(!groups.has(r.g.id)){snapshotSegment(r.g);groups.add(r.g.id);}const draft=WK.draft(C,DW,p,r);Object.assign(draft.values,values);WK.apply(C,DW,p,r.sh.id,draft);}await persist();U80.undo={project:p.id,before,after:C.hash({...p,updatedAt:''})};render();toast('已批量修改 '+chosen.length+' 镜，可撤销本次批量');}catch(e){Object.assign(p,before);throw e;}},true,'应用到 '+chosen.length+' 镜');}

document.addEventListener('input',e=>{const el=e.target;if(el.dataset.wsField&&S.project&&!S.job){U80.plan='draft';const panel=document.querySelector('.ws-preview-body');if(panel&&WS.tab==='plan'){const top=panel.scrollTop;panel.innerHTML=wsPreview(wsCurrent());panel.scrollTop=top;}}if(el.id==='u80-ref-query'){U80.refQuery=el.value;u80FilterRefs();}if(['u80-film-query','u80-film-query-dialog'].includes(el.id)){U80.filmQuery=el.value;document.querySelectorAll('[data-film-name]').forEach(b=>b.hidden=!b.dataset.filmName.includes(el.value.toLowerCase()));}if(el.type==='range'&&el.id.startsWith('person-'))u80SettingsShow();});
document.addEventListener('change',e=>{const el=e.target;if(el.id==='u80-mode'){WS.preferences.layouts||={};WS.preferences.layouts[U80.mode]=Object.fromEntries(['left','right','bottom','leftOpen','rightOpen'].map(k=>[k,WS.preferences[k]]));U80.mode=el.value;WS.preferences.mode=U80.mode;Object.assign(WS.preferences,WS.preferences.layouts[U80.mode]||U80_PRESETS[U80.mode]);if(U80.mode==='focus')WS.tab='reference';wsPrefs();render();}if(el.id==='u80-ref-kind'){U80.refKind=el.value;u80FilterRefs();}if(el.dataset.wsRef)u80FilterRefs();if(el.dataset.u80Batch){el.checked?U80.batch.add(el.dataset.u80Batch):U80.batch.delete(el.dataset.u80Batch);if($('u80-batch-count'))$('u80-batch-count').textContent='已选 '+dwRows().filter(x=>U80.batch.has(x.sh.id)).length+' 镜';}});
document.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key)||e.altKey||e.ctrlKey||e.target.getAttribute('role')!=='tab')return;const tabs=[...e.target.closest('[role="tablist"]').querySelectorAll('[role="tab"]')],i=tabs.indexOf(e.target),next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;e.preventDefault();const action=tabs[next].dataset.action,data={...tabs[next].dataset};act(action,data).then(()=>document.querySelector(`[data-action="${action}"][aria-selected="true"]`)?.focus()).catch(showError);});
window.addEventListener('resize',()=>document.body.classList.toggle('u80-small',innerWidth<1400));

