/* Shared navigation, local task history and recoverable status across workspaces. */
WS_PAGES.projects='项目库';
const NEW_PROJECT={imported:null};
const HUB={panel:'',filter:'active',projectQuery:'',remote:[],loading:false,loadError:'',saved:new Map(),saveSerial:new Map(),read:new Set(),returnFocus:null};
try{HUB.read=new Set(JSON.parse(localStorage.getItem('guanlan-hub-read')||'[]'));}catch{}

function hubClock(value){const date=new Date(value||'');return Number.isNaN(date.getTime())?'—':date.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
function hubTaskRows(){
 const projectName=new Map(S.projects.map(p=>[p.id,p.name]));
 const local=S.projects.flatMap(p=>(p.jobs||[]).map(job=>({id:job.id,projectId:p.id,project:p.name,name:job.name||'AI 任务',kind:'ai',status:job.status||'unknown',at:job.finishedAt||job.startedAt||'',error:job.error||'',source:'history'})));
 const remote=new Map([...HUB.remote,...(VIDEO.jobs||[])].map(job=>[job.id,job]));
 const video=[...remote.values()].map(job=>({id:job.id,projectId:job.projectId,project:projectName.get(job.projectId)||'已移除项目',name:job.canvasNodeId?'画布生视频':'逐镜生视频',kind:'video',status:job.status||'unknown',at:job.updatedAt||job.createdAt||'',error:job.error||'',source:job.canvasNodeId?'canvas':'workbench',shotId:job.shotId||''}));
 return [...local,...video].sort((a,b)=>String(b.at).localeCompare(String(a.at)));
}
function hubTaskGroup(status){if(['submitting','queued','running'].includes(status))return 'active';if(['completed','succeeded'].includes(status))return 'done';return 'failed';}
function hubTaskLabel(row){return row.kind==='video'?videoJobLabel(row.status):({running:'进行中',completed:'已完成',failed:'失败',cancelled:'已停止'}[row.status]||row.status);}
const hubToolsBase=toolsView;
toolsView=function(){const rows=hubTaskRows().slice(0,6);return hubToolsBase()+`<section class="card hub-lab-jobs"><div class="section-head"><div><h2>最近任务</h2><p class="muted">脚本、诊断及其他 AI 任务使用本机真实记录；视频任务可在顶部任务队列查看。</p></div>${btn('查看全部任务','hub-queue')}</div>${rows.length?`<div class="hub-lab-job-list">${rows.map(row=>`<article><div><strong>${esc(row.name)}</strong><small>${esc(row.project)} · ${hubClock(row.at)}</small></div><span class="badge ${hubTaskGroup(row.status)==='failed'?'failed':hubTaskGroup(row.status)==='done'?'green':'info'}">${esc(hubTaskLabel(row))}</span>${btn('打开来源','hub-open-task',`data-id="${esc(row.id)}"`,'small')}</article>`).join('')}</div>`:'<p class="empty-inline">暂无任务。使用上方工具后，实际执行记录会显示在这里。</p>'}</section>`;};
function hubNotices(){
 const notices=[];
 for(const p of S.projects){let saved=[];try{saved=JSON.parse(localStorage.getItem('guanlan-canvas-messages-'+p.id)||'[]');}catch{}
  for(const item of Array.isArray(saved)?saved:[])if(item?.id&&item.text)notices.push({id:item.id,projectId:p.id,project:p.name,text:item.text,at:item.at||'',kind:item.kind||'info',read:Boolean(item.read)||HUB.read.has(item.id)});
 }
 for(const row of hubTaskRows())if(['done','failed'].includes(hubTaskGroup(row.status))){const id='task-'+row.id+'-'+row.status;notices.push({id,taskId:row.id,projectId:row.projectId,project:row.project,text:row.name+' · '+hubTaskLabel(row),at:row.at,kind:hubTaskGroup(row.status)==='failed'?'error':'info',read:HUB.read.has(id)});}
 return notices.sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,120);
}
function hubBadgeCounts(){return {active:hubTaskRows().filter(x=>hubTaskGroup(x.status)==='active').length,unread:hubNotices().filter(x=>!x.read).length};}
async function hubLoadJobs(){if(HUB.loading)return;HUB.loading=true;HUB.loadError='';hubPanelRender();try{const projects=[...S.projects],results=[];for(let i=0;i<projects.length;i+=4)results.push(...await Promise.allSettled(projects.slice(i,i+4).map(p=>call('video:list',p.id))));HUB.remote=results.flatMap(x=>x.status==='fulfilled'&&Array.isArray(x.value)?x.value:[]);if(results.some(x=>x.status==='rejected'))HUB.loadError='部分项目的视频任务暂未读取，当前列表可能不完整。';}finally{HUB.loading=false;hubPanelRender();hubBadges();}}
function projectLibraryView(){const q=HUB.projectQuery.trim().toLowerCase(),rows=[...S.projects].filter(p=>!q||[p.name,p.script||'',profiles[p.selectedProfile]||''].join(' ').toLowerCase().includes(q)).sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')));return `<section class="hub-projects"><div class="hub-page-head"><div><span class="dashboard-kicker">PROJECT LIBRARY / 本机项目</span><h1>项目库</h1><p>从上次停下的位置继续；剧本、资产、逐镜制作与自由画布属于同一个项目，但各有独立入口。</p></div><div class="hub-page-actions">${btn('查看回收站','hub-trash')}${btn('新建项目','new-project','','primary')}</div></div><div class="hub-project-search"><label for="hub-project-query">搜索项目</label><input id="hub-project-query" type="search" placeholder="输入项目名、作品品类或剧本文字" value="${esc(HUB.projectQuery)}"><span>${rows.length} / ${S.projects.length} 个项目</span></div>${rows.length?`<div class="hub-project-grid">${rows.map(p=>{const stats=dashboardStats(p);return `<article class="hub-project-card"><div class="hub-project-card-head"><span>${esc(profiles[p.selectedProfile]||'创作项目')}</span><time>${hubClock(p.updatedAt)}</time></div><h2 title="${esc(p.name)}">${esc(p.name)}</h2><p>${p.script?.trim()?'剧本已导入':'尚未导入剧本'} · ${stats.shots} 镜 · ${stats.assets} 项资产 · ${stats.results} 条成片记录</p><div class="hub-project-actions">${btn('继续逐镜','dashboard-open',`data-id="${esc(p.id)}" data-target="workbench"`,'primary')}${btn('自由画布','dashboard-open',`data-id="${esc(p.id)}" data-target="canvas"`)}${btn('剧本与要素','dashboard-open',`data-id="${esc(p.id)}" data-target="home"`)}${btn('删除项目','hub-delete-project',`data-id="${esc(p.id)}"`,'small danger')}</div></article>`;}).join('')}</div>`:`<div class="global-library-empty"><strong>${S.projects.length?'没有匹配项目':'还没有项目'}</strong><p>${S.projects.length?'换个关键词试试。':'先新建一个项目，再从剧本或自由画布开始。'}</p>${S.projects.length?'':btn('创建第一个项目','new-project','','primary')}</div>`}</section>`;}
function hubNavMount(){const nav=$('nav');if(!nav)return;for(const selector of ['.dashboard-nav-entry','.u80-canvas-entry','.learning-nav','.global-library-nav','.tools-nav'])nav.querySelector(selector)?.remove();const active=S.page,globalPage=['dashboard','projects','library','tools'].includes(active);if(globalPage||['home','assets'].includes(active)){nav.querySelector('.u80-context-nav')?.remove();}if(globalPage)nav.querySelector('.u80-nav-tools')?.remove();const group=document.createElement('div');group.className='hub-primary-nav';group.innerHTML='<small>创作空间</small>'+[['dashboard','home','首页'],['projects','projects','项目库'],['canvas','canvas','无限画布'],['library','library','统一资产库']].map(([page,glyph,name])=>btn(`${icon(glyph)}<span>${name}</span>`,'page',`data-page="${page}" title="${name}" aria-label="${name}" ${active===page?'aria-current="page"':''}`,active===page?'active':'')).join('')+'<small>工具与学习</small>'+[['tools','lab','AI 实验室'],['film','film','拉片学习']].map(([page,glyph,name])=>btn(`${icon(glyph)}<span>${name}</span>`,'page',`data-page="${page}" title="${name}" aria-label="${name}" ${active===page?'aria-current="page"':''}`,active===page?'active':'')).join('');nav.prepend(group);}
function hubSaveText(){if(!S.project)return '本机工作区';const value=HUB.saved.get(S.project.id)||S.project.updatedAt;return value?'已保存 · '+hubClock(value):'本机保存';}
function hubBadges(){const counts=hubBadgeCounts();for(const [kind,count] of [['queue',counts.active],['messages',counts.unread]]){const button=document.querySelector('[data-action="hub-'+kind+'"]');if(button){button.querySelector('.hub-count')?.replaceChildren(String(count));button.setAttribute('aria-label',(kind==='queue'?'任务队列':'消息中心')+'，'+count+(kind==='queue'?' 项进行中':' 条未读'));}}}
function hubChromeMount(){
 const row=document.querySelector('main>header>.row');if(!row)return;row.querySelector('.hub-header-actions')?.remove();row.querySelector('[data-action="help"]')?.remove();row.querySelector('[data-action="about"]')?.remove();
 if(['dashboard','projects','library','tools'].includes(S.page)){const breadcrumb=$('breadcrumb');if(breadcrumb)breadcrumb.textContent='创作空间 / '+({dashboard:'首页',projects:'项目库',library:'统一资产库',tools:'AI 实验室'}[S.page]);}
 const counts=hubBadgeCounts();row.insertAdjacentHTML('afterbegin',`<div class="hub-header-actions">${btn(`${icon('queue')}<span class="hub-label">任务</span><i class="hub-count">${counts.active}</i>`,'hub-queue',`aria-label="任务队列，${counts.active} 项进行中" title="任务队列" aria-expanded="${HUB.panel==='queue'}"`,'hub-header-button')}${btn(`${icon('message')}<span class="hub-label">消息</span><i class="hub-count">${counts.unread}</i>`,'hub-messages',`aria-label="消息中心，${counts.unread} 条未读" title="消息中心" aria-expanded="${HUB.panel==='messages'}"`,'hub-header-button')}${btn(icon('help'),'hub-help','aria-label="帮助与常见问题" title="帮助与常见问题"','hub-header-button hub-icon-button')}${btn(`${icon('feedback')}<span class="hub-label">反馈</span>`,'product-feedback','aria-label="意见反馈" title="意见反馈"','hub-header-button hub-feedback-button')}</div>`);
 const save=$('save-status');if(save&&!/待保存|保存中|保存失败/.test(save.textContent))save.textContent=hubSaveText();hubBadges();
}
function hubPanelRender(){let panel=$('hub-panel');if(!panel){panel=document.createElement('section');panel.id='hub-panel';panel.className='hub-panel';panel.tabIndex=-1;panel.setAttribute('aria-label','工作台状态');document.body.append(panel);}panel.hidden=!HUB.panel;if(!HUB.panel)return;
 const close=btn('×','hub-close','aria-label="关闭面板"','hub-close');
 if(HUB.panel==='queue'){const rows=hubTaskRows().filter(x=>HUB.filter==='all'||hubTaskGroup(x.status)===HUB.filter);panel.innerHTML=`<div class="hub-panel-head"><div><small>LOCAL TASKS</small><h2>任务队列</h2></div>${btn('刷新','hub-refresh','','small')}${close}</div><div class="hub-panel-tabs">${[['active','进行中'],['failed','需处理'],['done','已完成'],['all','全部']].map(([key,name])=>btn(name+' '+hubTaskRows().filter(x=>key==='all'||hubTaskGroup(x.status)===key).length,'hub-filter',`data-filter="${key}" aria-pressed="${HUB.filter===key}"`,HUB.filter===key?'active':'')).join('')}</div>${HUB.loadError?`<p class="hub-panel-warning">${esc(HUB.loadError)}</p>`:''}${HUB.loading?'<p class="hub-panel-note">正在读取各项目的任务记录…</p>':''}<div class="hub-panel-list">${rows.length?rows.map(x=>`<article class="hub-task"><div><span class="hub-task-kind">${x.kind==='video'?'生视频':'AI 任务'}</span><time>${hubClock(x.at)}</time></div><strong>${esc(x.name)}</strong><small>${esc(x.project)} · ${esc(hubTaskLabel(x))}</small>${x.error?`<p class="hub-task-error">${esc(x.error)}</p>`:''}${S.projects.some(p=>p.id===x.projectId)?btn('打开来源','hub-open-task',`data-id="${esc(x.id)}"`,'small'):''}</article>`).join(''):`<div class="hub-panel-empty">${HUB.loading?'正在读取…':HUB.filter==='all'?'还没有任务。完成 AI 分析或提交视频任务后会出现在这里。':'此分类暂无任务。'}</div>`}</div><p class="hub-panel-note">显示观澜本机真实记录；视频任务需要自行配置相应服务。</p>`;return;}
 if(HUB.panel==='messages'){const notices=hubNotices();panel.innerHTML=`<div class="hub-panel-head"><div><small>LOCAL NOTICES</small><h2>消息中心</h2></div>${btn('全部已读','hub-read','','small')}${close}</div><div class="hub-panel-list">${notices.length?notices.map(x=>`<article class="hub-notice ${x.read?'':'unread'}"><div><span>${esc(x.project)}</span><time>${hubClock(x.at)}</time></div><p>${esc(x.text)}</p>${S.projects.some(p=>p.id===x.projectId)?btn('打开来源','hub-open-notice',`data-id="${esc(x.id)}"`,'small'):''}</article>`).join(''):'<div class="hub-panel-empty">暂无消息。任务完成、失败与画布提醒会留在这里。</div>'}</div><p class="hub-panel-note">消息只保存在这台电脑，不会跨设备同步。</p>`;return;}
 panel.innerHTML=`<div class="hub-panel-head"><div><small>HELP</small><h2>帮助与问题</h2></div>${close}</div><div class="hub-help-list">${btn('从第一次打开到交付 · 使用指南','help')}${btn('查看模型连接与生成条件','settings')}${btn('导出问题反馈与诊断信息','product-feedback')}${btn('查看本机任务记录','page','data-page="history"')}</div><p class="hub-panel-note">生成失败先到任务队列查看状态和原因；界面操作问题可打开使用指南。</p>`;
}
function hubClose(){HUB.panel='';hubPanelRender();if(HUB.returnFocus?.isConnected)HUB.returnFocus.focus({preventScroll:true});HUB.returnFocus=null;}
function hubOpen(kind){const wasOpen=HUB.panel===kind;if(wasOpen){hubClose();return;}HUB.returnFocus=document.activeElement;HUB.panel=kind;hubPanelRender();$('hub-panel')?.focus({preventScroll:true});document.querySelectorAll('[data-action="hub-queue"],[data-action="hub-messages"]').forEach(b=>b.setAttribute('aria-expanded',String(HUB.panel===b.dataset.action.slice(4))));if(HUB.panel==='queue')hubLoadJobs().catch(showError);}
registerAction('hub-queue',()=>hubOpen('queue'));
registerAction('hub-messages',()=>hubOpen('messages'));
registerAction('hub-help',()=>hubOpen('help'));
registerAction('hub-close',hubClose);
registerAction('hub-filter',d=>{HUB.filter=d.filter||'all';hubPanelRender();});
registerAction('hub-refresh',()=>hubLoadJobs());
registerAction('hub-read',()=>{const ids=hubNotices().map(x=>x.id);for(const id of ids)HUB.read.add(id);try{localStorage.setItem('guanlan-hub-read',JSON.stringify([...HUB.read].slice(-500)));}catch{}for(const p of S.projects){const key='guanlan-canvas-messages-'+p.id;try{const rows=JSON.parse(localStorage.getItem(key)||'[]');for(const x of rows)x.read=true;localStorage.setItem(key,JSON.stringify(rows));if(CANVAS_DESK.projectId===p.id)CANVAS_DESK.messages=rows;}catch{}}hubPanelRender();hubBadges();canvasDeskBadges();});
registerAction('hub-open-task',async d=>{const row=hubTaskRows().find(x=>x.id===d.id);if(!row)throw Error('任务已不在列表中，请刷新');if(S.project?.id!==row.projectId)await selectProject(row.projectId);if(row.source==='history')S.page='history';else{S.page=row.source;VIDEO.jobs=HUB.remote.filter(x=>x.projectId===row.projectId);VIDEO.projectId=row.projectId;if(row.shotId){WS.selected[row.projectId]=row.shotId;WS.tab='result';WS.view='studio';}}HUB.panel='';render();});
registerAction('hub-open-notice',async d=>{const notice=hubNotices().find(x=>x.id===d.id);if(!notice)throw Error('消息已不在列表中');HUB.read.add(notice.id);try{localStorage.setItem('guanlan-hub-read',JSON.stringify([...HUB.read].slice(-500)));}catch{}if(notice.taskId)return act('hub-open-task',{id:notice.taskId});if(S.project?.id!==notice.projectId)await selectProject(notice.projectId);S.page='canvas';HUB.panel='';render();});
async function hubTrashOpen(){HUB.trash=await call('projects:archived');showModal('项目回收站',`<p class="muted">删除的项目暂存在这台电脑；恢复后会重新出现在项目库。永久删除无法撤销。</p>${HUB.trash.length?`<div class="hub-trash-list">${HUB.trash.map(row=>`<article><div><strong>${esc(row.name)}</strong><small>移入时间 ${hubClock(row.archivedAt)}</small></div><div class="toolbar">${btn('恢复项目','hub-restore-project',`data-key="${esc(row.key)}"`,'small')}${btn('永久删除','hub-purge-project',`data-key="${esc(row.key)}"`,'small danger')}</div></article>`).join('')}</div>`:'<p class="empty-inline">回收站为空。</p>'}`);}
registerAction('hub-trash',hubTrashOpen);
registerAction('hub-delete-project',d=>{const project=S.projects.find(row=>row.id===d.id);if(!project)throw Error('项目已不在项目库中');confirmAction('删除项目',`《${project.name}》将从项目库移入本机回收站，仍可在项目库右上角恢复。正在运行的模型任务不会自动取消。`,async()=>{if(S.project?.id===project.id)await persist();await call('projects:archive',project.id);S.projects=S.projects.filter(row=>row.id!==project.id);if(S.project?.id===project.id)S.project=S.projects[0]||null;S.page='projects';render();toast('《'+project.name+'》已移入回收站');});});
registerAction('hub-restore-project',async d=>{const project=C.normalize(await call('projects:unarchive',d.key));S.projects.unshift(project);if(!S.project)S.project=project;S.page='projects';closeModal();render();toast('《'+project.name+'》已恢复到项目库');});
registerAction('hub-purge-project',d=>{const row=HUB.trash?.find(item=>item.key===d.key);if(!row)throw Error('回收站记录已变化，请重新打开');showModal('永久删除项目',`<p>将永久删除《${esc(row.name)}》的项目文件与历史快照，无法从观澜恢复。共享媒体文件及已提交的外部模型任务不在此次清理范围内。</p><label>输入项目名称以确认<input id="hub-purge-name" autocomplete="off" placeholder="${esc(row.name)}"></label>`,async()=>{if($('hub-purge-name').value!==row.name)throw Error('项目名称不匹配');await call('projects:removeArchived',row.key);closeModal();toast('《'+row.name+'》已永久删除');},false,'永久删除');});
registerAction('new-project-import',async()=>{const file=await call('files:script');if(!file)return;if(!String(file.text||'').trim())throw Error('文件没有可导入的文字');NEW_PROJECT.imported={name:file.name,text:file.text};const mode=$('new-mode');if(mode&&/\.srt$/i.test(file.name))mode.value='subtitle';const status=$('new-project-file');if(status)status.textContent=file.name+' · '+file.text.length+' 字符，创建后进入剧本页核对原文。';});
document.addEventListener('input',event=>{if(event.target.id!=='hub-project-query')return;HUB.projectQuery=event.target.value;const start=event.target.selectionStart,end=event.target.selectionEnd;render();const field=$('hub-project-query');field?.focus();field?.setSelectionRange(start,end);});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&HUB.panel){hubClose();event.preventDefault();}});
document.addEventListener('click',event=>{if(!HUB.panel||event.composedPath().some(node=>node?.id==='hub-panel')||event.target.closest('[data-action="hub-queue"],[data-action="hub-messages"],[data-action="hub-help"],[data-action="canvas-desk-queue"],[data-action="canvas-desk-messages"]'))return;HUB.panel='';hubPanelRender();});
const hubPersistBase=persist;
persist=function(){const id=S.project?.id,serial=id?(HUB.saveSerial.get(id)||0)+1:0;if(id){HUB.saveSerial.set(id,serial);const save=$('save-status');if(save)save.textContent='保存中…';}return hubPersistBase().then(value=>{if(id&&S.project?.id===id&&HUB.saveSerial.get(id)===serial){const at=new Date().toISOString(),save=$('save-status');HUB.saved.set(id,at);if(save){save.textContent=hubSaveText();save.title='最后成功保存：'+new Date(at).toLocaleString('zh-CN');}}return value;}).catch(error=>{if(id&&S.project?.id===id&&HUB.saveSerial.get(id)===serial){const save=$('save-status');if(save){save.textContent='保存失败 · 见错误提示';save.title=String(error.message||error);}}throw error;});};
const hubRenderBase=render;
render=function(){hubRenderBase();hubNavMount();hubChromeMount();hubPanelRender();};
